### ISSUE TITLE
Help, maybe?

### ISSUE THREAD

**Issue by BetaDv** [lucko/LuckPerms#2386] opened 2020-06-16 21:06 UTC
This isn't really an Issue. But, more of a Suggestion or somethin'.
![Screenshot_20200616_235647_com discord](https://user-images.githubusercontent.com/62099784/84828179-4a509280-b02e-11ea-812c-fbb495c3df8e.jpg)
And,
![Screenshot_20200616_235857_com discord](https://user-images.githubusercontent.com/62099784/84828192-4faddd00-b02e-11ea-9cd3-11ae444e49a4.jpg)
He's saying that there's an api for the Ultra Permissions Plugin made by TechCode, you could contact him he says. Like, i want Migration from Ultra Permissions to Luck Perms.

**Comment by Tobi406** [comment] 2020-06-16 21:19
Duplicate of #1871

**Comment by BrainStone** [comment] 2020-06-16 21:23
We've been over this many times See #1871 and #1643.

It boils down to the API not being publically available and the storage format being an anreadable mess which is nothing short of a miracle that it even works and doesn't take minutes to load per user.

**Closed** 2020-06-20 18:07 UTC
