### ISSUE TITLE
Issue with permissions

### ISSUE THREAD

**Issue by ElBananaa** [lucko/LuckPerms#1822] opened 2019-11-26 20:56 UTC
Hey!
I'm trying to give managers of my server the permissions to set/remove parents to players. Actually, they can set parent to all players, including ranks higher than theirs. The problem is that they can change ranks of the administrators, and I don't want to. I tried few permissions, and it didn't work.
I also asked for help on discord, and despite the help of several people, my problem persists.
argument-based-command-permissions is set to true in my config file, and here is the complete verbose content: https://media.discordapp.net/attachments/241667244927483904/648904464459235348/7e3f6331b0cf9aa93e42323d615a637f.png?width=747&height=702

Is there a way to solve my issue?
Thanks in advance for any reply.

**Comment by Andre601** [comment] 2019-11-26 21:12
Did you execute the commands the players should **not** be able to run while you had verbose enabled?

**Comment by Tobi406** [comment] 2019-11-26 21:12
Try removing `luckperms.user.parent.set`

**Comment by ElBananaa** [comment] 2019-11-26 21:50
> Did you execute the commands the players should **not** be able to run while you had verbose enabled?

Yes I did, and [here](https://luckperms.net/verbose/#08vVhdKiVa) is the verbose link

**Comment by ElBananaa** [comment] 2019-11-26 21:52
> Try removing `luckperms.user.parent.set`

I tried, but if I remove this permission, the moderators can't define the rank of anybody.

**Comment by BrainStone** [comment] 2019-11-26 22:27
Just to be sure, did you restart the server after enabling `argument-based-permissions` in the LP config? Not just a reload. 

And what LP version are you using?

**Comment by ElBananaa** [comment] 2019-11-26 22:31
> Just to be sure, did you restart the server after enabling `argument-based-permissions` in the LP config? Not just a reload.
> 
> And what LP version are you using?

I did, and i'm using the latest version (v5.0.8)

**Comment by BrainStone** [comment] 2019-11-26 22:34
@lucko ya broke it!

**Comment by lucko** [comment] 2019-11-26 23:15
Could you send a link to the actual verbose results instead of just a picture :)

**Comment by ElBananaa** [comment] 2019-11-26 23:21
> Could you send a link to the actual verbose results instead of just a picture :)

I already sent a link before, but here it is: https://luckperms.net/verbose/#08vVhdKiVa

**Comment by ElBananaa** [comment] 2019-11-28 09:07
@lucko Did you mean results of the complete verbose (fithout filter)?

**Comment by lucko** [comment] 2019-11-29 12:18
I meant a verbose showing the issue, i.e. them having access to set admin ranks

**Comment by ElBananaa** [comment] 2019-11-29 13:17
> I meant a verbose showing the issue, i.e. them having access to set admin ranks

They don't have access to the admin ranks. They can't set their own role to admin, but they can change admin ranks to lower ranks like moderator, player, vip...
For the verbose, I'll send you one as soon as I get to my computer.

**Comment by ElBananaa** [comment] 2019-11-29 15:45
Here is the complete verbose https://luckperms.net/verbose/#HTSpr07jUt

**Comment by lucko** [comment] 2019-11-29 17:10
It seems to be returning correctly?

![](https://i.imgur.com/7PsYck7.png)

**Comment by ElBananaa** [comment] 2019-11-29 17:44
@lucko It does, But as I said, the problem is that moderators can set parent for the administrators, whereas they shouldn't be able to.

**Comment by ElBananaa** [comment] 2019-11-30 14:43
On the screen under, you can see that I can set the default group as a moderator (Which is what I want), the problem is that I can set the default group to everyone, including administrators (While I should not be able to) I hope it's a little clearer (And btw, thanks for help 😃)

![adedab3152bcef05d4717d45fe0c2511](https://user-images.githubusercontent.com/53318613/69901861-64bf6900-1387-11ea-9271-e52514f5bb8a.png)

**Comment by BrainStone** [comment] 2019-11-30 16:56
In short they have argument based perms enabled but none of them seem to be checked.

**Comment by ElBananaa** [comment] 2019-11-30 20:43
> In short they have argument based perms enabled but none of them seem to be checked.

Argument based perms are enabled, and they are working, because I use permissions like `luckperms.user.parent.set.admin` which is set to false, so they can't use the command /lp user test parent set admin as example.
I don't know if this is useful, but here is my lp editor (Hope It could help you): https://editor.luckperms.net/eVrHo9vGgJ

**Comment by BrainStone** [comment] 2019-11-30 21:34
So then doesn't that solve your initial issue then?  
Because initally you said that exactly that isn't working.

**Comment by ElBananaa** [comment] 2019-11-30 22:09
> So then doesn't that solve your initial issue then?
> Because initally you said that exactly that isn't working.

I just noticed that I had not expressed myself well in my initial message, I just modified it.

**Comment by BrainStone** [comment] 2019-11-30 22:35
So you want to prevent group a from being able to remove group b from people being in group c?

**Comment by ElBananaa** [comment] 2019-11-30 22:37
> So you want to prevent group a from being able to remove group b from people being in group c?

Yep, that's it. Sorry if i'm not very clear 😅

**Comment by BrainStone** [comment] 2019-11-30 22:38
Do all players in group c also have group b?

**Comment by ElBananaa** [comment] 2019-11-30 22:40
No they don't. Since group c has permission '*', I thought it wasn't necessary

**Comment by lucko** [comment] 2019-12-02 21:05
Duplicate of #1512

**Closed by lucko** 2019-12-02 21:05 UTC
Labels: status: need more info, type: issue
