### ISSUE TITLE
LuckyPerms for Modded Minecraft Server?

### ISSUE THREAD

**Issue by quin2k** [lucko/LuckPerms#396] opened 2017-07-26 10:39 UTC
So, I'm trying to use LuckyPerms on my test server before trying it on the full modded servers (converting from PEX if it works) but it's throwing an error.  Setup is kcauldron / spigot / forge 1.7.10; disabled most plugins so that shouldn't be the issue, though we will/do use bungee on our main servers.

Was using LuckPerms-Bukkit-Legacy-3.2.57.jar - even tried throwing in the non-legacy and bungee plugin in desperation and get the same error:
https://pastebin.com/imDZHFhC

**Comment by lucko** [comment] 2017-07-26 12:48
This is a Thermos/KCauldron bug.

Duplicate of:
CyberdyneCC/Thermos#498 #193 #167 #157 #153 #293 #308

There's a workaround you can use here:
https://github.com/CyberdyneCC/Thermos/issues/498#issuecomment-247083549

(I also suggest you stop using / don't use crappy bukkit-forge hacks, and instead use [Sponge](https://www.spongepowered.org/).

**Closed by lucko** 2017-07-26 12:48 UTC

**Comment by liach** [comment] 2017-07-26 14:46
People cannot see that Thermos issue any more

**Comment by lucko** [comment] 2017-07-26 16:13
Oh right, they removed their issues tab. Nice! :+1:

The comment basically outlined a workaround with SpecialSource. It's an issue with Thermos/KCauldron and Java 8.

I don't really remember the exact details, so I'm afraid unless anyone else can recall how to do it, you're on your own.

(also, to clarify, this has **nothing** to do with LuckPerms)

**Comment by quin2k** [comment] 2017-07-26 22:25
> (I also suggest you stop using / don't use crappy bukkit-forge hacks, and instead use Sponge.

So essentially you do not support modded minecraft below 1.10.2, as that is the lowest version of Sponge Forge available, and the only other way to get plugins and mods to play together is KCauldron (and I guess Thermos).  Might save you some unwanted issues if you mentioned somewhere that LuckPerms-Bukkit-Legacy is meant for vanilla Minecraft only.

**Comment by quin2k** [comment] 2017-07-26 22:52
Here, since you keep linking a dead resource, here is a copy of what KaiKikuchi commented on Sep 14 2016:
> The solution is so easy that I wonder why nobody tested it.
>
> The SpecialSource library included with Thermos uses ASM4.
> Updating it to the latest version will fix the issue.
>
> This is how I fixed it:
> - Navigate to libraries\net\md-5\SpecialSource\1.7-SNAPSHOT folder
> - Delete the SpecialSource-1.7-SNAPSHOT.jar jar file
> - Download SpecialSource v1.7.4Copy the jar file to the libraries\net\md-5\SpecialSource\1.7-SNAPSHOT folder
> - Rename the jar file you just copied to SpecialSource-1.7-SNAPSHOT.jar
>
> I am using Thermos 1.7.10-1614.56, but I think the fix should be the same or similar for other Thermos versions.

I managed to get Google to give me the cache of the page in question.

**Comment by lucko** [comment] 2017-07-26 23:41
> So essentially you do not support modded minecraft below 1.10.2, as that is the lowest version of Sponge Forge available, and the only other way to get plugins and mods to play together is KCauldron (and I guess Thermos). Might save you some unwanted issues if you mentioned somewhere that LuckPerms-Bukkit-Legacy is meant for vanilla Minecraft only.

LuckPerms is released on the Spigot forums, and intended for use by Paper/Spigot/CraftBukkit servers running 1.7 and above.

It will work with Cauldron/KCauldron/Thermos, however, I cannot help you if it doesn't work / breaks.

My suggestion for people looking to run modded servers with plugins is to use Sponge, as it's API is built with this in mind.

Basically, yeah, LP might work with KCauldron, but I don't "officially" support it.

I hope that makes sense, and sorry I can't be of much help.
