### ISSUE TITLE
Java 11/13 console error.

### ISSUE THREAD

**Issue by andrewkm** [lucko/LuckPerms#1930] opened 2020-01-14 16:37 UTC
Going from Java 8 to 11 / 13 is shooting the following on startup. All other plugins are fine.
https://i.imgur.com/OkysfE7.png

Unsure if it's something I should worry about or simply ignore.
Luckperms 4.4.31

PS: Sorry I didn't paste the error, it's not in Spigot logs, its on the Java side.

**Comment by lucko** [comment] 2020-01-14 16:43
Duplicate of #952 - yep you're safe to just ignore it.

**Closed by lucko** 2020-01-14 16:43 UTC
