### ISSUE TITLE
Meta Not Working (SkyClaims) - Sponge

### ISSUE THREAD

**Issue by Rob5Underscores** [lucko/LuckPerms#200] opened 2017-02-28 16:09 UTC
Hi,

Meta as defined here: https://github.com/DevOnTheRocks/SkyClaims/wiki/Options does not take effect. In particular, the default biome. 

Here is my default groups data (yml format): http://pastebin.com/MQ9nCN27
The meta was added via in-game command.

SpongeForge 2177 and LuckPerms 3.0.4

Worth noting that this meta had previously worked but recent changes (before 3.x.x) broke it.

**Comment by lucko** [comment] 2017-02-28 17:27
Update to the latest version.

**Comment by Rob5Underscores** [comment] 2017-03-02 20:11
@lucko 
Using 3.0.9 which was latest when you closed the thread, issue not fixed.
Thanks

**Comment by lucko** [comment] 2017-03-02 20:56
You said "LuckPerms 3.0.4", which was before 3.0.8, when a meta bug was fixed. https://ci.lucko.me/job/LuckPerms/71/

Is it still an issue on the very latest build? Can you please confirm it's not a bug with SkyClaims?

**Comment by Rob5Underscores** [comment] 2017-03-02 21:28
I spoke with Mohron (SkyClaims dev) who assured me it wasn't anything on his end as he is just using Sponge API and couldn't remember changing anything about this recently. I'll send this issue to him to see if he has any input.

Thanks!

**Comment by Mohron** [comment] 2017-03-02 21:34
@lucko I'm far from perfect but all I'm doing is getting options from Sponge API [here](https://github.com/DevOnTheRocks/SkyClaims/blob/development/src/main/java/net/mohron/skyclaims/permissions/Options.java) and validating the input. In the case of the biomes, it will completely ignore invalid biomes, so that could be the case.

**Comment by lucko** [comment] 2017-03-02 21:39
Yeah, that looks all fine. 

Update to the latest LP & test again. Otherwise, I need the output of `/lp user <user> meta info` for the player having issues.

**Comment by Rob5Underscores** [comment] 2017-03-02 21:54
Will do so and report back asap.

**Comment by lucko** [comment] 2017-03-05 17:51
Assuming this is now fixed?

**Closed by lucko** 2017-03-05 17:51 UTC

**Comment by Rob5Underscores** [comment] 2017-03-05 17:54
Apologies for the delay.

I haven't tested it yet, but have just now updated to 3.0.11 - will report back asap.
