### ISSUE TITLE
Potential compatibility issue with MySQL 8

### ISSUE THREAD

**Issue by Tommakazi** [lucko/LuckPerms#2658] opened 2020-10-08 22:02 UTC
I did a fresh install of LuckPerms on Ubuntu 20 with Bungeecord, Spigot, and MySQL 8. The only DB tables that were created were "messages" and "user_permissions". I looked into the MySQL.sql DB Schema for LuckPerms and found that the "tracks" table uses "groups" as a column name and "groups" is a reserved word in MySQL 8 and therefore cannot be used in this way. I am not sure what else this may affect, but it seems that MySQL 8 is not compatible with the current version of LuckPerms.

**Comment by lucko** [comment] 2020-10-12 21:26
Thanks for the report, but I'm not sure that's actually the cause. I've used LP with MySQL 8 with no problems before.

Try deleting all LP tables and restarting the server to see if they generate correctly.

**Comment by Tommakazi** [comment] 2020-10-12 21:35
I tried that and had the same behavior. I also tried reinstalling
completely. I switched to MariaDB and did not have any issues at all.

**Comment by Tommakazi** [comment] 2020-10-12 21:37
I only noticed it when I went to manually build the tables.

**Comment by lucko** [comment] 2020-11-10 23:04
I believe this has been fixed by 00d4a2a1dac1b4ebcb067f746010b35d8c889669

I've confirmed that `groups` has been correctly escaped in all places, so even though it is a reserved keyword it should be fine!

**Closed by lucko** 2020-11-10 23:04 UTC
Labels: type: issue
