### ISSUE TITLE
Issue with JPremium and DynamicBungeeAuth (Login System)

### ISSUE THREAD

**Issue by ManuGooX** [lucko/LuckPerms#2073] opened 2020-03-17 11:29 UTC
![image](https://user-images.githubusercontent.com/40543551/76851977-a0a11000-684a-11ea-8d9e-c8a2d593d8d7.png)

This problem happened to me yesterday when I was testing a new login plugin, synce now I've been using Authme but I decided to change it because problems with fastlogin and mojang api.

Now it works perfect except for this issue. It happens every time a player enter for a second time to a server, her offline uuid change, luckperms detects this and remove all his data, permission, permission group.

**Comment by RJHaytree** [comment] 2020-03-17 12:28
I personally don't see how, or why LuckPerms would cater to the demands of this plugin. LuckPerms must use the player's UUID, there is no way around that, nor is their a viable alternative. If the plugin is consistently changing the player's UUID, the plugin is incompatible with a vast amount of plugins, really any which use the player's UUID for storage.

**Comment by Andre601** [comment] 2020-03-17 13:45
This is a common issue you will face with offline servers. LuckPerms uses UUIDs for identifying players because unlike names are UUIDs unique per player. This however is getting lost when you run the server in cracked/offline mode as the server itself now creates the UUID based on the player's name.
Spigot even gives a hug warning when running in offline mode:
```
**** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
The server will make no attempt to authenticate usernames. Beware.
While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
To change this, set "online-mode" to "true" in the server.properties file.
```

This is something that can't really (And most likely won't really) be fixed on LPs end as it is not an issue, but intended behaviour.

**Closed** 2020-03-19 11:36 UTC
Labels: type: question
