### ISSUE TITLE
Major plugin compatibility issues

### ISSUE THREAD

**Issue by MackenzieMolloy** [lucko/LuckPerms#1920] opened 2020-01-06 20:49 UTC
I'm getting this error spamming my console when using various plugins.
https://pastebin.com/E92YzFha
Using the latest luckperms (5.0.52)

**Comment by Andre601** [comment] 2020-01-06 22:16
[default-assignment]: https://github.com/lucko/LuckPerms/wiki/Extensions#extension-default-assignments
[legacy-extension]: https://github.com/lucko/LuckPerms/wiki/Extensions#extension-legacy-api
[update]: https://github.com/lucko/LuckPerms/wiki/Upgrading-from-v4-to-v5
[default-groups]: https://github.com/lucko/LuckPerms/wiki/Default-Groups

# Common v5 issues

## Plugin x spams errors about LuckPerms
If the error contains `Caused by: java.lang.NoClassDefFoundError: me/lucko/luckperms/LuckPerms` then the plugin uses the old v4 API of LuckPerms, while you're using LuckPerms v5.
A solution to this problem is to [download and install the legacy-API extension][legacy-extension] into the `extension` folder located inside the `LuckPerms` folder. If no such folder exist, create it.
Also, please contact the developer of the plugin and ask them to update to the latest release of the LuckPerms API.

If the error, however, contains `Caused by: java.lang.ClassNotFoundException: net.luckperms.api.LuckPerms` then it is the exact opposite and you're using LuckPerms v4 while the plugin is using LuckPerms v5.
In that case, do you need to update LuckPerms to v5. A page explaining how to migrate from v4 to v5 can be found [here][update].

**Comment by BrainStone** [comment] 2020-01-06 22:35
10/10 for reading the error messages Andre.  
Basic troubleshooting has been passed. They also have the legacy API extension.

Please read the error messages before copy pasting unrelated canned answers.

**Comment by MackenzieMolloy** [comment] 2020-01-07 09:36
> 10/10 for reading the error messages Andre.
> Basic troubleshooting has been passed. They also have the legacy API extension.
> 
> Please read the error messages before copy pasting unrelated canned answers.

I was told to it was a bug and that I should put it here

**Comment by i9hdkill** [comment] 2020-01-07 10:04
That comment didn't meant you, all good. (It was about a comment that has been deleted)
Please update to latest, which is 5.0.52 atm if you havent already and post error logs that were produced with that exact lp version

**Comment by MackenzieMolloy** [comment] 2020-01-07 10:15
That is on the latest version, the developer of MyPrefix (the plugin that caused those errors to emitted) has updated his plugin and these are the error i get now;
https://pastebin.com/Vd9bx3J4

**Comment by i9hdkill** [comment] 2020-01-07 12:00
Issue in vks plugin. He is setting a nullworld as guessed yesterday. But that doesnt make sense to me. Not a lp issue I suppose

**Comment by Turbotailz** [comment] 2020-01-07 12:51
Since @vk2gpz is probably too busy making his 1000th plugin, I'll add the things he said to @MackenzieMolloy on Discord:

> then you can ask them to make sure that "null" for "world" parameter is supported for setPlayerPrefix, method. convention is that if "null" is specified for "world", the prefix should be applied to the player regardless of the world the player is in.

> null is valid option there.

> other permission plugins will apply prefix regardless of world if null was specified.

> they really need to fix it to support null in world
> to comply with Vault's convention

> no, i have no interest in talking to those who just ignore the specification of Vault.
> i do not have any explicit support for LP.
> they're the one claiming that LP works with Vault... which clearly does not since they do not follow the specification of Vault.

> it's fine for them to claim that "LP is not like other perm plugins"
> but he needs to learn that if he claims that LP is supported by Vault, they need to follow Vault's specification.

> that's why i'm telling you, you need to ask LP to fix itself to comply with Vault's specification if they're hooking onto Vault.

I'm not sure exactly what needs to be done but we need input from @lucko on this one.

**Comment by Andre601** [comment] 2020-01-07 12:57
Is this confirmed in the official Javadoc of Vault?

**Comment by i9hdkill** [comment] 2020-01-07 13:05
Yes andre, see the link I provided soem comments earlier.

Guess needs a small change here, unless my thinking is too easy:
https://github.com/lucko/LuckPerms/blob/master/bukkit/src/main/java/me/lucko/luckperms/bukkit/vault/LuckPermsVaultChat.java#L226

**Comment by Andre601** [comment] 2020-01-07 13:36
> Yes andre, see the link I provided soem comments earlier.
> 
> Guess needs a small change here, unless my thinking is too easy:
> https://github.com/lucko/LuckPerms/blob/master/bukkit/src/main/java/me/lucko/luckperms/bukkit/vault/LuckPermsVaultChat.java#L226

LuckPerms seems to already handle it as in the two below examples:
https://github.com/lucko/LuckPerms/blob/242993763c22b2d20e181422628d8ba01a6311f4/bukkit/src/main/java/me/lucko/luckperms/bukkit/vault/LuckPermsVaultChat.java#L236

https://github.com/lucko/LuckPerms/blob/242993763c22b2d20e181422628d8ba01a6311f4/bukkit/src/main/java/me/lucko/luckperms/bukkit/vault/LuckPermsVaultChat.java#L276

**Comment by MackenzieMolloy** [comment] 2020-01-07 13:44
vk2gpz said:
NPE is coming out from 
>         if ((key.equalsIgnoreCase(DefaultContextKeys.SERVER_KEY) || key.equalsIgnoreCase(DefaultContextKeys.WORLD_KEY)) && value.equalsIgnoreCase("global")) {

**Comment by lucko** [comment] 2020-01-07 14:38
Fixed in the above commit.

> no, i have no interest in talking to those who just ignore the specification of Vault.
i do not have any explicit support for LP.
they're the one claiming that LP works with Vault... which clearly does not since they do not follow the specification of Vault.
it's fine for them to claim that "LP is not like other perm plugins"
but he needs to learn that if he claims that LP is supported by Vault, they need to follow Vault's specification.

@vk2gpz It was just a bug? A bit wild to just immediately jump to the conclusion that I'm purposely "ignoring the specification", or conclude that a misimplementation of the Vault API is a result of an unwillingless to "learn" to be compatible on my part, lol.

I'm always happy to look into issues and fix bugs, but at least give me 24 hours to respond before jumping to "oh it must just be because they're incompetent and/or think they're too special to play by the rules" - hopefully you can see how absurd that is.

Turns out it was a very simple fix! @MackenzieMolloy please could you confirm that the issue is fixed in the latest version. (v5.0.53, download from here https://luckperms.net/)

**Comment by Andre601** [comment] 2020-01-07 14:44
Also, to make things clear: To my knowledge does vault is not supporting LP, but more LP is supporting Vault... It's a minor, yet important details if you ask me.
And if Vault actually does support LP: Cool.

**Comment by MackenzieMolloy** [comment] 2020-01-07 14:48
The latest commit has fixed my issue on the test server - let me try it in production.

**Comment by MackenzieMolloy** [comment] 2020-01-07 15:01
The latest comment has also fixed my issue in production - Thanks for the fix.

**Comment by lucko** [comment] 2020-01-07 15:07
Great, thanks :)

**Closed** 2020-01-07 15:07 UTC
Labels: type: issue

**Comment by vk2gpz** [comment] 2020-01-07 20:16
this is why I told @MackenzieMolloy not to just copy & paste conversations...(by doing so, it will lose the context) I made those comment in response to your dev team's comment saying that I should not pass "null" and I need to fix my plugin even after I pointed out that that's what Vault informing other developers that it is a valid value, and was not made against you @lucko.  Anyway, you did find the place to put those 32 characters.  My estimation of 3 min job was rather accurate ;)  Glad that you have one more happy user.
