### ISSUE TITLE
Bug with Viaversion last version

### ISSUE THREAD

**Issue by msmanui** [lucko/LuckPerms#3059] opened 2021-06-08 17:58 UTC
Luckperms is having issues with viaverison as they changed somethings of their api.

https://i.gyazo.com/1e5dcf861657be1d4cf13df882e8a647.png

**Comment by emilyy-dev** [comment] 2021-06-08 17:59
1. Follow the issue template, **do not ignore it!** It helps us help you
2. Update LuckPerms https://luckperms.net/download

**Comment by Sneakometer** [comment] 2021-06-09 01:14
I can confirm this for the latest luckperms release 5.3.42 and ViaVersion 4.0.0.
ViaVersion changed some things in their api and luckperms needs to be updated.
You can find the changes made to the ViaVersion API here: https://gist.github.com/KennyTV/3778685985ddc45bd99e003191ff02eb

Affected Platform: Bukkit

**Comment by Pace1337** [comment] 2021-06-09 14:55
I have this issue as well. https://paste.md-5.net/afoqolifis.apache

**Comment by 2008Choco** [comment] 2021-06-09 21:15
This is caused by the Adventure library platform implementations, [KyoriaPowered/adventure-platform](https://github.com/KyoriPowered/adventure-platform), specifically [BukkitFacet$ViaHook:L347](https://github.com/KyoriPowered/adventure-platform/blob/master/platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/BukkitFacet.java#L347) not cooperating with the 4.0.0 API of ViaVersion. Not technically an issue to do with LuckPerms, a PR needs to be made to Adventure Platform.

**Comment by lucko** [comment] 2021-06-13 12:09
I've published a new release with this fix included (it's been fixed in dev builds for a little while)

**Closed by lucko** 2021-06-13 12:09 UTC
Labels: type: issue
