### ISSUE TITLE
> WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by alsoGAMER** [lucko/LuckPerms#1903] opened 2019-12-29 12:47 UTC
WARNING: Illegal reflective access by me.lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader (file:/srv/mc/plugins/LuckPerms-Bukkit-5.0.39.jar) to method java.net.URLClassLoader.addURL(java.net.URL)

WARNING: Please consider reporting this to the maintainers of me.lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader

WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations

WARNING: All illegal access operations will be denied in a future release

PaperSpigot Version: git-Paper-31 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
Java Version: build 11.0.5+10-post-Debian-1deb10u1

**Comment by Andre601** [comment] 2019-12-29 12:52
Duplicate of #952

**Closed** 2019-12-31 21:27 UTC
