### ISSUE TITLE
Warning about something.. just thought i should post

### ISSUE THREAD

**Issue by M-Ashoor** [lucko/LuckPerms#1873] opened 2019-12-14 09:35 UTC
[WARNING] ....WARNING: An illegal reflective access operation has occurred

[WARNING] WARNING: Illegal reflective access by me.lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader (file:/home/gs-41341/plugins/LuckPerms-Bukkit-5.0.21.jar) to method java.net.URLClassLoader.addURL(java.net.URL)

[WARNING] WARNING: Please consider reporting this to the maintainers of me.lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader

[WARNING] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations

[WARNING] WARNING: All illegal access operations will be denied in a future release

**Comment by Andre601** [comment] 2019-12-14 11:27
Can be ignored as it should be fixed in latest dev release

**Comment by lucko** [comment] 2019-12-14 16:01
Duplicate of https://github.com/lucko/LuckPerms/issues/952

**Closed by lucko** 2019-12-14 16:01 UTC
