### ISSUE TITLE
Startup exception

### ISSUE THREAD

**Issue by DarkFort** [lucko/LuckPerms#749] opened 2018-02-09 17:38 UTC
https://hastebin.com/gubohosila.md

**Comment by lucko** [comment] 2018-02-09 17:39
What server version?

**Comment by DarkFort** [comment] 2018-02-09 17:43
PaperSpigot 1.12.2
Latest LuckPerms on jenkins

**Comment by lucko** [comment] 2018-02-09 17:43
which version of Paper

**Comment by DarkFort** [comment] 2018-02-09 17:44
git-Paper-1305

**Comment by lucko** [comment] 2018-02-09 17:44
Try updating to the latest version.

**Comment by DarkFort** [comment] 2018-02-09 17:46
I'll try to do it at night, when online will be less. Please, do not close the issue

**Comment by lucko** [comment] 2018-02-09 18:11
You can re-open it if the issue isn't fixed by updating.

**Closed by lucko** 2018-02-09 18:11 UTC
Labels: need more info
