### ISSUE TITLE
LuckPerms not exporting prefixes correctly

### ISSUE THREAD

**Issue by PiggyPiglet** [lucko/LuckPerms#418] opened 2017-08-05 00:50 UTC
Just a little bug, when exporting your permissions, prefix's aren't being exported correctly. For example, the exported prefix looks like this,
`/luckperms group developer permission set prefix.10.&8[&5Developer&8] true creative`
when it should look like
`/luckperms group developer meta addprefix 10 &8[&5Developer&8] creative`
It still works, but it will not show the prefix when showing meta info.

**Comment by lucko** [comment] 2017-08-05 15:36
I'm curious about this.

> It still works, but it will not show the prefix when showing meta info.

Are you sure it doesn't work using the latest dev build? Adding as a permission in that way should still work.

**Comment by PiggyPiglet** [comment] 2017-08-06 09:13
I just updated and tested, it seems it works now (May of been fixed in a previous update, or can only happen in certain circumstances). Although it doesn't really make a difference, I still think it should export using meta commands instead of prefixes.

**Comment by lucko** [comment] 2017-08-06 11:57
Yep, I understood that bit.

However, it should still be working. (in other words, this is an enhancement, not a bug)

**Comment by PiggyPiglet** [comment] 2017-08-10 09:15
Can you change the label to enhancement please? I'm not sure how to.

**Comment by lucko** [comment] 2017-08-14 16:58
Closed in 046202719a4903d1e0584d86c1f3597e9500843d

**Closed by lucko** 2017-08-14 16:58 UTC
Labels: enhancement
