### ISSUE TITLE
Groups aren't being saved.

### ISSUE THREAD

**Issue by zStian** [lucko/LuckPerms#1659] opened 2019-08-06 15:30 UTC
When using storage-method YAML-combined the groups don't save when created in-game. 
Running LuckPerms v4.4.1, Spigot v1.14.4
![3fc84982665bd79e3cf77539c67fa190](https://user-images.githubusercontent.com/32354998/62553570-db33da80-b86f-11e9-98ab-86acc425b9b3.png)
Also this appears when checking on groups in-game. (stays the same after I create a group)

**Comment by Andre601** [comment] 2019-08-06 16:14
Can you show us your config settings?
Also, what are the steps you tried?

**Comment by zStian** [comment] 2019-08-06 16:26
Config: https://pastebin.com/pt5Jg9QD
Also the I posted everything I did in detail here: https://www.spigotmc.org/threads/luckperms-an-advanced-permissions-plugin.174259/page-139

**Comment by Andre601** [comment] 2019-08-06 16:35
Is yaml really needed?
If you only want to use it to later manually edit it: Don't.
We highly recommend to NOT edit files manually since LP has a different syntax than PEX and one typo can mess up the entire group system.

We recommend using the web editor (`/lp editor`) to edit permissions of groups and users much easier.
You still have to create groups manually but pretty much anything else can be done through the web editor.

That way can you f.e. keep the default storage type (h2) and won't deal with problems like right now.
Your error could perhaps be caused by a malformed file or wrong saving... But we can't tell without knowing any errors or similar.

**Comment by zStian** [comment] 2019-08-06 16:46
It's an advertised feature and I love editing files manually, but I do realize that if I make one teeny tiny mistake I might ruin the whole thing. I've always ran different servers for testing stuff like this, and I really would like to keep doing it. Is there no way to figure out the problem? I can send more stuff and make an essay post on (specifically) what I'm doing and what is not working, even though it seems very simple. I find it hard to believe that no one else is using this method, and that I'm the first person to make note of the issue (individually or collectively).

**Comment by Andre601** [comment] 2019-08-06 16:55
> It's an advertised feature and I love editing files manually, but I do realize that if I make one teeny tiny mistake I might ruin the whole thing.

Yeah. But the previously mentioned Web editor would be way easier to use and it is guaranteed that there wouldn't be an issue causing your storage to get messed up.
Also yaml storage will increase the used diskspace.
> I've always ran different servers for testing stuff like this, and I really would like to keep doing it. Is there no way to figure out the problem?

I honestly don't get the first sentence, but for the other: One thing would be to check the console for any errors that might appear. If there's an error, then it most likely is an unwanted thing happening.
> I can send more stuff and make an essay post on (specifically) what I'm doing and what is not working, even though it seems very simple.

This would definitely help us understand what could cause this problem.
> I find it hard to believe that no one else is using this method, and that I'm the first person to make note of the issue (individually or collectively).

From what I remember are you really the first one having those issues.
Since LP doesn't save any bStats data is it hard to get right numbers but my assumption is that most people either stick with the default h2-storage, use MySQL or MariaDB for network synchronization or the normal (split up) yaml-storage.

**Comment by zStian** [comment] 2019-08-06 17:55
LuckPerms startup (nothing shows up, also highlighted everything else LuckPerm related on startup, no issues. (https://pastebin.com/4NTAuKQ8)
Also, in the yaml-storage folder, every YAML file except groups.yml and tracks.yml seem to be saving. Also I tried using another method, and it worked perfectly so it only occurs when storing as YAML-combined. 

Also what I tried to write above is that every time I edit a file I make a new copy and keep the old one in case I screw up. I also never test the new file on my main server but try it on a different server so if I do mess up, nothing really happens. I dont know how this works compared to PEX, but PermissionsEX also had a fragile group file, so if you added or removed something that you weren't supposed to touched things would easily crash and burn. What I'm trying to say is that I doubt messing up the files would be a problem. 

Also this isn't as much related to the issue as it is a question, but, when using MySQL or MariaDB as recommended in the main plugin thread on the Spigot Forums, would I not be able to edit my groups in text format at all?

Diskspace won't be a problem.

**Comment by Andre601** [comment] 2019-08-06 17:59
MySQL and MariaDB are mostly recommended when you're setting up a network of servers and want groups and permissions to be the same across those.
You can obviously not edit those types since they aren't file-based storage types that are human-readable.
But like I mentioned it multiple times is the web editor the best solution for editing permissions.

**Comment by zStian** [comment] 2019-08-06 18:02
Yeah I understand but previously when I used PEX I could edit the files as they were on my minecraft-server, then they'd be uploaded to MySQL and synced to my other servers (or something like that). Also I tried /lp debug and something happened, don't know if related.
(https://pastebin.com/1BwnS2yY)

**Comment by zStian** [comment] 2019-08-07 16:40
Will this be looked into or will the feature to store as yaml-combined be dismissed?

**Comment by Andre601** [comment] 2019-08-07 16:51
Luck has to look into this and I asked him to do so.
All we can do is wait for him to respond.

**Comment by lucko** [comment] 2019-12-02 20:59
Duplicate of #1793 - this is now resolved :)

**Closed by lucko** 2019-12-02 20:59 UTC
Labels: type: issue
