### ISSUE TITLE
Stacking doesn't work/broken.

### ISSUE THREAD

**Issue by icehenrik** [lucko/LuckPerms#901] opened 2018-04-08 14:34 UTC
Mods on the discord server have seen on my setup and everything is setyp correct, but it dosen't show on prefixes I have set it on

**Comment by lucko** [comment] 2018-04-08 15:40
I don't know how you expect me to help you without providing any sort of information about:

- your setup
- how you've configured the plugin
- what stacking settings you have
- what groups/prefixes you've assigned to the user
- the things you've done so far to try to resolve / diagnose the problem yourself

**Comment by Explosivee** [comment] 2018-04-08 16:45
![image](https://user-images.githubusercontent.com/35429381/38469971-5aa31b16-3b65-11e8-8647-e83f176a7d24.png)

**Comment by lucko** [comment] 2018-04-09 20:10
I'm unable to reproduce.

```
> lp creategroup vip
[21:04:06 INFO]: [LP] vip was successfully created.
> lp creategroup vip+
[21:04:08 INFO]: [LP] vip+ was successfully created.
> lp creategroup mod
[21:04:10 INFO]: [LP] mod was successfully created.
> lp creategroup admin
[21:04:13 INFO]: [LP] admin was successfully created.
> lp group mod meta addprefix 30 "&d[MOD]"
[21:04:31 INFO]: [LP] mod had prefix '[MOD]' set at a priority of 30 in context global.
> lp group admin meta addprefix 40 "&d[ADMIN]"
[21:04:43 INFO]: [LP] admin had prefix '[ADMIN]' set at a priority of 40 in context global.
> lp group vip meta addprefix 10 "&e[VIP]"
[21:04:55 INFO]: [LP] vip had prefix '[VIP]' set at a priority of 10 in context global.
> lp group vip+ meta addprefix 10 "&6[VIP+]"
[21:05:04 INFO]: [LP] vip+ had prefix '[VIP+]' set at a priority of 10 in context global.
> lp group default meta addprefix 1 &7[MEMBER]
[21:05:21 INFO]: [LP] default had prefix '[MEMBER]' set at a priority of 1 in context global.
[21:05:29 INFO]: <[MEMBER]Luck> hi
> vaultchatformatter reload
[21:05:51 INFO]: Reloaded successfully.
[21:05:55 INFO]: [MEMBER]Luck hi
> lp reloadconfig
[21:06:11 INFO]: [LP] The configuration file was reloaded. (some options will only apply after the server has restarted)
> lp sync
[21:06:13 INFO]: [LP] An update task has been requested. Please wait...
[21:06:14 INFO]: [LP] Update task complete.
[21:06:17 INFO]: [MEMBER] Luck hi
> lp user luck parent add mod
[21:06:28 INFO]: [LP] luck now inherits permissions from mod in context global.
> lp user luck parent add vip
[21:06:31 INFO]: [LP] luck now inherits permissions from vip in context global.
[21:06:33 INFO]: [MOD] Luck hi
> lp createtrack donor
[21:07:03 INFO]: [LP] donor was successfully created.
> lp createtrack staff
[21:07:06 INFO]: [LP] staff was successfully created.
> lp track donor append default
[21:07:12 INFO]: [LP] Group default was appended to track donor.
> lp track donor append vip
[21:07:15 INFO]: [LP] Group vip was appended to track donor.
[21:07:15 INFO]: [LP] default ---> vip
> lp track donor append vip+
[21:07:17 INFO]: [LP] Group vip+ was appended to track donor.
[21:07:17 INFO]: [LP] default ---> vip ---> vip+
> lp track staff append mod
[21:07:21 INFO]: [LP] Group mod was appended to track staff.
> lp track staff append admin
[21:07:24 INFO]: [LP] Group admin was appended to track staff.
[21:07:24 INFO]: [LP] mod ---> admin
> lp reloadconfig
[21:07:28 INFO]: [LP] The configuration file was reloaded. (some options will only apply after the server has restarted)
> lp sync
[21:07:32 INFO]: [LP] An update task has been requested. Please wait...
[21:07:32 INFO]: [LP] Update task complete.
[21:07:35 INFO]: [VIP] [MOD] Luck test
> lp reloadconfig
[21:07:48 INFO]: [LP] The configuration file was reloaded. (some options will only apply after the server has restarted)
> lp sync
[21:07:49 INFO]: [LP] An update task has been requested. Please wait...
[21:07:49 INFO]: [LP] Update task complete.
[21:07:52 INFO]: [MOD] [VIP] Luck test
> lp group default meta addsuffix 1 "&f: &7"
[21:08:15 INFO]: [LP] default had suffix ': ' set at a priority of 1 in context global.
[21:08:18 INFO]: [MOD] [VIP] Luck:  test
> lp reloadconfig
[21:08:32 INFO]: [LP] The configuration file was reloaded. (some options will only apply after the server has restarted)
> lp sync
[21:08:33 INFO]: [LP] An update task has been requested. Please wait...
[21:08:34 INFO]: [LP] Update task complete.
[21:08:36 INFO]: [MOD] [VIP]Luck:  test
```

Please provide specific steps (commands) to be executed in order to reproduce the issue. Feel free to re-open this ticket when you've done so. :)

**Closed by lucko** 2018-04-09 20:10 UTC
Labels: status: need more info, type: question

**Comment by icehenrik** [comment] 2018-04-09 20:27
Can you give me the plugin for vaultchatformatter? So I can try to add it on my server to see if that is the problem

**Comment by lucko** [comment] 2018-04-09 20:28
https://www.spigotmc.org/resources/vaultchatformatter.49016/

**Comment by icehenrik** [comment] 2018-04-10 19:04
Hmm. I have tried on all my servers with no luck to get all the prefixes.

**Comment by BrainStone** [comment] 2018-04-10 19:07
Some people were complaining that Deluxe Chat was causing this to break.

**Comment by icehenrik** [comment] 2018-04-10 19:12
Well I am glad that I am not using deluxechat

**Comment by icehenrik** [comment] 2018-04-10 19:15
Here is the list off my plugins: https://prnt.sc/j3hkd0
