### ISSUE TITLE
Error on bungee

### ISSUE THREAD

**Issue by 4Cris** [lucko/LuckPerms#2238] opened 2020-04-28 08:14 UTC
[09:50:35] [Netty Worker IO Thread #9/WARN] [LuckPerms]: A permission check was made for player MiniRexx523 - 0c750d53-3b16-4bef-bccd-4516bcceab97, but LuckPerms does not have any permissions data loaded for them. Perhaps their UUID has been altered since login?
[09:50:35] [Netty Worker IO Thread #9/ERROR]: java.lang.Exception
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at me.lucko.luckperms.bungee.listeners.BungeePermissionCheckListener.onPlayerPermissionCheck(BungeePermissionCheckListener.java:67)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:434)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at net.md_5.bungee.UserConnection.hasPermission(UserConnection.java:565)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at dev.aura.bungeechat.permission.PermissionManager.hasPermission(PermissionManager.java:14)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at dev.aura.bungeechat.listener.LeaveMessageListener.onPlayerLeave(LeaveMessageListener.java:16)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:434)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at dev.aura.bungeechat.listener.BungeeChatEventsListener.onPlayerLeave(BungeeChatEventsListener.java:61)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:434)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at net.md_5.bungee.connection.UpstreamBridge.disconnected(UpstreamBridge.java:65)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at net.md_5.bungee.netty.HandlerBoss.channelInactive(HandlerBoss.java:60)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:818)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[09:50:35] [Netty Worker IO Thread #9/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by Elguerrero11** [comment] 2020-04-28 10:43
I have the same error.

**Comment by lucko** [comment] 2020-04-28 12:48
Duplicate of #2107 - please see my comment there & let me know if the fix worked. :)

**Closed by lucko** 2020-04-28 12:48 UTC

**Comment by Elguerrero11** [comment] 2020-04-28 18:05
> Duplicate of #2107 - please see my comment there & let me know if the fix worked. :)

I have the same error with latest version of the plugin.

**Comment by Elguerrero11** [comment] 2020-04-29 11:25
Fixed with latest update, thanks :)
