### ISSUE TITLE
Migration from GroupManager fails (exception errors)

### ISSUE THREAD

**Issue by mrfloris** [lucko/LuckPerms#1937] opened 2020-01-18 14:42 UTC
Freshly installed Spigot 1.15.1 that i made with buildtools, got the old groupmanager/ folder and jar file and vault/cmi and luckperms

after the server started up once, i /stop it, started it again.

then typed in-game lp migration groupmanager true, and it looks like it's doing a bunch of groups and users. but the console is flooded with exception errors. 

```
>ver
[15:41:28] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-492a779-d208733 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
[15:41:28] [Server thread/INFO]: Checking version, please wait...
[15:41:29] [Thread-10/INFO]: You are 6 version(s) behind
>ver LuckPerms
[15:41:31] [Server thread/INFO]: LuckPerms version 5.0.9
[15:41:31] [Server thread/INFO]: A permissions plugin
[15:41:31] [Server thread/INFO]: Website: https://luckperms.net
[15:41:31] [Server thread/INFO]: Author: Luck
>ver GroupManager
[15:41:32] [Server thread/INFO]: GroupManager version 0.3.0
[15:41:32] [Server thread/INFO]: Provides on-the-fly system for permissions system created by Nijikokun. But all in memory, and with flat-file saving schedule.
[15:41:32] [Server thread/INFO]: Website: http://ess.khhq.net/wiki/Group_Manager
[15:41:32] [Server thread/INFO]: Authors: AnjoCaido, Gabriel Couto, ElgarL and Xadzkon
>
```
-latest.log removed-

Not sure what i am doing wrong, we've always had groupmanager on this small server and it was time with 1.15.1 to move to luckperm.

**Comment by Andre601** [comment] 2020-01-18 15:24
Your latest.log does not contain any errors.
Also, https://hasteb.in is prefered over downloading a file.

**Comment by mrfloris** [comment] 2020-01-18 15:27
Oh for cryin... i dunno how the wrong one ended up there, i am sure i checked before including it.. ok 

https://hasteb.in/kipeqoje.md

**Comment by Andre601** [comment] 2020-01-18 15:29
Do you use GroupManager from EssentialsX or the original one?
Because I think the original one might not even work with LP.

**Comment by mrfloris** [comment] 2020-01-18 15:31
This is the one i had working okay on my spigot setup for 1.15.1, 
https://www.spigotmc.org/resources/groupmanager.38875/

If you prefer i use a different build for 1.15.1 feel free to link to it, ill try that instead.

**Comment by Andre601** [comment] 2020-01-18 15:46
Looks like ther isn't even a build from the EssentialsX team

Also, that version you use seem strange and not like the original one either, so perhaps the issue is changed API stuff by that dev?

I can only suggest to use the original one to make sure it's really supported by LP.

**Comment by mrfloris** [comment] 2020-01-18 15:53
Ok, feel free to link me to the one that luckperm supports, and i will try to work it with that one.

**Comment by lucko** [comment] 2020-01-25 12:44
Try the latest LP from here: https://luckperms.net/

Should be fixed already.

**Closed by lucko** 2020-01-25 12:44 UTC
