### ISSUE TITLE
IllegalStateException: No permissions data present

### ISSUE THREAD

**Issue by A248** [lucko/LuckPerms#2131] opened 2020-04-01 21:46 UTC
**Stacktrace**
https://pastebin.com/raw/j5rbesN6

**Description**
Just a simple permissions check, originating from the TAB plugin (which, I might add, is a terrific plugin).

The calling stacktrace is off by a couple of lines due to other commits, but the calling code hasn't changed. It's just a bungeecord-specific `player.hasPermission("tab.staff")` check:

https://github.com/NEZNAMY/TAB/blob/master/src/me/neznamy/tab/shared/ITabPlayer.java#L125

https://github.com/NEZNAMY/TAB/blob/master/src/me/neznamy/tab/platforms/bungee/TabPlayer.java#L48

I'm not sure why this error occurred. It seems like a normal permissions check. I know that TAB runs almost entirely asynchronously, but LuckPerms claims to support full concurrent API usage.

**Comment by LucidAPs** [comment] 2020-04-01 22:10
Lets add this one too, same thing.
https://pastebin.com/raw/hCunLrQr

**Comment by lucko** [comment] 2020-04-05 16:25
Seems to be a duplicate of #2107 - see: https://github.com/lucko/LuckPerms/issues/2107#issuecomment-609433613

**Closed by lucko** 2020-04-05 16:25 UTC
