### ISSUE TITLE
Autoin support

### ISSUE THREAD

**Issue by ChoonJa** [lucko/LuckPerms#496] opened 2017-10-08 08:03 UTC
My server is offline server, and i use autoin: https://www.spigotmc.org/resources/auto-in.578/
i have problem.
Crack players can not join server.
[LuckPerms] [WARN] User doesn't have data pre-loaded. - denying login.
I get this message.
What should I do?

**Comment by lucko** [comment] 2017-10-08 08:51
Can you set `debug-logins: true` in the LuckPerms config file, then ask a cracked user to login, and send me the log output.

**Comment by ChoonJa** [comment] 2017-10-08 08:57
[17:56:31 INFO]: [AutoIn] CRACKED Player: ChoonJaJa (4fb6b9f9-3274-3b3a-879a-03e18fa4a479) [/192.168.35.1] connected to the server.
[17:56:31 INFO]: [LP] Processing login for 4fb6b9f9-3274-3b3a-879a-03e18fa4a479 - ChoonJaJa
[17:56:31 INFO]: [LuckPerms] [WARN] User 4fb6b9f9-3274-3b3a-879a-03e18fa4a479 - ChoonJaJa doesn't have data pre-loaded. - denying login.
[17:56:31 INFO]: Disconnecting com.mojang.authlib.GameProfile@7790d68b[id=4fb6b9f9-3274-3b3a-879a-03e18fa4a479,name=ChoonJaJa,properties={},legacy=false] (/192.168.35.1:36474): §7§l[§b§lL§3§lP§7§l] §cPermissions data could not be loaded. Please try again later.
[17:56:31 INFO]: com.mojang.authlib.GameProfile@7790d68b[id=4fb6b9f9-3274-3b3a-879a-03e18fa4a479,name=ChoonJaJa,properties={},legacy=false] (/192.168.35.1:36474) lost connection: §7§l[§b§lL§3§lP§7§l] §cPermissions data could not be loaded. Please try again later.

I set debug-logins: true, Still can not connect.

**Comment by lucko** [comment] 2017-10-08 09:04
Which LuckPerms version are you using?

**Comment by lucko** [comment] 2017-10-08 09:06
When you enable that option, you should see two additional messages in console for each login.

One saying:
```
Processing pre-login for <uuid> - <username>
```

then another for:
```
Processing login for <uuid> - <username>
```

**Comment by ChoonJa** [comment] 2017-10-08 09:17
LuckPerms-Bukkit-3.4.20

One saying:
[LuckPerms] [WARN] User 4fb6b9f9-3274-3b3a-879a-03e18fa4a479 - ChoonJaJa doesn't have data pre-loaded. - denying login.

then another for:
[LP] Processing login for 4fb6b9f9-3274-3b3a-879a-03e18fa4a479 - ChoonJaJa

**Comment by lucko** [comment] 2017-10-08 09:27
Can you pastebin your config?

**Comment by ChoonJa** [comment] 2017-10-09 07:28
https://pastebin.com/CKmxBU9P
here.

**Comment by mikroskeem** [comment] 2017-10-09 15:32
Why are you using Auto-In? Author has deprecated it and suggested to use [FastLogin](https://github.com/games647/FastLogin) instead.

**Comment by lucko** [comment] 2017-10-09 15:37
What server version @ChoonJa?

According to the information you'ver provided so far, the `AsyncPlayerPreLoginEvent` isn't being called for cracked users, which is very strange behaviour, which is bound to break plugins.

**Comment by ChoonJa** [comment] 2017-10-09 15:49
git-Spigot-72c2605-251a5b6 (MC: 1.10.2)
1.10.2-R0.1-SNAPSHOT

**Comment by DoNotSpamPls** [comment] 2017-10-10 09:12
Why did you close the issue? Have you fixed it? if so, tell us, so users with the same problem can find a solution 😃

**Comment by ChoonJa** [comment] 2017-10-12 10:18
Why is there no response?
Can not AutoIn support?

**Comment by mikroskeem** [comment] 2017-10-12 10:58
@ChoonJa See my response. Nobody really knows how Auto-In works (as plugin is closed source and obfuscated) and adding special support for it (or obsolete plugins at all) is not good for future of plugin.

Even though it cannot be an issue with LuckPerms itself, your problem very likely boils down to misconfiguration of Auto-in.

**Comment by DoNotSpamPls** [comment] 2017-10-12 17:21
Another note on @mikroskeem's comment, you should probably switch to FastLogin, instead of AutoIn. The latter one is closed-source and has been abandoned for a long time now.

**Comment by mat41997** [comment] 2017-10-13 02:14
auto-in project isn't not be support
https://www.spigotmc.org/resources/auto-in.578/
![2017-10-13 04_12_45-auto-in _ spigotmc - high performance minecraft](https://user-images.githubusercontent.com/5884000/31527378-0721b656-afcd-11e7-8d7a-28e7066ae645.png)

**Closed** 2017-10-14 21:57 UTC

**Comment by lucko** [comment] 2017-10-14 22:00
The issue here is almost certainly caused by AutoIn, and not an LP bug.
You should endeavour to contact its author to report the issue - there's nothing more I can really do to help.

As has been pointed out, it seems AutoIn is no longer supported anyways.
