### ISSUE TITLE
Warning message on fresh server...

### ISSUE THREAD

**Issue by roracle** [lucko/LuckPerms#2242] opened 2020-04-29 16:17 UTC
LuckPerms 5.0.72
Paper 227 (also occurs with Spigot 1.15.2-R0.1-SNAPSHOT)
The following happens when starting a fresh new server using Spigot or Paper.  I've never seen this in previous servers I've done, so this encounter is very new:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by me.lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader (file:/home/roracle/Spigot/paper/plugins/LuckPerms-Bukkit-5.0.72.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of me.lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by OmegaWeaponDev** [comment] 2020-05-01 23:36
You can ignore that error. It won't cause any issues.

**Comment by lucko** [comment] 2020-05-02 22:58
Duplicate of #952

**Closed by lucko** 2020-05-02 22:58 UTC
