### ISSUE TITLE
Conflict with Towny Perms

### ISSUE THREAD

**Issue by LuisGVE** [lucko/LuckPerms#1342] opened 2018-12-21 02:40 UTC
LuckPerms causes that the Towny permissions do not work sometimes, this only happens if LuckPerms is installed. This is what the author of Towny says: https://github.com/TownyAdvanced/Towny/issues/3123

**Comment by lucko** [comment] 2018-12-21 16:50
Please don't open duplicate issues.

duplicate of #1330

**Comment by lucko** [comment] 2018-12-21 16:52
Duplicate of #1330

**Closed** 2018-12-21 16:52 UTC
Labels: type: question
