### ISSUE TITLE
Allow listing of permissions with specific context

### ISSUE THREAD

**Issue by Andre601** [lucko/LuckPerms#1792] opened 2019-10-21 11:03 UTC
The [`/lp user|group <user|group> permission info`](https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Permission#lp-usergroup-usergroup-permission-info) command currently doesn't have an option to only list permissions, that have a specific context set (e.g. server context).

That's why I suggest adding an optional context argument to the command, to filter the permissions.

Examples:
```
/lp group default permission info server=survival
/lp group default permission info world=world_the_end
```

**Comment by lucko** [comment] 2019-12-02 15:51
Duplicate of #819

**Closed by lucko** 2019-12-02 15:51 UTC
Labels: type: suggestion
