### ISSUE TITLE
LuckPerms Console Error and Parse error

### ISSUE THREAD

**Issue by omgitsAngus** [lucko/LuckPerms#1565] opened 2019-06-07 12:23 UTC
Hi there!

I believe I am having a few issues with the plugin, whether they are related I am unsure. First off, sometimes I receive the following error in console: https://pastebin.com/Lhfjnry4.

I also have an issue with the plugin where sometimes when players rankup through a rank system through this plugin and CMI, they lose the ability to have permissions which resets their chat format to default (as it requires a permission) and they can't run any permission-based commands. They have to log out and log back in and that fixes it. I am extremely confused about this as it is fixed when re-logging in so that makes me believe it is a plugin issue. I have tried changing a few things around in CMI and contacting the dev but there has been no resolution. I am happy to provide any configuration you may need! I use yaml storage.

Thanks for any help you can provide! :)
Angus

**Comment by lucko** [comment] 2019-06-17 20:26
The error message is due to a corrupted actions logging file. You can fix this by renaming/deleting that file.

The second issue sounds like it could be caused by CMI, but I'm not sure. I'd need more info, specific reproduction steps, etc to be able to look into it more. 

Going to close this issue for now, but if you manage to get any more info about the second issue, feel free to reopen it. :)

**Closed by lucko** 2019-06-17 20:26 UTC

**Comment by omgitsAngus** [comment] 2019-06-18 08:37
Hi there, 
What is the name of the file causing the issue? I don't wanna accidentally delete it.
Unfortunately there is no way to reproduce the bug from my experience, it happens at any time at any of their ranks, it is not rank-specific, doesn't send errors to console etc. It would be CMI I would say however I thought it was possible to be LuckPerms as they don't have any of their permissions or groups until they re-log and CMI shouldn't change/effect LuckPerms perms or groups.

**Comment by lucko** [comment] 2019-07-14 09:00
Sorry for the delay in replying.

The file is called `actions.json`, it's in the storage folder.
