### ISSUE TITLE
[Sponge] Implement PAPI expansion

### ISSUE THREAD

**Issue by 02Miki** [lucko/LuckPerms#1664] opened 2019-08-08 21:36 UTC
Hello!
I'd love to get this ( https://github.com/lucko/LuckPerms/wiki/Placeholders ) for sponge as well, as sponge PAPI, doesn't have some features that are in this extension.
Thanks!

**Comment by lucko** [comment] 2019-08-19 16:58
Duplicate of #1685 1636

**Closed** 2019-08-19 16:58 UTC
