### ISSUE TITLE
Command to set prefix.

### ISSUE THREAD

**Issue by mibby** [lucko/LuckPerms#1048] opened 2018-06-12 19:00 UTC
Would it be possible to implement a command to set a prefix on a player rather than add or remove? That way players could click on a gui that switches their prefix color (with the same weight) rather than having it stack in a long list in their user file?

So when a player clicks on a new prefix color to set, it removes / overwrites all the old ones they had set.

**Comment by lucko** [comment] 2018-06-19 20:05
Kind of a duplicate of #840

This is already possible atm, just through using the removeprefix command followed by addprefix, but yes, could reduce that to only one command execution.

Closing in favour of the other issue

**Closed by lucko** 2018-06-19 20:05 UTC
