### ISSUE TITLE
Failed to validate connection.

### ISSUE THREAD

**Issue by LucidusMC** [lucko/LuckPerms#1444] opened 2019-02-28 16:26 UTC
Paper: 1.13.2
LuckPerms: 4.3.73

Console Error
https://pastebin.com/e7yJPG9q

Thanks.

**Comment by Andre601** [comment] 2019-02-28 16:43
[`28.02 06:40:20 [Server] WARN Caused by: me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.`](https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#luckperms-cannot-connect-to-my-mysql-server)

Most likely an issue with either your login cridentials being wrong or the settings in LP/MySQL not being setup properly.

Whatever it is, it not really is an issue caused by LP itself.

**Comment by LucidusMC** [comment] 2019-02-28 18:21
Well, I checked my settings, they seem good to me. So how exactly is this not a LP problem? You didn't give an explanation...

**Comment by Andre601** [comment] 2019-02-28 18:40
It doesn't need to be a fault on LPs side, since a missconfiguration on your MySQL database (for example a too short lifetime for connections) can cause that too.

And the error clearly states, that LP tries to connect on an already closed connection, which means that either the setting in the config of LP or the one in MySQL is set wrong.
I already linked the page about common errors in storage systems and yours could be one of 2 listed errors.

**Comment by LucidusMC** [comment] 2019-02-28 19:48
Ok, wasn't saying it "had" to be LP's fault, I just needed a better explanation, thank you, I will speak with my host.

**Comment by LucidusMC** [comment] 2019-03-01 17:33
Ok, it was literally because I was missing :3306 on the address, the config file states that can be omitted, this description needs to be updated based on my experience.

**Comment by lucko** [comment] 2019-03-03 12:03
May be fixed by 2cf919a17a72d3cdfaf0880275a767a3808e9523

Are those errors showing on startup, or just periodically whilst the server is running?

**Comment by LucidusMC** [comment] 2019-03-03 16:29
While server is running, I have increased max connections and idle connections, no errors yet, will report back.

**Comment by LucidusMC** [comment] 2019-03-04 02:58
I had set vault-unsafe-lookups: false (I didn't really want to, but it was the recommendation of all the errors by LuckPerms spit out below.  I did some more reading about those errors and it seems the LuckPerms devs all agree it is the cause of other plugins.  This likely caused the errors I was getting above.  Can you help me to know who I should be contacting?  WorldGuard? Citizens? So many different plugins are listed below I'm not sure which ones I should be approaching. Thanks!

https://pastebin.com/zXD2ifMx

**Comment by LucidusMC** [comment] 2019-03-05 15:14
Worldguard seems to be the culprit, removing it solves all my console Error spam.  I will pursue that path for now. Thanks.

**Comment by lucko** [comment] 2019-03-08 18:35
Citizens / WorldGuard yes.

The latest set of warning messages aren't related to the first ones. :)

**Closed** 2019-03-08 18:35 UTC
Labels: type: issue
