### ISSUE TITLE
Illegal reflective access Warning

### ISSUE THREAD

**Issue by KleinCrafter** [lucko/LuckPerms#1966] opened 2020-02-01 10:38 UTC
**Used Versions**
Paper-87
LuckPerms 5.0.70

> WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by me.lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader (file:/home/mcserver/25599/share/plugins/LuckPerms-Bukkit-5.0.70.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of me.lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Warning shows only in Console not in Log...

**Comment by Andre601** [comment] 2020-02-01 10:41
Duplicate of #952

**Closed** 2020-02-01 13:09 UTC
Labels: type: question
