### ISSUE TITLE
issue / request

### ISSUE THREAD

**Issue by Zekrin** [lucko/LuckPerms#2371] opened 2020-06-12 08:29 UTC
is there any way to take away the duration of a permission that was granted via settemp?
Example: lp user {player} permission settemp node 90d accumulate
What if I wanted to take 30 days?
Currently it is not possible because settemp takes negatives as positives and it is not possible to subtract the duration of an already placed permission.
It would be ideal for people who manage online stores as it would protect us in case of refunds/cashbacks

**Comment by l1ttleO** [comment] 2020-06-12 09:48
`/lp user <username> permission unsettemp <node>`

**Comment by Laarryy** [comment] 2020-06-12 09:49
The request is to be able to remove a variable amount of time from an existing temp node, not simply remove it.

**Comment by lucko** [comment] 2020-06-20 17:45
Duplicate of #1384 - I'll try work on adding this soon. :)

**Closed by lucko** 2020-06-20 17:45 UTC
