### ISSUE TITLE
PEX Migration doesn't set Prefix / Suffix correctly

### ISSUE THREAD

**Issue by HeroCC** [lucko/LuckPerms#93] opened 2016-12-19 01:43 UTC
Hello again!

It looks like if you set a prefix or suffix (with `/pex group GROUPNAME suffix SUPERCOOLPREFIX`), it isn't imported correctly, instead interpreting it as a permission (ex. `suffix.0.&f` is set if the PEX suffix is "&f").

**Comment by lucko** [comment] 2016-12-20 12:58
Duplicate of #63. Will look into it soon.

**Closed by lucko** 2016-12-20 12:58 UTC
