### ISSUE TITLE
Luckperms not loading on Thermos

### ISSUE THREAD

**Issue by merjilin** [lucko/LuckPerms#293] opened 2017-05-22 16:16 UTC
Hey, luck! I'm encountering some issues loading luckperms with the newest installation of thermos. I'm not too sure if it is intended to load with thermos anyway, but there isn't any harm in asking! 
Here is the error I am receiving: 
https://gist.github.com/merjilin/3329cdf1edd2a62712ab2939ce4f63c3
and here is my FML log: 
https://gist.github.com/merjilin/df307794a97ee903b99977dd137c9d2c

Thank you for your time - merjilin

**Comment by lucko** [comment] 2017-05-22 16:30
This is a Thermos bug.

Duplicate of:
CyberdyneCC/Thermos#498 #193 #167 #157 #153

**Closed by lucko** 2017-05-22 16:30 UTC
