### ISSUE TITLE
Promoting a player along track sometimes breaks permission

### ISSUE THREAD

**Issue by hihihih565** [lucko/LuckPerms#1697] opened 2019-08-20 19:54 UTC
When promoting a player across a track, sometimes it causes the player's permissions to break making them unable to do anything, relogging or running /lp user {player} info will fix the player's permission, currently storing players permission info via mysql.

**Comment by Andre601** [comment] 2019-08-20 19:56
This is a duplicate of #1696 

Please comment on that issue before making your own one thanks.

**Comment by lucko** [comment] 2019-09-06 17:49
duplicate of #1696

**Closed by lucko** 2019-09-06 17:49 UTC
