### ISSUE TITLE
Java 11.0.1

### ISSUE THREAD

**Issue by andrewkm** [lucko/LuckPerms#1300] opened 2018-11-15 19:46 UTC
Hey Luck, testing Java 11 and it seems this plugin is the only one shooting an error for me.
Can't even see it in the logs, seems to be a client side thing on the local machine:
https://i.imgur.com/Rf461Qz.png

This is me loading up the server on my test box, all other plugins work fine (over 40), just luck perms being weird for some reason.

Previously was using Java 8

**Comment by md678685** [comment] 2018-11-15 19:53
Pretty much an exact duplicate of #1290.

**Closed** 2018-11-15 20:02 UTC
