### ISSUE TITLE
[API] Default group not getting removed after

### ISSUE THREAD

**Issue by marlester-dev** [lucko/LuckPerms#3664] opened 2023-06-05 18:43 UTC
### Description

If I do like this:
```
user.data().clear();
luckPerms.getUserManager().saveUser(user);
luckPerms.getUserManager().cleanupUser(user);
```
User still remains visible in the lp editor's database with group.default, happens only if user had group that inherits default group.
![lp](https://github.com/LuckPerms/LuckPerms/assets/77095872/85f64b29-0d0b-430f-ac96-fee76c3e53c2)
I want to delete the user completely. (user is "offline")

### Reproduction Steps

1. Give the user 'vip' group (group that inherits default group).
2. Using api execute this code (you need to get the offline user and luckPerms):
user.data().clear();
luckPerms.getUserManager().saveUser(user);
luckPerms.getUserManager().cleanupUser(user);
3. open the lp editor, you should see something like this:
![lp](https://github.com/LuckPerms/LuckPerms/assets/77095872/764e7b34-e6b6-44b0-8a6c-8dc75e2b51f7)

### Expected Behaviour

User gets completely wiped out, deleted.

### Server Details

git-Purpur-1964 (MC: 1.19.4)*

### LuckPerms Version

'net.luckperms:api:5.4' (gradle), 5.4.71 on server

### Logs and Configs

No logs.

### Extra Details

I want to completely delete and wipe out the user, but with those who have group that inherits default group, it does not work and they still have default group in result and I can't delete it then. I need to delete the user completely, otherwise lp editor users will get trashed up by random users.

**Comment by Turbotailz** [comment] 2023-06-05 21:10
Duplicate of #3663

**Closed as completed** 2023-06-19 14:29 UTC
Labels: type: issue
