### ISSUE TITLE
RLCraft + Nucleus + LuckPerms

### ISSUE THREAD

**Issue by Voxdnb** [lucko/LuckPerms#2123] opened 2020-03-30 21:31 UTC
Hi Luck. I raised an issue with Nucleus about an issue I'm having with my RLCraft server. Upon speaking to dualspiral, he informed me that it's more of a LuckPerms issue. https://gist.github.com/Voxdnb/0952f96bee5a5d78d43988444afb694c -- This is the logs from the server. dualspiral mentioned it could be something deep in LP code causing the issue.

Description of the problem: LuckPerms works fine until I add Nucleus. Then, when I try to send a message, my name completely disappears.

**Comment by lucko** [comment] 2020-03-30 21:49
Could you link me to the issue or chat log you had with dualspiral? I trust his judgement, but what you've said so far doesn't lead me to believe the bug you're experiencing is caused by LuckPerms.

Could you also clarify: when you say your name disappears, I assume you mean your username in the chat?

LuckPerms doesn't do any chat formatting itself, it merely provides "option" data (prefixes, suffixes, etc) when other plugins request it.

**Comment by Voxdnb** [comment] 2020-03-30 21:55
Hi Luck, it was actually in the LuckPerms discord in #General-2. An image of chat log and more discussion is there.

**Comment by lucko** [comment] 2020-03-30 21:58
Nevermind, I went to the Nucleus discord and found your conversation myself - would've been helpful if you'd included the error you got here too! (https://pastebin.com/RZgawj1P)

Should be fixed in the above commit.

**Closed** 2020-03-30 21:58 UTC
Labels: status: need more info, type: question

**Comment by Voxdnb** [comment] 2020-03-30 22:00
Hi, wanted to know - what do I do with the comment above?

**Comment by lucko** [comment] 2020-03-30 22:03
Apologies, I hadn't seen your conversation in the LP discord before responding to this ticket. 

All you need to do is update to LuckPerms 5.0.114 or newer.
