### ISSUE TITLE
Error when starting latest bedrock edition

### ISSUE THREAD

**Issue by austindkelly** [lucko/LuckPerms#2292] opened 2020-05-13 06:41 UTC
I just installed the latest https://ci.nukkitx.com/job/NukkitX/job/Nukkit/job/master/686/ of nukkit and tried the latest of luckperms 5.1.15 and got the following error:

> 2020-05-13 06:36:14.694 [main] INFO  - Loading §anukkit.yml§f ...
2020-05-13 06:36:14.798 [main] INFO  - Loading §aserver.properties§f ...
2020-05-13 06:36:14.811 [main] INFO  - Selected English (eng) as the base language
2020-05-13 06:36:14.812 [main] INFO  - Starting Minecraft: BE server version §bv1.14.60§r
2020-05-13 06:36:14.820 [main] INFO  - Selected Zlib Provider: 2 (cn.nukkit.utils.ZlibThreadLocal)
2020-05-13 06:36:14.864 [main] INFO  - Opening server on 0.0.0.0:19132
2020-05-13 06:36:14.880 [main] INFO  - This server is running Nukkit version §egit-f8e9e30§f "§b§f" (API 1.0.9)
2020-05-13 06:36:14.881 [main] INFO  - Nukkit is distributed under the LGPL License
2020-05-13 06:36:15.533 [main] INFO  - Loading recipes...
2020-05-13 06:36:15.683 [main] INFO  - Loaded 1320 recipes.
2020-05-13 06:36:15.686 [main] INFO  - Successfully loaded 0 resource packs
2020-05-13 06:36:15.702 [main] INFO  - Loading LuckPerms v5.1.15
2020-05-13 06:36:15.800 [RakNet Thread #15] INFO  - Epoll Status is true
2020-05-13 06:36:15.839 [main] INFO  - Enabling LuckPerms v5.1.15
2020-05-13 06:36:15.882 [main] INFO  - §b       §3 __
2020-05-13 06:36:15.894 [main] INFO  - §b  |    §3|__)   §2LuckPerms §bv5.1.15
2020-05-13 06:36:15.895 [main] INFO  - §b  |___ §3|      §8Running on Nukkit - Nukkit
2020-05-13 06:36:15.895 [main] INFO  - 
2020-05-13 06:36:15.910 [main] INFO  - [LuckPerms] Loading configuration...
2020-05-13 06:36:16.235 [main] INFO  - [LuckPerms] Loading storage provider... [H2]
2020-05-13 06:36:16.948 [main] INFO  - [LuckPerms] Loading internal permission managers...
2020-05-13 06:36:16.969 [main] ERROR - Throwing
java.lang.RuntimeException: java.lang.ExceptionInInitializerError
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:443) [nukkit.jar:?]
	at cn.nukkit.Server.enablePlugin(Server.java:741) [nukkit.jar:?]
	at cn.nukkit.Server.enablePlugins(Server.java:730) [nukkit.jar:?]
	at cn.nukkit.Server.<init>(Server.java:491) [nukkit.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at me.lucko.luckperms.nukkit.inject.permissible.MonitoredPermissibleBase.<init>(MonitoredPermissibleBase.java:62) ~[?:?]
	at me.lucko.luckperms.nukkit.inject.permissible.PermissibleMonitoringInjector.transform(PermissibleMonitoringInjector.java:82) ~[?:?]
	at me.lucko.luckperms.nukkit.inject.permissible.PermissibleMonitoringInjector.injectConsole(PermissibleMonitoringInjector.java:96) ~[?:?]
	at me.lucko.luckperms.nukkit.inject.permissible.PermissibleMonitoringInjector.run(PermissibleMonitoringInjector.java:57) ~[?:?]
	at me.lucko.luckperms.nukkit.LPNukkitPlugin.setupPlatformHooks(LPNukkitPlugin.java:162) ~[?:?]
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:171) ~[?:?]
	at me.lucko.luckperms.nukkit.LPNukkitBootstrap.onEnable(LPNukkitBootstrap.java:125) ~[?:?]
	at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[nukkit.jar:?]
	at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[nukkit.jar:?]
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439) ~[nukkit.jar:?]
	... 4 more
Caused by: java.lang.IllegalArgumentException: Can not set final java.util.Set field cn.nukkit.permission.PermissibleBase.attachments to me.lucko.luckperms.common.util.EmptyCollections$EmptyList
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:1.8.0_252]
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:1.8.0_252]
	at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:83) ~[?:1.8.0_252]
	at java.lang.reflect.Field.set(Field.java:764) ~[?:1.8.0_252]
	at me.lucko.luckperms.nukkit.inject.permissible.DummyPermissibleBase.<init>(DummyPermissibleBase.java:71) ~[?:?]
	at me.lucko.luckperms.nukkit.inject.permissible.DummyPermissibleBase.<clinit>(DummyPermissibleBase.java:65) ~[?:?]
	at me.lucko.luckperms.nukkit.inject.permissible.MonitoredPermissibleBase.<init>(MonitoredPermissibleBase.java:62) ~[?:?]
	at me.lucko.luckperms.nukkit.inject.permissible.PermissibleMonitoringInjector.transform(PermissibleMonitoringInjector.java:82) ~[?:?]
	at me.lucko.luckperms.nukkit.inject.permissible.PermissibleMonitoringInjector.injectConsole(PermissibleMonitoringInjector.java:96) ~[?:?]
	at me.lucko.luckperms.nukkit.inject.permissible.PermissibleMonitoringInjector.run(PermissibleMonitoringInjector.java:57) ~[?:?]
	at me.lucko.luckperms.nukkit.LPNukkitPlugin.setupPlatformHooks(LPNukkitPlugin.java:162) ~[?:?]
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:171) ~[?:?]
	at me.lucko.luckperms.nukkit.LPNukkitBootstrap.onEnable(LPNukkitBootstrap.java:125) ~[?:?]
	at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[nukkit.jar:?]
	at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[nukkit.jar:?]
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439) ~[nukkit.jar:?]
	... 4 more
2020-05-13 06:36:16.975 [main] INFO  - Disabling LuckPerms v5.1.15
2020-05-13 06:36:16.976 [main] INFO  - [LuckPerms] Starting shutdown process...
2020-05-13 06:36:16.978 [main] ERROR - Throwing
java.lang.NullPointerException: null
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.disable(AbstractLuckPermsPlugin.java:218) ~[?:?]
	at me.lucko.luckperms.nukkit.LPNukkitBootstrap.onDisable(LPNukkitBootstrap.java:133) ~[?:?]
	at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:91) ~[nukkit.jar:?]
	at cn.nukkit.plugin.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:132) ~[nukkit.jar:?]
	at cn.nukkit.plugin.PluginManager.disablePlugin(PluginManager.java:513) [nukkit.jar:?]
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:445) [nukkit.jar:?]
	at cn.nukkit.Server.enablePlugin(Server.java:741) [nukkit.jar:?]
	at cn.nukkit.Server.enablePlugins(Server.java:730) [nukkit.jar:?]
	at cn.nukkit.Server.<init>(Server.java:491) [nukkit.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit.jar:?]
2020-05-13 06:36:17.017 [main] INFO  - Preparing level "§asurvive§f"
2020-05-13 06:36:17.078 [main] INFO  - Preparing level "§anether§f"
2020-05-13 06:36:17.126 [main] INFO  - Starting GS4 status listener
2020-05-13 06:36:17.126 [main] INFO  - Setting query port to 19132
2020-05-13 06:36:17.127 [main] INFO  - Query is running on 0.0.0.0:19132
2020-05-13 06:36:17.127 [main] INFO  - Default game type: Survival Mode
2020-05-13 06:36:17.128 [main] INFO  - Done (2.474s)! For help, type "help" or "?"

**Comment by austindkelly** [comment] 2020-05-13 06:55
I was able to get it working with https://ci.lucko.me/view/LuckPerms/job/LuckPerms/1082/

**Comment by lucko** [comment] 2020-05-16 17:13
Duplicate of #2290 - this is fixed now in the latest builds :)

**Closed by lucko** 2020-05-16 17:13 UTC
