### ISSUE TITLE
Performance issues with LP

### ISSUE THREAD

**Issue by bloodmc** [lucko/LuckPerms#86] opened 2016-12-14 22:17 UTC
https://timings.aikar.co/v2/?id=8f017635ea9f4627ae4717a4c521d2b3&start=1481752687&end=1481752909&section=lag

[-]luckperms::userGetPermissionValuecount(4) total(12.43% 2.456s, 7.32% of tick)  avg(613.88ms per - 3.66ms/0.01 per tick)

[-]luckperms::userGetPermissionValuecount(54) total(4.25% 0.84s, 2.50% of tick)  avg(15.55ms per - 1.25ms/0.08 per tick)

[-]luckperms::groupGetParentscount(2818) total(30.48% 3.451s, 164.34% of tick)  avg(1.22ms per - 82.17ms/67.10 per tick)

Any idea what is causing these slowdowns?

**Comment by Slind14** [comment] 2016-12-14 22:22
Those were caused by an accidental loop in the inheriting process. This only affected the Sponge Environment with LuckPerms 2.16.25. The Bukkit environment was unaffected.

While inherit loops are the users fault I see another issue at hand:

Group Manager
inherits: admin
inherits: perms_admin

Group Admin:
inherits: jradmin
inherits: perms_admin

Group Jr Admin
inherits: perms_admin

If the list goes on, this creates quite some unnecessary overhead.

**Comment by lucko** [comment] 2016-12-14 22:29
Duplicate of #69

**Closed by lucko** 2016-12-14 22:29 UTC
