### ISSUE TITLE
PlaceHolders

### ISSUE THREAD

**Issue by Tomi010817** [lucko/LuckPerms#1214] opened 2018-09-12 00:38 UTC
I want to type "[%vault_rank%] &7"  on the prefix of group "user" but I just discovered that it doesn't load the placeholder, this is a problem of the plugin because I have already downloaded the placeholders of "Vault" and What I wanted to do is to make a Rankup system so when a player says something on the chat, he may be able to see his rank (I use LuckPerms for vip,mod,admin ranks and PermissionsEx for the Rankup ranks). Everything is done correctly but the problem is that LuckPerms doesn't read the placeholders when they are on the prefix or suffix. 
PD: I'm new to this permission plugin, so I don't know if there is an alternative for putting placeholders on the chat format of the player. 

Thanks for reading. Any help is really appreciated

**Comment by Andre601** [comment] 2018-09-12 00:49
Do **never** run two seperate permission-plugins at the time!
Either run LuckPerms or PermissionsEx, or something **will** break.

Also the thing with the placeholder is not a LP-related issue.
Why should `%vault_rank%` work in a prefix of a permission-plugin, that also uses Vault (There could be one issue with having two perm-plugins)?

LP does **not** format the chat in any way! It only provides groups and the prefixes wich can be used through Vault and - you guessed it - the placeholder `%vault_rank%`

**Comment by Tomi010817** [comment] 2018-09-12 01:10
Thanks for the quick reply. Nothing has broken since I use PermissionsEx and Luckperms together, and I saw big networks that use them both for the same reason as me, so if the issue that I told before isn't fixable, what should I do then to show the PermissionsEx rank on the chat format? Is there any way of doing that? because I'm 100% sure that there is.
I tried using EssentialsChat using {GROUP} but it detects the group of LuckPerms, so then I tried to put more weight to the ranks of permissionsEx, but still the same.

**Comment by Andre601** [comment] 2018-09-12 01:41
Ok. I'll answer as good as possible...

> Nothing has broken since I use PermissionsEx and Luckperms together, and I saw big networks that use them both for the same reason as me,

That is either a lie from you, or from those guys...
I no way can you just run two permission-plugins at the same time. They WILL conflict at some time. And in the case of Vault can it also cause other issues.

> what should I do then to show the PermissionsEx rank on the chat format? Is there any way of doing that? because I'm 100% sure that there is.

See? That's one of the issues on having two perm-plugins on the same server at the same time. It will create conflicts.

> I tried using EssentialsChat using {GROUP} but it detects the group of LuckPerms, so then I tried to put more weight to the ranks of permissionsEx, but still the same.

No more explanation needed...
And you really say, that there aren't any issues?

**Comment by Imortalshard** [comment] 2018-09-12 01:51
Having two permissions plugins on one server at a time (Unless for the exception of Luckperms Migration) will always cause issues. There is no if, maybe, or buts about it because of the way they work.

The reason for the placeholders having the current issues is because PEX and Luckperms are conflicting about which plugin should use the placeholder, so the EssentialsChat will not know which plugin to use so it will just ignore the placeholder. 

This is the same as trying to run Spigot and Sponge along side of eachother on a single server. It will not work because of many conflicts and issues. 

We are unable to help you because the issue is purely on having two permission plugins. Remove one of them (Preferably PermissionsEX as it is outdated and no longer supported).

Just because you "saw" big networks doing it doesn't mean you have to either. They will have issues with this as well and most likely have had to either revert to using just one or they have some weird setup that allows them to bypass all the conflicts. 

It is strongly recommended that you remove one of the permissions plugins and just stick to the one. Once you do this, all the "issues" you're facing will be fixed.

**Comment by darbyjack** [comment] 2018-09-12 01:54
This issue has been closed. I ate all my popcorn reading this.

**Comment by Tomi010817** [comment] 2018-09-12 02:07
ImortalShard. you are right, they have a really weird setup because what they do, is to use luckperms for bungeecord so in the sub servers they use permissionsex, and in that case, essentialschat will take the rank of permissionsex instead of the rank of luckperms placed on the proxy of the bungeecord. This is the way that they have probably made it. So in essentialsChat they type the chat format to be "{GROUP} {USERNAME}" and the essentialschat will take the rank of permissionsex as how it is the unique permissions plugin situated on that sub server, and LuckPerms will replace the {USERNAME} with the playername and the prefix that in this case it will be the vip rank. Thanks for answering.
PD: I know that two permissions plugin can have conflict, but in this case, the ranks made for rankup on permissionsex would only have just 1 permissions each one, so there might not be that ton of issues

**Comment by Andre601** [comment] 2018-09-12 02:13
> ImortalShard. you are right, they have a really weird setup because what they do, is to use luckperms for bungeecord so in the sub servers they use permissionsex, and in that case, essentialschat will take the rank of permissionsex instead of the rank of luckperms placed on the proxy of the bungeecord.

That means they use LP for BungeeCord-perms and PEX for normal spigot perms.
BungeeCord plugins and Spigot plugins don't interact with each other, unless they have some sort of connection (bridge).

> PD: I know that two permissions plugin can have conflict, but in this case, the ranks made for rankup on permissionsex would only have just 1 permissions each one, so there might not be that ton of issues

Nope. Even that can and will break stuff.
It's not only about how many perms a group/perm-plugin has... If both use Vault, then at least that is fucked.

**Comment by Tomi010817** [comment] 2018-09-12 02:41
Thanks Andre, I really consider your advice Inmortalshard, It's a bad fault to be digging a big whole just to solve that tiny problem, I could easily put a prefix for the donor ranks and suffix for the rankup ranks and not meassure off everything. 
And what you said on the last part its not right, because in that case the ranks of permissionsex wouldn't have prefix or suffix

**Comment by codingJWilliams** [comment] 2018-09-12 06:50
What do you mean what he's said isn't right? Having two permissions plugins **does not work.** If you hop over to our discord @  https://discord.gg/W3FzxHA I'll happily assist you in setting up luckperms to do exactly what you think you need permissionsEx for, because whatever it is I guarantee there's a way with luckperms, and it'll solve all your current issues with conflicting plugins. If you wish to continue using permissionsEx alongside luckperms this is definitely not supported; this ticket is definitely a PEBKAC issue otherwise.

The networks that use both have a slightly strange, but valid setup as for all any spigot plugin cares LuckPerms-Bungee might as well not exist, as it connects with it in no way. The way you've described their networks sounds like **in the spigot plugin folder** they have permissionsex only whereas you have both luckperms and pex, so your setup isn't the same as this 'large network that works'.

If you aren't going to seek assistance converting to use only one permissions plugin, then I'm afraid I'm going to have to ask you to close the ticket, or get luck to close it for us.

**Comment by BrainStone** [comment] 2018-09-12 12:10
Just so you know. LP disables all its permissions managing capabilities when it detects PEX. It does that to allow migration. If it didn’t do that your server would throw exceptions and no permissions would be working or your server would crash straight away.

And as many have pointed out the only way to have LP and PEX coexist is by having them on different servers.

I don’t understand why you can’t seem to grasp these simple concepts. 

And yet again. There’s not a single thing you can do with PEX, you can’t do with LP. Only exceptions are plugins that only use the PEX-API instead of the Vault-API. In other words terrible plugins.

**Comment by lucko** [comment] 2018-09-12 12:50
You should only use one permission plugin at a time. That's most likely what's causing your issue. :)

**Closed by lucko** 2018-09-12 12:50 UTC
