### ISSUE TITLE
Permissions data load error

### ISSUE THREAD

**Issue by RikoDEV** [lucko/LuckPerms#110] opened 2016-12-29 14:35 UTC
I noticed that when we turn on the whitelist and a player not added to the list attempts to connect to the server console receive this error:

`[15:28:57 INFO]: Disconnecting com.mojang.authlib.GameProfile@13d18540[id=e76f9ae4-5295-3286-85d2-8e16341cd0fb,name=NeonDmn,properties={textures=[com.mojang.authlib.properties.Property@5c64dbe7]},legacy=false] (/37.47.107.145:38792): ?7?l[?b?lL?3?lP?7?l] ?cPermissions data could not be loaded. Please contact an administrator.`

**Comment by lucko** [comment] 2017-01-04 18:44
Will look into it. I've noticed the same thing.

**Comment by lucko** [comment] 2017-01-05 19:16
```
[19:14:12 INFO]: UUID of player Lucko is 7edb3771-6862-318f-9565-df5b318cf080
[19:14:12 INFO]: Disconnecting com.mojang.authlib.GameProfile@f1851bf[id=7edb3771-6862-318f-9565-df5b318cf080,name=Lucko,properties={},legacy=false] (/127.0.0.1:64855): You are not whitelisted on this server!
[19:14:12 INFO]: com.mojang.authlib.GameProfile@f1851bf[id=7edb3771-6862-318f-9565-df5b318cf080,name=Lucko,properties={},legacy=false] (/127.0.0.1:64855) lost connection: You are not whitelisted on this server!
```

Huh, weird. I can't reproduce now...

**Comment by VankkaGithub** [comment] 2017-01-09 16:09
I have experienced the same with bukkit legacy

This issue is useally caused by not being able to connect to database because of malformed config or simply no access or wrong assword

```
[18:04:09] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v2.16.83
[18:04:09] [Server thread/INFO]: [LuckPerms] Loading configuration...
[18:04:10] [Server thread/INFO]: [LuckPerms] Detecting storage method...
[18:04:10] [Server thread/INFO]: [LuckPerms] Loading dependencies...
[18:04:10] [Server thread/INFO]: [LuckPerms] Identified the following dependencies: [MYSQL_DRIVER, SLF4J_API, SLF4J_SIMPLE, HIKARI]
[18:04:10] [Server thread/INFO]: [LuckPerms] Dependency 'mysql_driver-5.1.6.jar' could not be found. Attempting to download.
[18:04:10] [Server thread/INFO]: [LuckPerms] Dependency 'mysql_driver-5.1.6.jar' successfully downloaded.
[18:04:10] [Server thread/INFO]: [LuckPerms] Dependency 'slf4j_api-1.7.9.jar' could not be found. Attempting to download.
[18:04:10] [Server thread/INFO]: [LuckPerms] Dependency 'slf4j_api-1.7.9.jar' successfully downloaded.
[18:04:10] [Server thread/INFO]: [LuckPerms] Dependency 'slf4j_simple-1.7.9.jar' could not be found. Attempting to download.
[18:04:10] [Server thread/INFO]: [LuckPerms] Dependency 'slf4j_simple-1.7.9.jar' successfully downloaded.
[18:04:10] [Server thread/INFO]: [LuckPerms] Dependency 'hikari-2.5.1.jar' could not be found. Attempting to download.
[18:04:11] [Server thread/INFO]: [LuckPerms] Dependency 'hikari-2.5.1.jar' successfully downloaded.
[18:04:11] [Server thread/ERROR]: [LuckPerms] Failed to load jar for dependency HIKARI
[18:04:11] [Server thread/WARN]: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
[18:04:11] [Server thread/WARN]: 	at com.zaxxer.hikari.HikariConfig.<clinit>(HikariConfig.java:50)
[18:04:11] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:04:11] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[18:04:11] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[18:04:11] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[18:04:11] [Server thread/WARN]: 	at java.lang.Class.newInstance(Unknown Source)
[18:04:11] [Server thread/WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyManager.loadJar(DependencyManager.java:138)
[18:04:11] [Server thread/WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyManager.loadDependencies(DependencyManager.java:100)
[18:04:11] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.LPBukkitPlugin.onEnable(LPBukkitPlugin.java:144)
[18:04:11] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[18:04:11] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[18:04:11] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[18:04:11] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415)
[18:04:11] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349)
[18:04:11] [Server thread/WARN]: 	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462)
[18:04:11] [Server thread/WARN]: 	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:137)
[18:04:11] [Server thread/WARN]: 	at net.minecraft.world.World.<init>(World.java:360)
[18:04:11] [Server thread/WARN]: 	at net.minecraft.world.WorldServer.<init>(WorldServer.java:160)
[18:04:11] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:367)
[18:04:11] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
[18:04:11] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
[18:04:11] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[18:04:11] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
[18:04:11] [Server thread/WARN]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
[18:04:11] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[18:04:11] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[18:04:11] [Server thread/WARN]: 	... 22 more
[18:04:11] [Server thread/INFO]: [LuckPerms] Initializing storage backings...
[18:04:11] [Server thread/INFO]: [LuckPerms] Initialising storage provider...
[18:04:11] [Server thread/ERROR]: Error occurred while enabling LuckPerms v2.16.83 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class com.zaxxer.hikari.HikariConfig
	at me.lucko.luckperms.common.storage.backing.sqlprovider.MySQLProvider.init(MySQLProvider.java:45) ~[?:?]
	at me.lucko.luckperms.common.storage.backing.SQLBacking.init(SQLBacking.java:134) ~[?:?]
	at me.lucko.luckperms.common.storage.AbstractStorage.init(AbstractStorage.java:55) ~[?:?]
	at me.lucko.luckperms.common.storage.wrappings.TolerantStorage.init(TolerantStorage.java:52) ~[?:?]
	at me.lucko.luckperms.common.storage.wrappings.BufferedOutputStorage.init(BufferedOutputStorage.java:47) ~[?:?]
	at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:113) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitPlugin.onEnable(LPBukkitPlugin.java:181) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:137) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:360) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:160) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:367) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
```

**Comment by lucko** [comment] 2017-01-13 21:58
I've tried to reproduce in a number of different circumstances and have been unable to get it to break. Any ideas?

**Comment by lucko** [comment] 2017-01-15 12:22
Closing for now, since as far as I can tell, this isn't an issue anymore. Feel free to reopen if you're still experiencing the issue.

**Comment by lucko** [comment] 2017-01-19 20:04
Should be fixed :)

**Closed by lucko** 2017-01-19 20:04 UTC

**Comment by DiscoDuck151** [comment] 2017-04-09 02:23
I have the exact same problem with version 3.0.0. Help would be much appreciated.
