### ISSUE TITLE
Delayed permission changes incompatible with some plugins

### ISSUE THREAD

**Issue by Sir-Will** [lucko/LuckPerms#85] opened 2016-12-12 23:42 UTC
I have a plugin which adds a permission to the user and does react to the permission change instantly.
With zPerms this worked without any issues but LuckPerms seems to have a delay.

So, when the plugin looksup the users permissions LuckPerms returns the "old" information as it hasn't processed the permission changes. This is causing the plugin to not work at all.

**Comment by lucko** [comment] 2016-12-13 07:35
Which plugin is it?

**Comment by Sir-Will** [comment] 2016-12-14 01:36
CommandHelper, ServerSigns, ChestCommands, all this plugins where you can run multiple commands.

**Comment by lucko** [comment] 2016-12-15 17:19
Can you explain what the issue is with that?

Like, I assume they're adding permissions to users when certain actions take place? I don't understand the problem here.

**Comment by Slind14** [comment] 2016-12-16 00:12
ChestGUI display based on permissions.

1. chest gui opens with settings and their state is based on permissions
2. player clicks an item to change the permission which updates the permission and reloads the chest gui
3. chest gui still displays the option like it wasn't changed (hasPermission still reports the old state)

1. player clicks a sign which gives him a temporary permission and asks him to click again to confirm
2. he clicks again and the permission isn't live yet, hence it fails

1. on login (highest priority) a permission is being set 
2. on login (normal priority) another plugin is checking for this permission but its reporting the old state

.. the list goes on

For us this caused multiple systems to not work anymore and some of them can't be tweaked easily.

**Comment by lucko** [comment] 2016-12-16 19:11
I spoke briefly to you on Discord earlier. Just going to repeat a bit of what was said there for reference on this ticket.


The core issue is that modifications take place asynchronously. When you execute a command to modify user/group state, that change will apply *at some point* in the future. It is not guaranteed to be immediate. 

Reasons for this:

1. Modifying state takes time. It affects overall server performance if the main server thread stops and waits for these changes to be applied.
2. The changes take **even longer** in LuckPerms than they would in other plugins, due to the way I've designed it. It's not simply a case of removing a node from a Map/Set, I have to apply the changes to multiple caching layers, and replicate the change in state across all affected objects. For example, if a group changes, I have to replicate that change across all users/groups who inherit the change.

A lot of the LuckPerms design centers around pre-processing. It means that making changes to the data is time consuming, but actually reading it is very quick.

So, why not just make the change happen synchronously like other plugins?

1. Simply put, it's slow.
2. I want to modify the most up-to-date object state. This means loading data from storage (SQL queries are even slower)
3. Using this approach, "pre-processing" as I call it does far more harm than good. 

So, the solution to your problem, well, I'm not really sure.

As I said on Discord, it's an implementation detail. It's not a requirement that **all commands** that modify data state should make the change in sync with the server thread. 

In my own projects, (I write and work on multiple projects that use LuckPerms as a base for saving data about players), I simply embrace the multithreaded nature of the plugin and use callbacks. I appreciate this may not be possible when using pre-made plugins, but I really can't think of an easy way around the issue.

In reply to the individual issues above (I understand this is probably really unhelpful advice)

1 - Perhaps just refresh at a delay? Obviously you're using ChestCommands, so there's not really a simple solution. I've written similar systems using LP as a base, and have just made the inventory change whilst the permission changes go through in the background. Obviously this won't work if you're using permission state to re-build the menu. I don't really have any ideas.

2 - Not really sure with this one. But the reply is going to be the same as No. 3. If you're just wanted to set transient permissions (those that will only exist for the remainder of the session), you can just make this change through Bukkit's API. Vault has methods for it too.

I'd appreciate any other suggestions, but at this point, completely changing the system to allow for synchronised writes isn't possible. The performance benefits hugely outweigh the concurrency issues.

**Comment by Slind14** [comment] 2016-12-17 01:35
Yes, I totally agree, resolving this requires major core changes and some sacrifice of performance.

I guess the main question is, how could it be designed to be unnoticeable in terms of performance and resolve the issue.

I believe the best way would be to split the system. Into a consistent local environment while keeping the efficient backend. I'm certain it is possible for the system to perform extremely well with a local consistency when designed nicely. Frankly if the last nano second of performance is valued highly, it could be optional to turn it off and sacrifice the consistency for improved performance where necessary. 
Overall I believe that this performance impact is mainly interesting for huge servers with thousands of permission changes every second.

**Comment by Sir-Will** [comment] 2016-12-17 08:57
Would be a second command which doesn't run it async a solution? So that command can be used for special cases like this.

**Comment by lucko** [comment] 2016-12-17 09:14
Depends if you could deal with the whole server halting for x ms every time a command runs. (basically no it's not really a solution :/ )

**Closed** 2016-12-17 13:55 UTC

**Comment by Slind14** [comment] 2016-12-18 02:57
How could you make a plugin like server signs/chest gui work? It is all about commands.
