### ISSUE TITLE
Promotion and demotion

### ISSUE THREAD

**Issue by Lifeonblack** [lucko/LuckPerms#355] opened 2017-07-04 05:53 UTC
Hello so if this does not implemented yet,
what about having custom permission as you demote or promote a player forxample
luckperms.user.promote.<groupName> or luckperms.user.promote.* same as demote :)

**Comment by lucko** [comment] 2017-07-05 20:15
Duplicate of #174

**Closed by lucko** 2017-07-05 20:15 UTC
