### ISSUE TITLE
LP-Sponge: 1.12.2 4.0.87 going thru nether portal throws repeated exceptions

### ISSUE THREAD

**Issue by smmmadden** [lucko/LuckPerms#685] opened 2018-01-14 22:13 UTC
I can go thru each side of the portal, but going "into" the nether is where all the exceptions starts.  Coming back to the overworld they stop.
exceptions in latest.log: https://pastebin.com/9nCFeN8d
exceptions in fml-junk-earlystartup.log: https://pastebin.com/HREbEBcn

Environment:
 Minecraft: 1.12.2
    SpongeAPI: 7.1.0-SNAPSHOT-eebceb6
    SpongeForge: 1.12.2-2555-7.1.0-BETA-2831
    Minecraft Forge: 14.23.1.2587
    LuckPerms-Sponge-4.0.87
    GriefPrevention: 4.3.0.511
    O/S: Windows 10 Pro x64
    Java: 1.8.0_152x64
    Server: Pokecube Revival 1.12.2 - 6.14.2

**Comment by lucko** [comment] 2018-01-14 22:16
I need to see the full FML log,
This issue is most likely caused by another plugin. (GriefPrevention??)

**Comment by smmmadden** [comment] 2018-01-14 22:21
which full FML log do you need? fml-junk-earlystartup.log, fml-server-latest.log or fml-server-#.log

**Comment by smmmadden** [comment] 2018-01-14 22:23
here is fml-server-latest.log: https://pastebin.com/GVnHaB1m

**Comment by lucko** [comment] 2018-01-14 22:26
There should be stacktraces which go along with these errors:
```
[16:52:39] [Server thread/INFO]: [LuckPerms] [WARN] An exception was thrown whilst calculating the context of subject luckperms.api7.SubjectProxy(ref=luckperms.SubjectReference(collection=user, subject=f098c794-f41a-4edd-a536-b638b26b748e))
```

Those traces will show which plugin is causing the error.

**Comment by smmmadden** [comment] 2018-01-14 22:39
that's the full content of those logs

**Comment by lucko** [comment] 2018-01-14 22:40
Yeah, the full content will be in one of the other files.

**Comment by smmmadden** [comment] 2018-01-15 02:11
I've given every log that I got for the time it occurred.  Just zipped them up here in case they help.
[logs.zip](https://github.com/lucko/LuckPerms/files/1630114/logs.zip)

**Comment by smmmadden** [comment] 2018-01-15 14:02
I just retested with spongeforge-1.12.2-2555-7.1.0-BETA-2837, Forge-1.12.2-14.23.1.2589 and LP-Sponge-4.0.90 and same issue persists.  I created a new Nether Portal, walk thru and end up in Nether.  But console is spammed with the same errors until I walk back thru to the overworld and then it stops writing to the console.

**Comment by lucko** [comment] 2018-01-15 14:20
GriefPrevention issue.

```
java.lang.NullPointerException
	at me.ryanhamshire.griefprevention.claim.GPClaim.initializeClaimData(GPClaim.java:255)
	at me.ryanhamshire.griefprevention.claim.GPClaimManager.createWildernessClaim(GPClaimManager.java:392)
	at me.ryanhamshire.griefprevention.claim.GPClaimManager.getWildernessClaim(GPClaimManager.java:401)
	at me.ryanhamshire.griefprevention.claim.GPClaimManager.getClaimAt(GPClaimManager.java:473)
	at me.ryanhamshire.griefprevention.claim.GPClaimManager.getClaimAtPlayer(GPClaimManager.java:452)
	at me.ryanhamshire.griefprevention.DataStore.getClaimAtPlayer(DataStore.java:561)
	at me.ryanhamshire.griefprevention.claim.ClaimContextCalculator.accumulateContexts(ClaimContextCalculator.java:51)
	at me.ryanhamshire.griefprevention.claim.ClaimContextCalculator.accumulateContexts(ClaimContextCalculator.java:37)
	at me.lucko.luckperms.sponge.contexts.ProxiedContextCalculator.giveApplicableContext(ProxiedContextCalculator.java:50)
	at me.lucko.luckperms.sponge.contexts.ProxiedContextCalculator.giveApplicableContext(ProxiedContextCalculator.java:39)
	at me.lucko.luckperms.common.contexts.AbstractContextManager$Loader.load(AbstractContextManager.java:182)
	at me.lucko.luckperms.common.contexts.AbstractContextManager$Loader.load(AbstractContextManager.java:175)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache.lambda$new$0(BoundedLocalCache.java:3311)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2034)
	at java.util.concurrent.ConcurrentHashMap.compute(Unknown Source)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2032)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2015)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:113)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:67)
	at me.lucko.luckperms.common.contexts.AbstractContextManager.getApplicableContexts(AbstractContextManager.java:104)
	at me.lucko.luckperms.common.contexts.AbstractContextManager.getApplicableContext(AbstractContextManager.java:96)
	at me.lucko.luckperms.sponge.model.SpongeUser$UserSubject.getActiveContextSet(SpongeUser.java:194)
	at me.lucko.luckperms.sponge.service.proxy.api7.SubjectProxy.lambda$getActiveContexts$9(SubjectProxy.java:166)
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApplyStage(Unknown Source)
	at java.util.concurrent.CompletableFuture.thenApply(Unknown Source)
	at me.lucko.luckperms.sponge.service.proxy.api7.SubjectProxy.getActiveContexts(SubjectProxy.java:166)
	at net.minecraft.entity.player.EntityPlayerMP.getActiveContexts(EntityPlayerMP.java:2654)
	at net.minecraft.entity.player.EntityPlayerMP.hasPermission(EntityPlayerMP.java:2710)
	at io.github.nucleuspowered.nucleus.internal.CommandPermissionHandler.test(CommandPermissionHandler.java:254)
	at io.github.nucleuspowered.nucleus.internal.CommandPermissionHandler.testBase(CommandPermissionHandler.java:185)
	at io.github.nucleuspowered.nucleus.modules.powertool.listeners.PowertoolListener.onUserInteract(PowertoolListener.java:32)
	at org.spongepowered.common.event.listener.InteractEventListener_PowertoolListener_onUserInteract116.handle(Unknown Source)
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:371)
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:422)
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:207)
	at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractItemEventPrimary(SpongeCommonEventFactory.java:557)
	at org.spongepowered.common.network.PacketUtil.firePreEvents(PacketUtil.java:203)
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:91)
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zkl000(SourceFile:539)
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at net.minecraft.util.Util.func_181617_a(SourceFile:46)
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:274)
	at net.minecraft.server.MinecraftServer.redirect$onRun$zja000(MinecraftServer.java:4007)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)
```

**Closed by lucko** 2018-01-15 14:20 UTC
Labels: not a bug, question
