### ISSUE TITLE
Nukkit LuckPerms conflict with other plugin(FuturePlots)

### ISSUE THREAD

**Issue by JuChanMin** [lucko/LuckPerms#2342] opened 2020-05-28 07:52 UTC
I used this plugin - (https://nukkitx.com/resources/futureplots.457/)
and This developer of this plugin sees it as an error in luckperm - (https://github.com/tim03we/FuturePlots/issues/11)

This is When I start server with LuckPerms and FuturePlots and use FuturePlots command.

07:47:39 [FATAL] 땅에서 "땅 자동" 명령어 실행 중 처리되지 않은 예외가 발생했습니다: java.lang.NullPointerException: permission
        at java.util.Objects.requireNonNull(Objects.java:228)
        at me.lucko.luckperms.nukkit.inject.permissible.LuckPermsPermissible.addAttachment(LuckPermsPermissible.java:247)
        at cn.nukkit.Player.addAttachment(Player.java:535)
        at cn.nukkit.Player.addAttachment(Player.java:530)
        at cn.nukkit.Player.addAttachment(Player.java:525)
        at tim03we.futureplots.FuturePlots.claimAvailable(FuturePlots.java:172)
        at tim03we.futureplots.commands.AutoCommand.execute(AutoCommand.java:39)
        at tim03we.futureplots.commands.MainCommand.execute(MainCommand.java:37)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257)
        at cn.nukkit.Server.dispatchCommand(Server.java:759)
        at cn.nukkit.Player.handleDataPacket(Player.java:2802)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at cn.nukkit.network.Network.processPackets(Network.java:197)
        at cn.nukkit.network.Network.processBatch(Network.java:180)
        at cn.nukkit.Player.handleDataPacket(Player.java:2105)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:83)
        at cn.nukkit.Server.tick(Server.java:1132)
        at cn.nukkit.Server.tickProcessor(Server.java:911)
        at cn.nukkit.Server.start(Server.java:888)
        at cn.nukkit.Server.<init>(Server.java:573)
        at cn.nukkit.Nukkit.main(Nukkit.java:112)
07:47:39 [ERROR] Throwing
java.lang.NullPointerException: permission
        at java.util.Objects.requireNonNull(Objects.java:228) ~[?:1.8.0_252]
        at me.lucko.luckperms.nukkit.inject.permissible.LuckPermsPermissible.addAttachment(LuckPermsPermissible.java:247) ~[?:?]
        at cn.nukkit.Player.addAttachment(Player.java:535) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.addAttachment(Player.java:530) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.addAttachment(Player.java:525) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at tim03we.futureplots.FuturePlots.claimAvailable(FuturePlots.java:172) ~[?:?]
        at tim03we.futureplots.commands.AutoCommand.execute(AutoCommand.java:39) ~[?:?]
        at tim03we.futureplots.commands.MainCommand.execute(MainCommand.java:37) ~[?:?]
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.dispatchCommand(Server.java:759) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2802) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_252]
        at cn.nukkit.network.Network.processPackets(Network.java:197) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.Network.processBatch(Network.java:180) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2105) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66) [nukkit-1.0-SNAPSHOT.jar:?]

땅에서 "땅 자동" 명령어 실행 중 처리되지 않은 예외가 발생했습니다 = Unhandled exception during command execution.

Can you fix this? :c 

And thank you for making LuckPerms work in Nukkit! 
I'm always using it well! c:

**Comment by lucko** [comment] 2020-05-28 20:45
Duplicate of #2333 - it's not a LuckPerms error.

**Closed by lucko** 2020-05-28 20:45 UTC
