### ISSUE TITLE
Server crashes when command block is used to set permission

### ISSUE THREAD

**Issue by MrPistachios** [lucko/LuckPerms#2702] opened 2020-11-06 18:54 UTC
### Description
We have multiple command blocks at spawn to set prefixes, suffixes, keep inventory true or false, and natural health regen true or false.

Each command block gives a player the permission by targeting them with the @p selector
`lp user @p permission set noregen.on true server=neatobuilds`
`/lp user @p permission set essentials.keepinv false server=neatobuilds`
`lp user @p meta setsuffix &4`
`lp user @p meta setprefix &4`

### Reproduction steps

1. Start server
2. click on the button that triggers the command block
3. the button triggers the first command block `/lp user @p permission set essentials.keepinv true server=neatobuilds`
4. then it triggers the second command block `say @p turned on Keep Inventory`
5. command goes through but when it sends to luckperms the server goes down

Here is the start and crash log
[start and crash log](https://bytebin.lucko.me/3wey6qOYYR)

Here is the luckperms config for the server
[config.yml](https://bytebin.lucko.me/qUFGFk3SkK)

### Expected behavior
Before all the command blocks worked fine until I recently upgraded the server to 1.16.4 and updated luckperms.
We used to use the 'commandhook' plugin but it failed as well then we learned we had the option for LuckPerms to resolve Vanilla command target selectors

### Environment details
The server runs in a bungeecord network and serves as the main survival world where players first join and can choose a name and chat color and whether to enable keep-inv or not

* `>.... [18:54:09 INFO]: Previous version: git-Paper-259 (MC: 1.16.4)
>.... [18:54:09 INFO]: You are running the latest version`

* LuckPerms version: `LuckPerms-Bukkit-5.2.23.jar`

**Comment by underscore11code** [comment] 2020-11-06 22:21
Can you try to reproduce on a clean server (i.e. nothing other than LP installed). The errors are the server not responding, which I'm doubtful is LP's fault since just about everything we can do off the main thread, we use a different thread(s).

**Comment by MrPistachios** [comment] 2020-11-06 23:27
ok I copied over the command blocks to another server and removed all the plugins except Luckperms but still got a crash
[start and crash log](https://bytebin.lucko.me/kQLBxxjYIm)

let me try switching to a local database now

**Comment by MrPistachios** [comment] 2020-11-06 23:48
here is the crash again on a H2 database after I imported the data from the mysql database
[start and crash](https://bytebin.lucko.me/5Q41MtFSBP)

we can do the command no problem by typing it in but when a command block does the command it crashes

**Comment by benwoo1110** [comment] 2020-11-07 00:29
Try set `register-command-data-list` up to `false` in luckperms config.yml

**Comment by Fefo6644** [comment] 2020-11-07 00:40
@benwoo1110 it already is

**Comment by Aitnys** [comment] 2020-11-10 14:32
I have the same issue with the new update (5.2.26) after restoring the previous version (5.1.107) it stopped happening.

**Comment by lucko** [comment] 2020-11-10 16:17
Thanks - silly mistake from me.

Should be all fixed in the latest version.

**Closed by lucko** 2020-11-10 16:17 UTC
Labels: type: issue
