### ISSUE TITLE
Error Connecting To MySQL

### ISSUE THREAD

**Issue by Samkist** [lucko/LuckPerms#580] opened 2017-12-01 13:45 UTC
```
[14:38:13] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v4.0.34
[14:38:13] [Server thread/INFO]: [0;36;1m               __       [0;36;22m __   ___  __         __  [m
[14:38:13] [Server thread/INFO]: [0;36;1m    |    |  | /  ` |__/ [0;36;22m|__) |__  |__)  |\/| /__` [m
[14:38:13] [Server thread/INFO]: [0;36;1m    |___ \__/ \__, |  \ [0;36;22m|    |___ |  \  |  | .__/ [m
[14:38:13] [Server thread/INFO]:  [m
[14:38:13] [Server thread/INFO]: [0;32;22m  Loading version [0;36;1mv4.0.34[0;32;22m on Bukkit - CraftBukkit[m
[14:38:13] [Server thread/INFO]: [0;30;1m  Running on server version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) - 1.8.8-R0.1-SNAPSHOT[m
[14:38:13] [Server thread/INFO]:  [m
[14:38:13] [Server thread/INFO]: [0;37;22m[21m[[0;36;1mL[0;36;22mP[0;37;22m[21m] [0;36;22mLoading configuration...[m
[14:38:14] [Server thread/INFO]: [0;37;22m[21m[[0;36;1mL[0;36;22mP[0;37;22m[21m] [0;36;22mIdentified the following dependencies: [MYSQL_DRIVER, SLF4J_API, SLF4J_SIMPLE, HIKARI][m
[14:38:15] [Server thread/INFO]: [0;37;22m[21m[[0;36;1mL[0;36;22mP[0;37;22m[21m] [0;36;22mLoading storage provider... [MYSQL][m
[14:38:15] [Server thread/WARN]: [Server thread] INFO com.zaxxer.hikari.HikariDataSource - luckperms - Starting...
[14:38:17] [Server thread/WARN]: [Server thread] ERROR com.zaxxer.hikari.pool.HikariPool - luckperms - Exception during pool initialization.
[14:38:17] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[14:38:17] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14:38:17] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[14:38:17] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[14:38:17] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[14:38:17] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[14:38:17] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
[14:38:17] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:343)
[14:38:17] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2334)
[14:38:17] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
[14:38:17] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
[14:38:17] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
[14:38:17] [Server thread/WARN]: 	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[14:38:17] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14:38:17] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[14:38:17] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[14:38:17] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[14:38:17] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[14:38:17] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
[14:38:17] [Server thread/WARN]: 	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
[14:38:17] [Server thread/WARN]: 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
[14:38:17] [Server thread/WARN]: 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
[14:38:17] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:375)
[14:38:17] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:204)
[14:38:17] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:459)
[14:38:17] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:533)
[14:38:17] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:114)
[14:38:17] [Server thread/WARN]: 	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72)
[14:38:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.dao.sql.connection.hikari.HikariConnectionFactory.init(HikariConnectionFactory.java:94)
[14:38:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.dao.sql.SqlDao.init(SqlDao.java:154)
[14:38:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.AbstractStorage.init(AbstractStorage.java:68)
[14:38:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.wrappings.PhasedStorage.init(PhasedStorage.java:62)
[14:38:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.wrappings.BufferedOutputStorage.init(BufferedOutputStorage.java:46)
[14:38:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:115)
[14:38:17] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.LPBukkitPlugin.enable(LPBukkitPlugin.java:214)
[14:38:17] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.LPBukkitPlugin.onEnable(LPBukkitPlugin.java:174)
[14:38:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[14:38:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[14:38:17] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[14:38:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[14:38:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[14:38:17] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199)
[14:38:17] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[14:38:17] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[14:38:17] [Server thread/WARN]: Caused by: java.net.ConnectException: Connection refused (Connection refused)
[14:38:17] [Server thread/WARN]: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
[14:38:17] [Server thread/WARN]: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[14:38:17] [Server thread/WARN]: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[14:38:17] [Server thread/WARN]: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[14:38:17] [Server thread/WARN]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[14:38:17] [Server thread/WARN]: 	at java.net.Socket.connect(Socket.java:589)
[14:38:17] [Server thread/WARN]: 	at java.net.Socket.connect(Socket.java:538)
[14:38:17] [Server thread/WARN]: 	at java.net.Socket.<init>(Socket.java:434)
[14:38:17] [Server thread/WARN]: 	at java.net.Socket.<init>(Socket.java:244)
[14:38:17] [Server thread/WARN]: 	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:254)
[14:38:17] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:292)
[14:38:17] [Server thread/WARN]: 	... 36 more
[14:38:17] [Server thread/WARN]: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[14:38:17] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:568)
[14:38:17] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:554)
[14:38:17] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:114)
[14:38:17] [Server thread/WARN]: 	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72)
[14:38:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.dao.sql.connection.hikari.HikariConnectionFactory.init(HikariConnectionFactory.java:94)
[14:38:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.dao.sql.SqlDao.init(SqlDao.java:154)
[14:38:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.AbstractStorage.init(AbstractStorage.java:68)
[14:38:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.wrappings.PhasedStorage.init(PhasedStorage.java:62)
[14:38:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.wrappings.BufferedOutputStorage.init(BufferedOutputStorage.java:46)
[14:38:17] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:115)
[14:38:17] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.LPBukkitPlugin.enable(LPBukkitPlugin.java:214)
[14:38:17] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.LPBukkitPlugin.onEnable(LPBukkitPlugin.java:174)
[14:38:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[14:38:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[14:38:17] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[14:38:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[14:38:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[14:38:17] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199)
[14:38:17] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[14:38:17] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[14:38:17] [Server thread/WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[14:38:17] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14:38:17] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[14:38:17] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[14:38:17] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[14:38:17] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[14:38:17] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
[14:38:17] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:343)
[14:38:17] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2334)
[14:38:17] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
[14:38:17] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
[14:38:17] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
[14:38:17] [Server thread/WARN]: 	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[14:38:17] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14:38:17] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[14:38:17] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[14:38:17] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[14:38:17] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[14:38:17] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
[14:38:17] [Server thread/WARN]: 	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
[14:38:17] [Server thread/WARN]: 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
[14:38:17] [Server thread/WARN]: 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
[14:38:17] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:375)
[14:38:17] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:204)
[14:38:17] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:459)
[14:38:17] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:533)
[14:38:17] [Server thread/WARN]: 	... 18 more
[14:38:17] [Server thread/WARN]: Caused by: java.net.ConnectException: Connection refused (Connection refused)
[14:38:17] [Server thread/WARN]: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
[14:38:17] [Server thread/WARN]: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[14:38:17] [Server thread/WARN]: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[14:38:17] [Server thread/WARN]: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[14:38:17] [Server thread/WARN]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[14:38:17] [Server thread/WARN]: 	at java.net.Socket.connect(Socket.java:589)
[14:38:17] [Server thread/WARN]: 	at java.net.Socket.connect(Socket.java:538)
[14:38:17] [Server thread/WARN]: 	at java.net.Socket.<init>(Socket.java:434)
[14:38:17] [Server thread/WARN]: 	at java.net.Socket.<init>(Socket.java:244)
[14:38:17] [Server thread/WARN]: 	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:254)
[14:38:17] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:292)
[14:38:17] [Server thread/WARN]: 	... 36 more
[14:38:17] [Server thread/INFO]: [0;37;22m[21m[[0;36;1mLuck[0;36;22mPerms[0;37;22m[21m] [0;31;22m[ERROR] Error occurred whilst initialising the database.[m
[14:38:19] [Server thread/INFO]: [0;37;22m[21m[[0;36;1mL[0;36;22mP[0;37;22m[21m] [0;36;22mLoading internal permission managers...[m
[14:38:19] [Server thread/INFO]: [0;37;22m[21m[[0;36;1mL[0;36;22mP[0;37;22m[21m] [0;36;22mPerforming initial data load...[m
[14:38:19] [Server thread/ERROR]: Error occurred while enabling LuckPerms v4.0.34 (Is it up to date?)
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_151]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_151]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592) ~[?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at me.lucko.luckperms.common.storage.dao.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:131) ~[?:?]
	at me.lucko.luckperms.common.storage.dao.sql.SqlDao.loadAllGroups(SqlDao.java:675) ~[?:?]
	at me.lucko.luckperms.common.storage.AbstractStorage.lambda$loadAllGroups$7(AbstractStorage.java:164) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_151]
	... 3 more
```
I have tried everything to my knowledge at one point I just opened all the ports, I have my mysql port allowing all TCP connections on the default mysql port, the mysql db is on the same server as the servers, should I use localhost as the address? This is my config

https://hastebin.com/aderihuceg.coffeescript

**Comment by spannerman79** [comment] 2017-12-01 15:11
`[14:38:17] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure`
**Communications link failure**

Not a Luckperms issue. http://lmgtfy.com/?q=Communications+link+failure+mysql

**Comment by Samkist** [comment] 2017-12-01 15:26
I looked it up and I only got things for developers as in writing plugins, and I combed the error several times, I shouldn’t have to under stand all the java and MySQL errors just to run a plugin the way I want, that google search only turned up things that had no relation to what I was doing.

**Comment by Samkist** [comment] 2017-12-01 15:27
I am trying to open my ports

**Comment by Samkist** [comment] 2017-12-01 15:35
How do I open all connections to the tcpport

**Comment by BrainStone** [comment] 2017-12-01 15:38
Please read the last section of this page: https://github.com/lucko/LuckPerms/wiki/FAQ

**Comment by BrainStone** [comment] 2017-12-01 15:42
Also try replacing `localhost` with `127.0.0.1` as localhost might translate to `::1` (IPv6 localhost).

**Comment by Samkist** [comment] 2017-12-01 16:06
Thanks!

**Comment by Samkist** [comment] 2017-12-01 16:11
It still didn't work for me ;/ I also have my servers running on a dedicated server under 0.0.0.0 could that have anything to do with it?

**Comment by Samkist** [comment] 2017-12-01 19:16
Could this have something to do with the size of my connection pool?

**Comment by MWFIAE** [comment] 2017-12-01 19:20
A poolsize of 10 is perfectly fine, more would probably hurt performance

**Comment by BrainStone** [comment] 2017-12-01 19:29
Is it a linux server? If so run this command in the command line: `netstat -tlpn | grep mysql`  
The out put should look like this: `tcp        0      0 0.0.0.0:3306            0.0.0.0:*               LISTEN      5921/mysqld` The `0.0.0.0:3306` in this example case is the IP and port the MySQL server is listening to. If it is `0.0.0.0` use `127.0.0.1` in your LP config. Also make sure you use the right port in the config.

And a pool size of 10 is a good value.

**Comment by Samkist** [comment] 2017-12-01 23:11
It says 127.0.0.1:3306

**Comment by Samkist** [comment] 2017-12-02 00:50
I did this and it's listening to all ips from all ports and on 3306

https://imgur.com/a/KBCHT

**Comment by BrainStone** [comment] 2017-12-02 15:29
Do you by any chance run the Minecraft servers inside a docker container?

**Comment by lucko** [comment] 2017-12-03 10:36
This isn't a LuckPerms issue - so I'm going to close the issue.

**Closed by lucko** 2017-12-03 10:36 UTC
Labels: question

**Comment by Samkist** [comment] 2017-12-12 23:19
@lucko Can you please open this I think @BrainStone is right, I do run the minecraft servers inside docker

**Comment by Foorack** [comment] 2017-12-12 23:32
@Samkist This is still not a LuckPerms issue, but rather a problem with your setup. If you run the minecraft server in docker then the database IP should not be 127.0.0.1.

Does your MySQL server also run in a docker container? If so then the hostname should be the network name of that docker container.

Does it not? Then please see this thread on how to setup so it can access the host or google "docker connect to host". https://forums.docker.com/t/accessing-host-machine-from-within-docker-container/14248/9

**Comment by Samkist** [comment] 2017-12-13 14:34
I found this but I don't know if my docker container has an IP?

`docker network create -d bridge --subnet (ip)/24 --gateway (other ip?)
dockernet`
@Foorack

**Comment by Foorack** [comment] 2017-12-13 16:05
@Samkist This is confirmed not to be a LuckPerms issue. I don't think this is the correct place to continue discussing this. For more help I recommend you asking on the Docker Forum or with whoever configured your Docker setup. **It is important to note that `127.0.0.1` does not point to the host machine, only to the virtual docker container itself.**

If your MySQL is running on the same host machine then you need to find a solution to connect to the host machine from inside the docker container. This is not the easiest and it is therefore recommended to run everything-containerized or containerize your dependencies (databases, etc) first.

There is currently no "correct" way to connect from a container to the host as this violates the principle of isolation in the first place. See this StackOverflow answer and the links it mentions for more information: https://stackoverflow.com/a/28058549 But the way you have to do it depends on the version you are running, what network stack you are running, what operating system you are running it on, etc...

I am curious why you are running a Minecraft server in Docker in the first place. I am a developer for a server where we are currently in the process of deploying Docker to everything on our network but that is purely for scaling purposes as the number of individual servers has now become slow to manage. Does using Docker make sense for your setup? If you want to continue using Docker for whatever reason then your best bet is to containerize the MySQL database as well. That way you can specify the host as the name of the MySQL container. If you do this then remember data inside docker volumes are not always persistent, and storing the database directly to the hard drive is highly recommended. :+1:

**Comment by Samkist** [comment] 2017-12-14 01:15
@Foorack I have a panel that creates the Docker I do not know if it does it inside all one Docker or in multiple to contain the ram but I use it the panel http://pterodactyl.net, I believe the panel or it’s daemon “wings” inits the Docker container so idk if Docker run would work and I am not exactly far along in the tech world as I am 14 so the best I can do is try to understand commands but I’m having some trouble.

**Comment by Foorack** [comment] 2017-12-14 09:46
@Samkist Ohh, you use pterodactyl, it makes more sense why your Minecraft server is containerized then. I'm sorry I have never worked with that panel in the past so my knowledge in that area is limited.

In that case, I recommend you to contact them as they surely have had this topic before. At the top of the Spigot post, there is a Discord (they will most likely answer fastest there) and a Github link. This is not a LuckPerms specific issue, tell them you have a plugin which wants to connect to the MySQL server running on the host machine, but it can't because the server is containerized and therefore can't connect. They should from there be able to guide you. Good luck. :smiley: 

https://www.spigotmc.org/threads/pterodactyl-panel-%E2%80%94-the-next-generation-of-free-multi-server-management-now-with-whmcs-support.114030/

**Comment by Samkist** [comment] 2017-12-14 12:04
Thank you @Foorack!

**Comment by AdamAtomus** [comment] 2019-10-27 13:46
OH

**Comment by linusstretchtips** [comment] 2020-06-01 21:04
your 2 years late lmao

**Comment by Cyanoure** [comment] 2023-04-23 16:33
lol
