### ISSUE TITLE
Please Fix MySql Connector

### ISSUE THREAD

**Issue by joeymaeuslp** [lucko/LuckPerms#739] opened 2018-02-07 15:00 UTC
sorry that I'm so hard but it can not be that you developed a plugin that supposedly better than permissonsex should be and it does not get it luckperms is a cool plugin but please it can not be that it only makes errors and now does not come with it is up to my database my database is exactly as yours please raises the disabled mysql errors a 9 years old java kiddie can deal better with mysql

excuse my unfriendliness but man has to speak hard words so that you understand it does not come to me now I have no idea I am a Java developer and programmers 17 years and have Java even in my training as an application developer

the errors come from your plugin and not from my database with pex is my oh so bad database so synonymous

luckperms - Failed to validate connection me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection@659a7eda (No operations allowed after connection closed.)
[15:49:37 WARN]: luckperms - Failed to validate connection me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection@5fa872f1 (No operations allowed after connection closed.)
[15:49:37 WARN]: luckperms - Failed to validate connection me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection@11f23b74 (No operations allowed after connection closed.)
[15:49:37 WARN]: luckperms - Failed to validate connection me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection@2728eb3e (No operations allowed after connection closed.)
[15:49:37 WARN]: luckperms - Failed to validate connection me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection@40b70342 (No operations allowed after connection closed.)
[15:49:37 WARN]: luckperms - Failed to validate connection me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection@5c14de5f (No operations allowed after connection closed.)
[15:49:37 WARN]: luckperms - Failed to validate connection me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection@5c3d6732 (No operations allowed after connection closed.)
[15:49:37 WARN]: luckperms - Failed to validate connection me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection@3c2c0690 (No operations allowed after connection closed.)
[15:49:37 INFO]: UUID of player JoeyPlayzTV is f54fe29c-c234-4191-bce5-a3291f9f9629

**Comment by lucko** [comment] 2018-02-07 15:07
**It has nothing to do with LuckPerms.**

As I have already said:

> The error has nothing to do with LuckPerms, it's coming from the MySQL driver & Hikari - again, nothing to do with me.

> You can try tweaking the timeout settings in the config file.

There's also an FAQ entry which explains what you can do.

https://github.com/lucko/LuckPerms/wiki/FAQ#mysql-no-operations-allowed-after-connection-closed-error


> excuse my unfriendliness but man has to speak hard words so that you understand it does not come to me now I have no idea I am a Java developer and programmers 17 years and have Java even in my training as an application developer

Even with basic experience of using JDBC, you'd know that connection errors being thrown by the driver are clearly not caused by the application *using* the driver.



Duplicate of #738

Please do not make any more tickets. If you have more to say, you can reply here.

**Closed by lucko** 2018-02-07 15:07 UTC

**Comment by Andre601** [comment] 2018-02-07 15:08
Calm down dude.
Even if you're angry that the MySQL-option doesn't work for you is no excuse to publicly insult Luck for that (`...please raises the disabled mysql errors a 9 years old java kiddie can deal better with mysql`)
Also if you're a Dev, that has 17 years of experience (Which I honestly don't believe), youwould know, whyt Luck just mentioned above.

**Comment by joeymaeuslp** [comment] 2018-02-07 15:28
Please Lucko I do not want you anything bad I just want to point out an error that you should fix before you claim your plugin is better than pex take me an example of pex or give me a clever answer as I fix the error is because so hard

**Comment by lucko** [comment] 2018-02-07 15:30
You're either ignoring my advice or not just reading it.

The issue is not caused by LuckPerms. Just accept it - there's no reason why I'd lie to you about that.



I'm just going to quote my previous replies. Please listen to what I'm saying.

> The error has nothing to do with LuckPerms, it's coming from the MySQL driver & Hikari

> You can try tweaking the timeout settings in the config file.

> There's also an FAQ entry which explains what you can do.
https://github.com/lucko/LuckPerms/wiki/FAQ#mysql-no-operations-allowed-after-connection-closed-error

**Comment by joeymaeuslp** [comment] 2018-02-07 15:31
I like your plugin and I do not want you anything bad I just want to draw your attention to something that you can do better Please mind about my concern Please explain to me your timeout settings Your contribution on gitup is not helpful

**Comment by lucko** [comment] 2018-02-07 15:33
> I just want to draw your attention to something that you can do better

There is nothing wrong. **I** cannot "do anything better", because **I** didn't write the MySQL driver.

  *Please* read my previous reply.

**Comment by joeymaeuslp** [comment] 2018-02-07 15:35
i give you my LuckPerms Config

**Comment by joeymaeuslp** [comment] 2018-02-07 15:36
Here is my Config https://pastebin.com/srGRwULR

**Comment by lucko** [comment] 2018-02-07 15:36
https://github.com/lucko/LuckPerms/wiki/FAQ#mysql-no-operations-allowed-after-connection-closed-error

^^ **It tells you what to do here** ^^

Here, I'll even copy it for you, since clicking links is apparently too hard.

___

### MySQL "No operations allowed after connection closed" error
If you get an error similar to:
> com.zaxxer.hikari.pool.PoolBase - luckperms - Failed to validate connection com.mysql.jdbc.JDBC4Connection@xxxxxxx (No operations allowed after connection closed.)

... you need to modify the `maximum-lifetime` setting in the 'pool-settings' section, within "Storage", in the LuckPerms config file.

This setting (defaults to 30 minutes and measured in milliseconds) must be **less** than the `wait_timeout` value set on your MySQL server.

https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_wait_timeout

The default value of 30 minutes is fine for the **vast** majority of users. It only becomes a problem if you or your hosting provider has changed the wait timeout setting.

If your MySQL server is provided by a 3rd party, ask them what the value is set to.

**Comment by lucko** [comment] 2018-02-07 15:37
Your config is useless to me unless you can also tell me what the `wait_timeout` setting is for your MySQL server.

**Comment by joeymaeuslp** [comment] 2018-02-07 15:39
I have tested several values ​​now it is 5 minutes Tell me what is better I should go higher or lower with the value

and I have read what you have given me but it is not helpful for me

**Comment by lucko** [comment] 2018-02-07 15:39
If you tell me what `wait_timeout` is set to, I can suggest a value.

**Comment by joeymaeuslp** [comment] 2018-02-07 15:40
the Section wait_timeout is not in my Config

**Comment by lucko** [comment] 2018-02-07 15:41
It's a MySQL setting.

Do you host your own MySQL server, or does a hosting company provide it for you?

**Comment by joeymaeuslp** [comment] 2018-02-07 15:42
i host my mysql database on Nitrado
