### ISSUE TITLE
Error dispatching event PermissionCheckEvent 

### ISSUE THREAD

**Issue by Nextopi** [lucko/LuckPerms#2225] opened 2020-04-25 05:25 UTC
Bungeecord + Fastlogin

Sometimes when someone logs in, you get this error very frequently with several players.

https://paste.gg/p/anonymous/b6c4629d1bca4b98b4a113fdb2375ee1/files/f5c9fe78f7eb49c790b2de739a938e14/raw

https://github.com/games647/FastLogin/issues/319

**Comment by Laarryy** [comment] 2020-04-25 05:26
That's a problem with FastLogin not processing UUIDs correctly, looks like. Is it a cracked server?

**Comment by Nextopi** [comment] 2020-04-28 04:16
each plugin blame eachother, who do I believe ?

**Comment by Laarryy** [comment] 2020-04-28 04:21
`[LuckPerms]: A permission check was made for player kik1nho - 94b4ced2-8a3c-4e76-97c6-afd9da37ca8c, but LuckPerms does not have any permissions data loaded for them. Perhaps their UUID has been altered since login?`

This error says that a player is not authenticating properly. Since Luckperms does not handle authentication, I'm inclined to say it's whatever service you use to authenticate. However, you can test this by removing FastLogin and seeing if it works. If it doesn't you should confirm that your bungeecord system is set up correctly and `bungee-online-mode` is set to true in the bungee config. Make sure `ip-forwarding` and `bungeecord` are both set to true in spigot.yml

If all of this is correct and the you still get the mismatched UUID, it may be that you have chosen to run your server cracked, or non-premium, and you do not have a properly functioning authentication system. 

Regardless, LP relies on one user having one UUID to work - if that does not happen, the system cannot function. It's not Luckperms causing the problem, but rather it is pointing out there is a problem and it should be resolved.

**Comment by Andre601** [comment] 2020-04-28 04:41
FastLogin is known to alter the UUID of a player, causing LP major issues, since the same name now belongs to a different UUID.

**Comment by BrainStone** [comment] 2020-04-28 09:12
What amazes me to this day is that they to this date still haven’t acknowledged the issue. It’s 100% on their side and I’m amazed that other plugins don’t break either. Also this probably can easily be fixed by them by running their code earlier.

**Comment by lucko** [comment] 2020-04-28 11:49
This isn't a FastLogin issue

**Comment by lucko** [comment] 2020-04-28 11:49
Probably related to #2107

**Comment by lucko** [comment] 2020-04-28 12:49
Duplicate of #2107 - please see my comment there & let me know if the fix worked. :)

**Closed by lucko** 2020-04-28 12:49 UTC
Labels: type: issue
