### ISSUE TITLE
1.13.1 SQL Error - BungeeCord-Bootstrap:1.13-SNAPSHOT:ba07397:1355

### ISSUE THREAD

**Issue by natr566** [lucko/LuckPerms#1192] opened 2018-09-02 18:21 UTC
19:19:38 [INFO] Using standard Java JCE cipher.
19:19:38 [INFO] Using standard Java compressor.
19:19:38 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.13-SNAPSHOT:ba07397:1355
19:19:38 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())
19:19:38 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())
19:19:38 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())
19:19:38 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())
19:19:38 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())
19:19:38 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())
19:19:38 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
19:19:38 [INFO] Loaded plugin LuckPerms version 4.2.85 by Luck
19:19:38 [INFO] Loaded plugin cmd_find version git:cmd_find:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
19:19:38 [INFO] Loaded plugin cmd_server version git:cmd_server:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
19:19:38 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
19:19:38 [INFO] Loaded plugin cmd_send version git:cmd_send:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
19:19:38 [INFO] Loaded plugin cmd_list version git:cmd_list:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
19:19:38 [WARNING] Forced host server pvp is not defined
19:19:38 [WARNING] MinecraftForge support is currently unmaintained and may have unresolved issues. Please use at your own risk.
19:19:38 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
19:19:38 [INFO]         __
19:19:38 [INFO]   |    |__)   LuckPerms v4.2.85
19:19:38 [INFO]   |___ |      Running on Bungee - BungeeCord
19:19:38 [INFO]
19:19:38 [INFO] [LuckPerms] Loading configuration...
19:19:38 [INFO] [LuckPerms] Loading storage provider... [MYSQL]
19:19:38 [SEVERE] [main] INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Starting...
19:19:38 [SEVERE] [LuckPerms] Failed to init storage dao
19:19:38 [SEVERE] java.lang.RuntimeException: java.lang.ClassNotFoundException: me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource
19:19:38 [SEVERE]     at me.lucko.luckperms.lib.hikari.util.UtilityElf.createInstance(UtilityElf.java:113)
19:19:38 [INFO] [LuckPerms] Loading messaging service... [BUNGEE]
19:19:38 [SEVERE]     at me.lucko.luckperms.lib.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:332)
19:19:38 [SEVERE]     at me.lucko.luckperms.lib.hikari.pool.PoolBase.<init>(PoolBase.java:109)
19:19:38 [SEVERE]     at me.lucko.luckperms.lib.hikari.pool.HikariPool.<init>(HikariPool.java:108)
19:19:38 [SEVERE]     at me.lucko.luckperms.lib.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
19:19:38 [SEVERE]     at me.lucko.luckperms.common.storage.dao.sql.connection.hikari.HikariConnectionFactory.init(HikariConnectionFactory.java:91)
19:19:38 [SEVERE]     at me.lucko.luckperms.common.storage.dao.sql.SqlDao.init(SqlDao.java:159)
19:19:38 [SEVERE]     at me.lucko.luckperms.common.storage.AbstractStorage.init(AbstractStorage.java:122)
19:19:38 [SEVERE]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19:19:38 [SEVERE]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
19:19:38 [SEVERE]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
19:19:38 [SEVERE]     at java.lang.reflect.Method.invoke(Unknown Source)
19:19:38 [SEVERE]     at me.lucko.luckperms.common.storage.wrappings.PhasedStorage.lambda$wrap$0(PhasedStorage.java:64)
19:19:38 [SEVERE]     at com.sun.proxy.$Proxy3.init(Unknown Source)
19:19:38 [SEVERE]     at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:117)
19:19:38 [SEVERE]     at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:132)
19:19:38 [SEVERE]     at me.lucko.luckperms.bungee.LPBungeeBootstrap.onEnable(LPBungeeBootstrap.java:124)
19:19:38 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
19:19:38 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:281)
19:19:38 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
19:19:38 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
19:19:38 [SEVERE] Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource
19:19:38 [SEVERE]     at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
19:19:38 [SEVERE]     at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
19:19:38 [SEVERE]     at java.lang.ClassLoader.loadClass(Unknown Source)
19:19:38 [SEVERE]     at me.lucko.luckperms.lib.hikari.util.UtilityElf.createInstance(UtilityElf.java:100)
19:19:38 [SEVERE]     ... 20 more
19:19:39 [INFO] [LuckPerms] Loading internal permission managers...
19:19:39 [INFO] [LuckPerms] Performing initial data load...
19:19:39 [SEVERE] java.util.concurrent.CompletionException: java.lang.NullPointerException
19:19:39 [SEVERE]     at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
19:19:39 [INFO] [LuckPerms] Successfully enabled. (took 318ms)
19:19:39 [SEVERE]     at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
19:19:39 [SEVERE]     at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
19:19:39 [SEVERE]     at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
19:19:39 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
19:19:39 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
19:19:39 [SEVERE]     at java.lang.Thread.run(Unknown Source)
19:19:39 [SEVERE] Caused by: java.lang.NullPointerException
19:19:39 [SEVERE]     at me.lucko.luckperms.common.storage.dao.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:128)
19:19:39 [SEVERE]     at me.lucko.luckperms.common.storage.dao.sql.SqlDao.loadAllGroups(SqlDao.java:609)
19:19:39 [SEVERE]     at me.lucko.luckperms.common.storage.AbstractStorage.lambda$loadAllGroups$10(AbstractStorage.java:214)
19:19:39 [SEVERE]     at me.lucko.luckperms.common.storage.AbstractStorage.lambda$makeFuture$1(AbstractStorage.java:102)
19:19:39 [SEVERE]     ... 5 more
19:19:39 [INFO] Enabled plugin LuckPerms version 4.2.85 by Luck
19:19:39 [INFO] Enabled plugin cmd_find version git:cmd_find:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
19:19:39 [INFO] Enabled plugin cmd_server version git:cmd_server:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
19:19:39 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
19:19:39 [INFO] Enabled plugin cmd_send version git:cmd_send:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
19:19:39 [INFO] Enabled plugin cmd_list version git:cmd_list:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
19:19:39 [INFO] Listening on /0.0.0.0:25577
>bungee
19:19:48 [INFO] This server is running BungeeCord version git:BungeeCord-Bootstrap:1.13-SNAPSHOT:ba07397:1355 by md_5
>

**Comment by Andre601** [comment] 2018-09-02 18:28
Please use https://hastebin.com or https://gist.github.com to share errors, since reading them from a issue is just annoying and slows down support.

**Comment by natr566** [comment] 2018-09-02 18:32
https://gist.github.com/natr566/15bf9716be2ccdcaaad1f1aed1ad9538

**Comment by natr566** [comment] 2018-09-02 18:32
Sory Im new at this

**Comment by codingJWilliams** [comment] 2018-09-02 19:04
Here's the actual issue:
When running luckperms with Bungeecord build [1533](https://ci.md-5.net/job/BungeeCord/1355/), an error occurs on startup, as seen here: https://gist.github.com/natr566/15bf9716be2ccdcaaad1f1aed1ad9538

You can reproduce this by starting the bungeecord jar linked above and adding the [latest luckperms](https://ci.lucko.me/view/LuckPerms/job/LuckPerms/746/artifact/bungee/build/libs/LuckPerms-Bungee-4.2.85.jar) to the plugins folder, restarting bungee, and configuring it to use mysql storage (doesn't make a difference if you give it working creds or not)

**Comment by lucko** [comment] 2018-09-02 19:05
Fixed in 2da027f3b5b5e2e95f82a031586d51debeee9070

**Comment by codingJWilliams** [comment] 2018-09-02 19:05
Dammit just as I wrote a proper report :stuck_out_tongue:

**Closed by lucko** 2018-09-02 19:05 UTC
