### ISSUE TITLE
Direct server crash when starting server (fabric)

### ISSUE THREAD

**Issue by emielderckx** [lucko/LuckPerms#2936] opened 2021-03-09 14:49 UTC
### Description
Just a lot of errors and a crashing server, don't really know what happens.
I tried running with the lastest build on the site (5.3.0) and on old version on modrinth (5.2.92). With each build I get the errors.
When removing luckperms the server runs smooth.

### Server: 
2gb - shared test server
```
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (build 1.8.0_262-b10)
OpenJDK 64-Bit Server VM (build 25.262-b10, mixed mode)
:/home/container$ java -Xms128M -Xmx2048M -jar server.jar
[15:41:09] [main/INFO]: Loading for game Minecraft 1.16.5
```

### Error:
https://mcpaste.io/71c41545486ea761

### Mods installed:
![image](https://user-images.githubusercontent.com/35953244/110487954-5addf700-80ee-11eb-8559-09ad0320bdd5.png)

**Comment by emielderckx** [comment] 2021-03-18 19:16
It looks like there is a conflict between chunky pre gen and luckperms

**Comment by uRyanxD** [comment] 2021-03-18 22:37
Minecraft 1.16.5 usa jdk 11 se não me engano.

**Comment by emielderckx** [comment] 2021-03-18 23:35
Same problem on java 11, chunky dev says its luckperms problem not his code

**Comment by lucko** [comment] 2021-03-19 19:36
Closing as duplicate of #2880

**Closed by lucko** 2021-03-19 19:36 UTC
Labels: type: issue
