### ISSUE TITLE
How to Use Prefixes Without Vault (EssentialsEx Chat)

### ISSUE THREAD

**Issue by GamingInfinite** [lucko/LuckPerms#1918] opened 2020-01-06 15:27 UTC
Well, exactly what the title says.  Vault hasn't been updated for 1.15 so I guess what I'm asking is do I have to wait for the 1.15 version to come out? Or is there like an alternative to Vault for 1.15? Or an early build type thing?

**Comment by BrainStone** [comment] 2020-01-06 15:49
Plugins typically don’t need to be updated. Which is the point of a plugin. If you are not sure if it works, try it out. And Vault is especially Version independent and works just fine on 1.15. And most likely will still work 10+ years into the future.

**Comment by james090500** [comment] 2020-01-06 16:34
I can confirm EssentialsXChat + Vault work fine on 1.15.

**Comment by Robby-** [comment] 2020-01-08 00:07
I wish there was a way to have prefixes/suffixes in chat without needing additional plugins except for the plugin itself that provides it (thus no Vault + \<the actual plugin that provides chat formatting\>). I try to keep the amount of plugins/bloat to a minimum.

**Comment by BrainStone** [comment] 2020-01-08 00:11
LuckPerms is a permissions plugin. Not a chat plugin. Adding chat functionality to LP would be unnecessary bloat.

Also there's a difference between many plugins and bloat.  
Having many plugins that each do one thing and that as good as possible is a lot better than having 1 plugin for many things and them only working half heartedly

**Comment by Andre601** [comment] 2020-01-08 00:13
> I wish there was a way to have prefixes/suffixes in chat without needing additional plugins except for the plugin itself that provides it (thus no Vault + <the actual plugin that provides chat formatting>). I try to keep the amount of plugins/bloat to a minimum.

The reason behind why LuckPerms doesn't provide chat management is simple: It's out of scope.
LuckPerms is a **permission** plugin (keyword is permission) and managing chat is something no real perm plugin should do.

Also, almost every major, popular plugin you may use will most likely support Vault, since Vault is almost a go-to plugin for every server in existence. And there are always alternatives for more lightweight chat plugins that don't "bloat" your server.

**Comment by Robby-** [comment] 2020-01-08 00:17
Yes, I did not mean that LuckPerms should provide this functionality too. What I meant was that I'd like to have only one additional plugin that provides the formatting and have it work without needing Vault too.

**Comment by BrainStone** [comment] 2020-01-08 00:21
Vault exists so that plugin devs don't need to individually support every permissions plugin in existance. Which would be insane to be honest. As Vault provides common functionality to get prefixes and such. It makes a lot more sense to just require Vault. Because then you instantly support every permissions plugin (that also supports Vault, which is essentially all). Vault also has 0 impact on your server as it does nothing by itself.  
It is also needed if you want to use economy between two plugins, as it provides common functionality for that too,

**Closed** 2020-01-25 12:04 UTC

**Comment by lucko** [comment] 2020-01-25 12:06
Vault is the de-facto method for chat plugins to retrieve prefix/suffix data.

More plugins does not necessarily mean more bloat - in this case Vault (an abstraction layer) actually decreases the bloat required to obtain such data.
