### ISSUE TITLE
Not issue, just a question

### ISSUE THREAD

**Issue by catalintrasca** [lucko/LuckPerms#505] opened 2017-10-16 09:48 UTC
Hey everyone, this is not an issue reporting, I'm here just to ask a question : I've configured the group A with 40 permission nodes (just examples) and now I want to configure the group B with the same 40 permission nodes and some other permissions in plus. Is there any way to transfer all permissions of a group to another group automatically instead of re-typing them manually? Thanks

**Comment by spannerman79** [comment] 2017-10-16 09:54
Use tracks - more efficient.
https://github.com/lucko/LuckPerms/wiki/Tracks

**Comment by catalintrasca** [comment] 2017-10-16 10:17
thanks for the answer but this won't help me too much. I just need a way to copy all the permissions from a group to another group by a command (if this is possible). of course the ranks are like a 'ladder'. like : group B have group A's all permissions + few more. maybe u got me. 😃

**Comment by spannerman79** [comment] 2017-10-16 10:21
You have the setup of;

> I've configured the group A with 40 permission nodes (just examples) and now I want to configure the group B with the same 40 permission nodes and some other permissions in plus

You use tracks for that.

You don't need to have a duplicate of everything in `GroupA` in `GroupB`, as `GroupB` would have the perms already that are in `GroupA` plus the extra's you mentioned if in a track.

NB:  There is a discord for asking things like this, this isn't an actual issue with luckperms ie: NullPointerException, etc

**Comment by catalintrasca** [comment] 2017-10-16 10:24
okay. I understood, thank you very much for your answers.

**Closed** 2017-10-16 10:24 UTC

**Comment by merjilin** [comment] 2017-10-16 11:16
You could also use `/lp group <group b> parent add <group a>`. That ways, group b inherit all permissions from group a.

**Comment by catalintrasca** [comment] 2017-10-16 11:55
this is what I was looking for! thank you 💪
