### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by hornta** [lucko/LuckPerms#2201] opened 2020-04-19 21:55 UTC
Got this in my console reported it here as the output wanted me to do :-)

>....WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by me.lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader (file:/home/container/plugins/LuckPerms-Bukkit-5.0.23.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of me.lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by Andre601** [comment] 2020-04-19 22:19
Duplicate of #952 

You can ignore this.

**Closed** 2020-04-24 15:55 UTC
Labels: type: question
