### ISSUE TITLE
Error "Another command is being executed, waiting for it to finish..."

### ISSUE THREAD

**Issue by Feldmarschall** [lucko/LuckPerms#2951] opened 2021-03-20 13:25 UTC
**Description**

Short report, as there is almost no support on Discord. Since the last LuckPerm update, my console commands no longer work.

**Serverversion:**

This server is running Paper version git-Paper-562 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-526 (MC: 1.16.5)

**LuckPerm version 5.3.0**

**Commands:**

```
     - '[console] lp user %player_name% permission set test.test1'
      - '[console] lp user %player_name% permission set test.test2'
      - '[console] lp user %player_name% permission set test.test3 false'
      - '[console] lp user %player_name% permission unset test.test4 false'
      - '[console] lp user %player_name% permission unset test.test5 false'
```
(DeluxeMenu)

**Log:** 

https://pastebin.com/TswLeLxF

**Comment by Turbotailz** [comment] 2021-03-20 13:41
What is your discord name?

**Comment by Feldmarschall** [comment] 2021-03-20 13:47
Sir William, the post was not long ago. 12:44 :)

But in this issure are more details.

**Comment by lucko** [comment] 2021-03-20 15:29
The logs just indicate that your server is struggling to keep up with LuckPerms command executions (they happen one after the other in the order in which they were executed)

I assume the commands do eventually go through?

Are you able to reliably reproduce the problem?

**Comment by Feldmarschall** [comment] 2021-03-20 15:57
The problem is that no player can join the server when the problem occurs.
I always have to restart the server. The following commands (luckPerm changes) are not saved.

Yes, whenever my player group changes their race. Then many permissions are changed. 

As far as I know, this happens with the latest 3.5.0 version. I will patch back today or tomorrow.

**Comment by lucko** [comment] 2021-03-20 16:09
> The problem is that no player can join the server when the problem occurs.

This would indicate that the problem is probably more significant than just LuckPerms.. the LP command queue getting stuck is one thing, but that wouldn't (shouldn't) prevent players from connecting to the server.

More likely you have a thread / CPU starvation problem which is resulting in the server not responding.

**Comment by Feldmarschall** [comment] 2021-03-21 10:34
I don't know exactly. In any case, I patched the old version. Now everything works again. (LuckPerm 5.2.76)

The 20 commands are executed instantaneously without the server getting problems.

**Comment by lucko** [comment] 2021-03-21 10:56
Could you try using 5.3.11 - https://luckperms.net/download

Let me know if that is any better, I've added a patch that may improve the situation :)

**Comment by Feldmarschall** [comment] 2021-03-22 23:24
It doesn't work with the version either.

**Comment by Feldmarschall** [comment] 2021-03-22 23:26
```
[00:21:46 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.volk.halblinge] has not completed. Trace: 
  java.base@11.0.10/jdk.internal.misc.Unsafe.park(Native Method)
  java.base@11.0.10/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
  java.base@11.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
  java.base@11.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:917)
  java.base@11.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1240)
  java.base@11.0.10/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:267)
  me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:148)
  me.lucko.luckperms.common.command.CommandManager$$Lambda$8715/0x00000008421bb840.get(Unknown Source)
  java.base@11.0.10/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
  java.base@11.0.10/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
  java.base@11.0.10/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
  java.base@11.0.10/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
  java.base@11.0.10/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
  java.base@11.0.10/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
  java.base@11.0.10/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[00:21:46 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.volk.nord] has not completed. Trace: 
  java.base@11.0.10/jdk.internal.misc.Unsafe.park(Native Method)
  java.base@11.0.10/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
  java.base@11.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
  java.base@11.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:917)
  java.base@11.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1240)
  java.base@11.0.10/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:267)
  me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:148)
  me.lucko.luckperms.common.command.CommandManager$$Lambda$8715/0x00000008421bb840.get(Unknown Source)
  java.base@11.0.10/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
  java.base@11.0.10/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
  java.base@11.0.10/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
  java.base@11.0.10/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
  java.base@11.0.10/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
  java.base@11.0.10/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
  java.base@11.0.10/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[00:21:46 INFO]: [LP] Another command is being executed, waiting for it to finish...
[00:21:46 INFO]: [LP] Another command is being executed, waiting for it to finish...
[00:21:56 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.volk.sturmmänner] has not completed. Trace: 
  java.base@11.0.10/jdk.internal.misc.Unsafe.park(Native Method)
  java.base@11.0.10/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
  java.base@11.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
  java.base@11.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:917)
  java.base@11.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1240)
  java.base@11.0.10/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:267)
  me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:148)
  me.lucko.luckperms.common.command.CommandManager$$Lambda$8715/0x00000008421bb840.get(Unknown Source)
  java.base@11.0.10/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
  java.base@11.0.10/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
  java.base@11.0.10/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
  java.base@11.0.10/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
  java.base@11.0.10/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
  java.base@11.0.10/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
  java.base@11.0.10/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[00:21:56 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.volk.aishuri] has not completed. Trace: 
  java.base@11.0.10/jdk.internal.misc.Unsafe.park(Native Method)
  java.base@11.0.10/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
  java.base@11.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
  java.base@11.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:917)
  java.base@11.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1240)
  java.base@11.0.10/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:267)
  me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:148)
  me.lucko.luckperms.common.command.CommandManager$$Lambda$8715/0x00000008421bb840.get(Unknown Source)
  java.base@11.0.10/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
  java.base@11.0.10/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
  java.base@11.0.10/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
  java.base@11.0.10/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
  java.base@11.0.10/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
  java.base@11.0.10/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
  java.base@11.0.10/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[00:21:56 INFO]: [LP] Another command is being executed, waiting for it to finish...
```

**Comment by lucko** [comment] 2021-03-23 00:47
Can you upload your full log?

**Comment by Feldmarschall** [comment] 2021-03-23 09:17
https://pastebin.com/paKuDyku

**Comment by lucko** [comment] 2021-03-23 11:10
Ah ok, I think I see what the problem is.

Could you try again using v5.3.12 :)

**Comment by Feldmarschall** [comment] 2021-03-24 09:01
Now it works, but there is still an error.

`[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] adurien already has adurath.volk.elfen set in context global.
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:29 INFO]: [LP] Another command is being executed, waiting for it to finish...
[09:59:34 INFO]: Akiraya issued server command: /spawn
[09:59:36 INFO]: Fabyskan neue Bilanz: 360,63
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, set, adurath.völkerwahl.sonnenfeuerelfen, false] has not completed - is another command execution blocking it?
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.völkerwahl.lordanier, false] has not completed - is another command execution blocking it?
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.völkerwahl.sturmmänner, false] has not completed - is another command execution blocking it?
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.völkerwahl.aishuri, false] has not completed - is another command execution blocking it?
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.völkerwahl.khalpatenier, false] has not completed - is another command execution blocking it?
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.völkerwahl.vestani, false] has not completed - is another command execution blocking it?
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.völkerwahl.waidländer, false] has not completed - is another command execution blocking it?
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.völkerwahl.stolzfußen, false] has not completed - is another command execution blocking it?
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, set, adurath.volk.sonnenfeuerelfen] has not completed. Trace: 
  java.base@11.0.10/jdk.internal.misc.Unsafe.park(Native Method)
  java.base@11.0.10/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
  java.base@11.0.10/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1796)
  java.base@11.0.10/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
  java.base@11.0.10/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1823)
  java.base@11.0.10/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2043)
  me.lucko.luckperms.common.commands.user.UserParentCommand.getTarget(UserParentCommand.java:114)
  me.lucko.luckperms.common.commands.user.UserParentCommand.getTarget(UserParentCommand.java:55)
  me.lucko.luckperms.common.command.abstraction.ParentCommand.execute(ParentCommand.java:102)
  me.lucko.luckperms.common.command.abstraction.ParentCommand.execute(ParentCommand.java:45)
  me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:260)
  me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:166)
  me.lucko.luckperms.common.command.CommandManager$$Lambda$8610/0x00000008423fa040.get(Unknown Source)
  java.base@11.0.10/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
  java.base@11.0.10/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  java.base@11.0.10/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  java.base@11.0.10/java.lang.Thread.run(Thread.java:834)
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.völkerwahl.bugans, false] has not completed - is another command execution blocking it?
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.völkerwahl.breitohren, false] has not completed - is another command execution blocking it?
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.völkerwahl.mondelfen, false] has not completed - is another command execution blocking it?
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.völkerwahl.windelfen, false] has not completed - is another command execution blocking it?
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.völkerwahl.waldelfen, false] has not completed - is another command execution blocking it?
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.völkerwahl.schattenelfen, false] has not completed - is another command execution blocking it?
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.völkerwahl.klan_bjor, false] has not completed - is another command execution blocking it?
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.völkerwahl.klan_ravn, false] has not completed - is another command execution blocking it?
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.völkerwahl.klan_ulf, false] has not completed - is another command execution blocking it?
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.völkerwahl.langbärte, false] has not completed - is another command execution blocking it?
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.völkerwahl.eisenfäuste, false] has not completed - is another command execution blocking it?
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.völkerwahl.grimmbärte, false] has not completed - is another command execution blocking it?
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.volk.menschen] has not completed - is another command execution blocking it?
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.volk.halblinge] has not completed - is another command execution blocking it?
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.volk.nord] has not completed - is another command execution blocking it?
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.volk.zwerge] has not completed - is another command execution blocking it?
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.volk.lordanier] has not completed - is another command execution blocking it?
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.volk.aishuri] has not completed - is another command execution blocking it?
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.volk.khalpatenier] has not completed - is another command execution blocking it?
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.volk.sturmmänner] has not completed - is another command execution blocking it?
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.volk.vestani] has not completed - is another command execution blocking it?
[09:59:39 WARN]: [LuckPerms] Command execution [user, Adurien, permission, unset, adurath.volk.waidländer] has not completed - is another command execution blocking it?
[09:59:39 INFO]: [LP] Set adurath.volk.sonnenfeuerelfen to true for adurien in context global.
[09:59:39 INFO]: [LP] Set adurath.völkerwahl.sonnenfeuerelfen to false for adurien in context global.
[09:59:39 INFO]: [LP] adurien does not have adurath.völkerwahl.lordanier set in context server=false.
[09:59:39 INFO]: [LP] adurien does not have adurath.völkerwahl.aishuri set in context server=false.
[09:59:39 INFO]: [LP] adurien does not have adurath.völkerwahl.sturmmänner set in context server=false.
[09:59:39 INFO]: [LP] adurien does not have adurath.völkerwahl.khalpatenier set in context server=false.
[09:59:39 INFO]: [LP] adurien does not have adurath.völkerwahl.vestani set in context server=false.
[09:59:39 INFO]: [LP] adurien does not have adurath.völkerwahl.waidländer set in context server=false.
[09:59:39 INFO]: [LP] adurien does not have adurath.völkerwahl.stolzfußen set in context server=false.
[09:59:39 INFO]: [LP] adurien does not have adurath.völkerwahl.bugans set in context server=false.
[09:59:39 INFO]: [LP] adurien does not have adurath.völkerwahl.breitohren set in context server=false.
[09:59:39 INFO]: [LP] adurien does not have adurath.völkerwahl.mondelfen set in context server=false.
[09:59:39 INFO]: [LP] adurien does not have adurath.völkerwahl.windelfen set in context server=false.
[09:59:39 INFO]: [LP] adurien does not have adurath.völkerwahl.waldelfen set in context server=false.
[09:59:39 INFO]: [LP] adurien does not have adurath.völkerwahl.schattenelfen set in context server=false.
[09:59:39 INFO]: [LP] adurien does not have adurath.völkerwahl.klan_bjor set in context server=false.
[09:59:39 INFO]: [LP] adurien does not have adurath.völkerwahl.klan_ravn set in context server=false.
[09:59:39 INFO]: [LP] adurien does not have adurath.völkerwahl.klan_ulf set in context server=false.
[09:59:39 INFO]: [LP] adurien does not have adurath.völkerwahl.eisenfäuste set in context server=false.
[09:59:39 INFO]: [LP] adurien does not have adurath.völkerwahl.langbärte set in context server=false.
[09:59:39 INFO]: [LP] adurien does not have adurath.völkerwahl.grimmbärte set in context server=false.
[09:59:39 INFO]: [LP] adurien does not have adurath.volk.menschen set in context global.
[09:59:39 INFO]: [LP] adurien does not have adurath.volk.halblinge set in context global.
[09:59:39 INFO]: [LP] adurien does not have adurath.volk.nord set in context global.
[09:59:39 INFO]: [LP] adurien does not have adurath.volk.zwerge set in context global.
[09:59:39 INFO]: [LP] adurien does not have adurath.volk.lordanier set in context global.
[09:59:39 INFO]: [LP] adurien does not have adurath.volk.aishuri set in context global.
[09:59:39 INFO]: [LP] adurien does not have adurath.volk.sturmmänner set in context global.
[09:59:39 INFO]: [LP] adurien does not have adurath.volk.khalpatenier set in context global.
[09:59:39 INFO]: [LP] adurien does not have adurath.volk.vestani set in context global.
[09:59:39 INFO]: [LP] adurien does not have adurath.volk.waidländer set in context global.
[09:59:39 INFO]: [LP] adurien does not have adurath.volk.stolzfußen set in context global.
[09:59:39 INFO]: [LP] adurien does not have adurath.volk.bugans set in context global.
[09:59:39 INFO]: [LP] adurien does not have adurath.volk.breitohren set in context global.
[09:59:39 INFO]: [LP] adurien does not have adurath.volk.mondelfen set in context global.
[09:59:39 INFO]: [LP] adurien does not have adurath.volk.windelfen set in context global.
[09:59:39 INFO]: [LP] Unset adurath.volk.waldelfen for adurien in context global.
[09:59:39 INFO]: [LP] adurien does not have adurath.volk.schattenelfen set in context global.
[09:59:39 INFO]: [LP] adurien does not have adurath.volk.klan_ulf set in context global.
[09:59:39 INFO]: [LP] adurien does not have adurath.volk.klan_ravn set in context global.
[09:59:39 INFO]: [LP] adurien does not have adurath.volk.klan_bjor set in context global.
[09:59:39 INFO]: [LP] adurien does not have adurath.volk.eisenfäuste set in context global.
[09:59:39 INFO]: [LP] adurien does not have adurath.volk.langbärte set in context global.
[09:59:39 INFO]: [LP] adurien does not have adurath.volk.grimmbärte set in context global.`

**Comment by lucko** [comment] 2021-03-24 12:40
Alright, 3rd time lucky... please try with 5.3.14 :)

**Comment by Feldmarschall** [comment] 2021-03-25 23:36
Yes it works fine. Thanks. One more Question.

Is that still normal? In the past, this display did not come up, but immediately the output.

```
[00:34:06 INFO]: [LP] Another command is being executed, waiting for it to finish...
[00:34:06 INFO]: [LP] Another command is being executed, waiting for it to finish...
[00:34:06 INFO]: [LP] Another command is being executed, waiting for it to finish...
[00:34:06 INFO]: [LP] Another command is being executed, waiting for it to finish...
[00:34:06 INFO]: [LP] Another command is being executed, waiting for it to finish...
[00:34:06 INFO]: [LP] Another command is being executed, waiting for it to finish...
[00:34:06 INFO]: [LP] Another command is being executed, waiting for it to finish...
[00:34:06 INFO]: [LP] Another command is being executed, waiting for it to finish...
[00:34:06 INFO]: [LP] Another command is being executed, waiting for it to finish...
```

**Comment by lucko** [comment] 2021-03-26 09:54
Yes - that's normal.

Great that the issue is fixed!

A closing comment from me: ask yourself, is it necessary to run so many commands at once? If you are assigning lots of permissions to a user, it would be better to add those permissions to a group, then just execute one command to add the group to the user.

For example, if you want to routinely give permissions:

```
essentials.ban
essentials.mute
essentials.fly
```

to a user.

Instead of running

```
/lp user {USER} permission set essentials.ban true
/lp user {USER} permission set essentials.mute true
/lp user {USER} permission set essentials.fly true
```

*every* time, add these permissions to a group:

```
/lp group mygroup permission set essentials.ban true
/lp group mygroup permission set essentials.mute true
/lp group mygroup permission set essentials.fly true
```

then just add the user to the group (one command each time instead of 3!)

```
/lp user {USER} parent add mygroup
```

**Closed by lucko** 2021-03-26 09:54 UTC
Labels: type: issue
