### ISSUE TITLE
Set scope of permission info

### ISSUE THREAD

**Issue by Iwitrag** [lucko/LuckPerms#1618] opened 2019-07-12 09:53 UTC
Hi,

often I need to see which plugin permissions group or user has.

For example I want to show only assigned permissions related to WorldBorder plugin.

Currently I need to browse several pages of permission list.
I would really appreciate a posibility to pass an argument [scope] - the root of the permission lookup (specify . to include all permissions)

Example:

/lp group admin permission info 1 worldborder

Which would show only permissions like
worldborder.fill
worldborder.bypass

etc.

**Comment by lucko** [comment] 2019-07-14 08:56
Definitely a valid suggestion.

In the meantime, I suggest using the webeditor. It has the benefit of being able to use a full page, and therefore is not constrained to the Minecraft chat window. Therefore, doesn't really suffer from this issue! :)

**Comment by Iwitrag** [comment] 2019-07-14 09:00
Yeah but it's not really comfortable as I'm playing in fullscreen so I need to switch to browser everytime.
Maybe adding simple filter would help? Like print only those permissions, which contains substring given as parameter.

**Comment by lucko** [comment] 2019-12-02 20:30
Duplicate of #819 and #1794 1792

**Closed by lucko** 2019-12-02 20:30 UTC
Labels: type: suggestion
