### ISSUE TITLE
reduce the time of a luckperm temporary permission

### ISSUE THREAD

**Issue by Bricec6** [lucko/LuckPerms#1867] opened 2019-12-11 22:44 UTC
Hello
It is impossible to reduce the time of a temporary permission....
example:
> lp user Extazii permission settemp permission.temporaire true 2h hell
 [LP] Set permission.temporaire to true for extazii for a duration of 2 hours 1 second in context server=hell.

> lp user Extazii permission settemp permission.temporaire true -1h accumulate server=hell
[LP] Set permission.temporaire to true for extazii for a duration of 2 hours 59 minutes 18 seconds in context server=hell.

or

> lp user Extazii permission settemp permission.temporaire true -1h server=hell
[LP] extazii already has permission.temporaire set temporarily in context server=hell.

It is I think it is necessary to add this feature to add another + for luckperm, at least add the -Xh or 2h reduce server=hell

thankyou

**Comment by lucko** [comment] 2019-12-14 17:25
Duplicate of #1384

**Closed by lucko** 2019-12-14 17:25 UTC
