### ISSUE TITLE
BungeeCord MySQL Error

### ISSUE THREAD

**Issue by MCMDEV** [lucko/LuckPerms#1348] opened 2018-12-23 15:19 UTC
Im just setting up a small BungeeCord Network on my localhost using one spigot server and one bungeecord server. I have typed the MySQL information into both servers. When i create a database and start the proxy i get this error: 
https://pastebin.com/PsJAc5rX

Im using LuckPerms 4.3.60

**Comment by lucko** [comment] 2018-12-23 21:07
Seems to be related to this commit.

2cb5e437fd65200eefe9a39f418d94da6a14c167

I'm not really sure what to do to fix it though. Could revert I guess?

**Comment by SynPDX** [comment] 2018-12-23 21:49
I too have this same issue.... If database is empty, issue exists when new tables are generated. After tables are generated, upon a reboot of the server, the console will no longer show the severe issues. Shutting down server, then dropping all tables on DB, booting server back up will result in the issue surfacing again.

Also, I am experiencing this on the BungeeCord server (haven't tested this on main servers just yet).

**Comment by SynPDX** [comment] 2018-12-23 21:55
Lastly - I've confirmed this issue is not present on this version:

https://ci.lucko.me/view/LuckPerms/job/LuckPerms/829/

**Comment by lucko** [comment] 2018-12-23 21:58
Will hopefully be fixed by c4154c09da530f7bd2009f9d9670822acfc9c769

Would one of you guys mind dropping your DBs again and testing using the latest version?
https://ci.lucko.me/job/LuckPerms/839/

**Comment by SynPDX** [comment] 2018-12-23 22:07
Dropped my DB tables, tested with your latest version and the issue seems to be corrected. Here's the console output (no errors):

https://paste.md-5.net/nexederuqi.tex

**Comment by Poggicek** [comment] 2018-12-23 22:08
Well done u just wasted your 5 minutes :DD someone did it already

**Comment by BrainStone** [comment] 2018-12-24 00:50
Are there any where clauses for the permission column? Because if so there definitely should be an index.  
I think a fulltext Index could work here.

**Comment by lucko** [comment] 2018-12-25 10:18
There are some lookups by permission, but they are only for the `/lp search`, `/lp group <g> listmembers` and bulkupdate commands.

Not really worth having an index for imo.

**Comment by lucko** [comment] 2018-12-25 10:19
Anyway, seems to be fixed, so will close. :)

**Closed by lucko** 2018-12-25 10:19 UTC
Labels: type: issue
