### ISSUE TITLE
OP with WorldGuard

### ISSUE THREAD

**Issue by Guest1131** [lucko/LuckPerms#1403] opened 2019-01-27 16:56 UTC
Hey,

I found a bug on LuckPerms with WorldGuard.

In the LuckPerms config.yml, I activated the "auto-op: true".
Which allows you to automatically assign OPs to a group or user, which receives permission "luckperms.autoop", and so far everything ok.

In WorldGuard in the config.yml I set "op-permission: false", which also allows who and OP, not to have WorldGuard permissions.

But the bug is not working, if luckperms and on the server, as soon as I removed the plugin luckperms, WorldGuard also blocks OP, if the plugin LuckPerms and on the server, WorldGuard no longer blocks OP.

I contacted the developer of WorldGuard, and he told me that the problem could be in luckperms, which could assign * instead of OP.

How can I fix it?

**Comment by lucko** [comment] 2019-01-28 11:03
Going to try to reproduce

**Comment by Guest1131** [comment] 2019-01-28 11:15
I use WorldGuard 7 on spigot 1.13.2, but I do not think this makes the difference.
It is a problem of LuckPerms not of WorldGuard.

Because if I remove the LuckPerms plugin, Worldguard blocks OP, if the option op-permission: false.
If instead of luckperms and on the server, WorldGuard no longer blocks OP.

**Comment by lucko** [comment] 2019-01-30 16:53
I think you're getting the WorldGuard `op-permission` option confused with `deop-everyone-on-join` and `block-in-game-op-command`.

The `op-permission` setting, when set to true, will allow server operators access to WorldGuard even if they don't have the permission for it - when it's false, the system just works as normal with permissions - if they have the perm, they can use the command, otherwise they can't.

**Comment by Guest1131** [comment] 2019-01-30 20:50
That's not the problem.

Op-permission: false, only works if I remove luckperms from the server.

So the problem is in luckperms.

And I have not * on worldguard

Can't you fix it?

**Comment by lucko** [comment] 2019-01-30 20:52
Try setting `worldguard.*` to false for your admin users.

**Comment by Guest1131** [comment] 2019-01-30 21:07
I speak of the op, not of groups. I can not add permissions to the OP

**Comment by Guest1131** [comment] 2019-01-30 21:09
It seems that Luckperms, sees OP as *

**Comment by Guest1131** [comment] 2019-01-30 21:13
I don't want OPs, has WorldGuard permits, for security reasons

**Comment by Andre601** [comment] 2019-01-30 21:14
Then do what Luck suggested and deny `worldguard.*`

**Comment by Guest1131** [comment] 2019-01-30 23:02
There's no point in denying permission.

How do I deny WorldGuard.* to the OP?

You can only deny on a group or player, not on OP.

**Comment by lucko** [comment] 2019-01-30 23:02
> I don't want OPs, has WorldGuard permission, for security reasons

That's fine, but simply setting `op-permissions` to false won't do that. By default, Bukkit gives operators access to all permissions - which is what's happening here.

> How do I deny WorldGuard.* to the OP?
You can only deny on a group or player, not on OP.

Just deny it for all players (the default group)

**Comment by Guest1131** [comment] 2019-01-30 23:20
Yes, but as I have already told you, it only happens if LuckPerms is installed, if no luckperms is not installed, OP and locked by op-permission: false

**Comment by lucko** [comment] 2019-01-31 00:02
Ok I see the issue, seems to be related to LP's implementation of the isPermissionSet method.

**Comment by lucko** [comment] 2019-01-31 01:19
My testing shows this as being fixed in `4.3.87` - https://luckperms.github.io/

Thanks for reporting the issue, please re-open if it's still not fixed. :)

**Closed by lucko** 2019-01-31 01:19 UTC
Labels: type: issue

**Comment by Guest1131** [comment] 2019-01-31 08:57
Okay, thank you very much :)
