### ISSUE TITLE
Im in need of help. Console spam for life!

### ISSUE THREAD

**Issue by Duqino** [lucko/LuckPerms#1219] opened 2018-09-19 14:28 UTC
Hello,

I dont know which plugin is causing it (bungeetablist or luckperms) so im placing my problem on both sites.

https://pastebin.com/XmCuasgm
https://pastebin.com/1m4cRFgR

Almost full error list:

https://pastebin.com/cDJhNhTB

Help!

Kind regards,

Duqino.

**Comment by codingJWilliams** [comment] 2018-09-19 15:47
As far as I can tell, that's a BungeeTabList error. If an error happens during a permission check luckperms prints it out, even if it isn't a luckperms error. That's why you have the word luckperms mixed in there :)

**Comment by codingJWilliams** [comment] 2018-09-19 15:48
Wait scratch that, there's also an error with LP

**Comment by codingJWilliams** [comment] 2018-09-19 15:49
@Duqino, could you please update to the latest version of LP and try again :)

**Comment by Duqino** [comment] 2018-09-19 16:12
I did that already. Im running jenkins version. Joined discord today and join message said it so i did :)

**Comment by Duqino** [comment] 2018-09-19 17:34
In the first pastebin are both bungeetablist and luckperms. Bungeetablist is shown first, that means bungeetablist is causing the problem?

**Comment by lucko** [comment] 2018-09-19 21:27
This is a LuckPerms issue, duplicate of #1212 

I'm planning to look into it a bit more tomorrow. :)

**Comment by lucko** [comment] 2018-09-19 21:28
Please use the other ticket to track progress

**Closed** 2018-09-19 21:28 UTC
Labels: resolution: duplicate, type: issue
