### ISSUE TITLE
lp permissions data could not be load

### ISSUE THREAD

**Issue by kohjoz** [lucko/LuckPerms#815] opened 2018-03-07 22:05 UTC
im getting this error all the time.. i reinstall it sometimes but it still doesnt work

![problem](https://user-images.githubusercontent.com/37160429/37120882-f1ce5118-225b-11e8-83e8-92a4cd26c197.png)

**Comment by lucko** [comment] 2018-03-07 22:14
Please upload a copy of your servers most recent log file to https://gist.github.com/ and reply with the link.

**Comment by kohjoz** [comment] 2018-03-07 22:21
https://gist.github.com/kohjoz/a05e84adf0a52dc55f204953473b03c6

**Comment by lucko** [comment] 2018-03-07 22:40
```
java.lang.NoClassDefFoundError: java/sql/Driver
```

Your server seems to be missing the JDBC drivers.

**Comment by lucko** [comment] 2018-03-07 22:41
Duplicate of https://github.com/lucko/LuckPerms/issues/779 ??

**Comment by kohjoz** [comment] 2018-03-07 22:56
well i also have it on my paied servers..

**Comment by kohjoz** [comment] 2018-03-08 00:25
Thank you for your answer ;) here is the log https://gist.github.com/kohjoz/c1b666b89e6eea8c4d0928c1a6e09161

**Comment by Neshram** [comment] 2018-03-08 15:58
I need to report I am seeing the same type of issues. For the sake of simplicity I set up a server instance with just LuckPerms, which is still getting error, and have Gist'd the logs below. The only settings I have (knowingly) changed from default are "eula=true", the server port to 25599 to avoid conflicts, and LuckPerms' storage engine for the second run. (The first was H2. The second was an unconfigured MySQL run as you suggested to Kohjoz.)

H2: https://gist.github.com/Neshram/787c7ccc5641aa5c574373ccff0c26de
MySQL: https://gist.github.com/Neshram/46933f8858787bdb8fa2abac7c3e36d2

**Comment by lucko** [comment] 2018-03-08 18:37
Yeah, I've done some more testing. Seems this issue only occurs on Java 9, which explains why it hasn't been reported too frequently. :)

I'm guessing that the user in #779 was also using J9 - although they said they weren't.

Should be fixed by the above commit
https://ci.lucko.me/job/LuckPerms/

**Closed by lucko** 2018-03-08 18:37 UTC
Labels: issue

**Comment by Neshram** [comment] 2018-03-08 19:50
Confirmed. That solved it for me. Thank you, very much.
