### ISSUE TITLE
Auto-completing permissions not working

### ISSUE THREAD

**Issue by david4444** [lucko/LuckPerms#1268] opened 2018-10-16 12:07 UTC
Hello,
recently auto-completing permission has stopped working.
I don't know why, but i've seen some people address auto-complete problems before like you can't auto-complete users.
I am on the latest 1.13.1 build, bungeecord with luckperms server side and proxy side.

**Comment by BrainStone** [comment] 2018-10-16 14:01
I’ve had several users complain that somewhere between the 4.2 and 4.3 builds it stopped working on 1.13.1.

**Comment by david4444** [comment] 2018-10-16 17:30
I checked, it started on 4.3. exactly when you added the brigadier which is the only thing that shows up now.

**Comment by lucko** [comment] 2018-10-18 13:19
Duplicate of #1257

**Closed by lucko** 2018-10-18 13:19 UTC
