### ISSUE TITLE
Unable to communicate with the editor

### ISSUE THREAD

**Issue by ky678** [lucko/LuckPerms#3158] opened 2021-09-08 09:36 UTC
### Description

When "/luckperms editor" is used, the link does not appear and instead "Unable to communicate with the editor" appears

### Reproduction steps

3. Run /luckperms editor from the console or gamechat

### Expected behaviour

The editor session link will appear in the chat

### Environment details

* Server type/version: `paper` running version `1.17.1` build `255`
* LuckPerms version: `v5.3.65`

[17:34:16 WARN]: [LuckPerms] Command execution [editor] has not completed. Trace:
  java.base@16.0.2/sun.nio.ch.Net.poll(Native Method)
  java.base@16.0.2/sun.nio.ch.NioSocketImpl.park(NioSocketImpl.java:181)
  java.base@16.0.2/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:548)
  java.base@16.0.2/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
  java.base@16.0.2/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
  java.base@16.0.2/java.net.Socket.connect(Socket.java:645)
  me.lucko.luckperms.lib.okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
  me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
  me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
  me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
  me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81)
  me.lucko.luckperms.common.http.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47)
  me.lucko.luckperms.common.http.BytebinClient.makeHttpRequest(BytebinClient.java:78)
  me.lucko.luckperms.common.http.BytebinClient.postContent(BytebinClient.java:98)
  me.lucko.luckperms.common.webeditor.WebEditorRequest.createSession(WebEditorRequest.java:174)
  me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:111)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:56)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:48)
  me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:263)
  me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:167)
  me.lucko.luckperms.common.command.CommandManager$$Lambda$5374/0x0000000801aff5c0.run(Unknown Source)
  java.base@16.0.2/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
  java.base@16.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
  java.base@16.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
  java.base@16.0.2/java.lang.Thread.run(Thread.java:831)

**Comment by Turbotailz** [comment] 2021-09-08 09:38
There really is no need to open a duplicate issue, when you just commented on #3157

**Comment by Turbotailz** [comment] 2021-09-08 09:40
Duplicate of #3157

**Closed** 2021-09-08 09:47 UTC
Labels: type: issue
