### ISSUE TITLE
Prefix & Suffix Stacking

### ISSUE THREAD

**Issue by ItzAntony** [lucko/LuckPerms#930] opened 2018-04-22 16:31 UTC
Two prefixes are being pulled from one track even though I have it set to "highest_on_track_<name>" (Obviously I added my track names :D)

Config (Prefix stacking part) https://pastebin.com/CssJXUGQ

![36ff539f7a840466398f1cd513390ff9](https://user-images.githubusercontent.com/20343506/39097345-f69a968c-4652-11e8-8b07-e9b13a80beb7.png)
![a418447724432132836bea410d9d47b2](https://user-images.githubusercontent.com/20343506/39097346-f6b1520a-4652-11e8-94dc-6ab32d936793.png)

A couple of examples. Staff and build rank prefixes are in the same track. So, I've no idea why it's grabbing both the builder rank and staff rank. The donator rank is in a different track called vanilla.

**Comment by lucko** [comment] 2018-04-22 19:59
Can you show screenshots of your tracks, and the groups the users inherit from

**Comment by ItzAntony** [comment] 2018-04-22 22:12
With the ranks, they each inherit from each other. e.g Titan would inherit the permissions of Elite, or Moderator would inherit the permissions of Helper.

![ac2a14d6071e01383844bd483a66fa3a](https://user-images.githubusercontent.com/20343506/39100436-81ea6a94-4682-11e8-816c-d5e270294d12.png)
![b64e0d5d3007a3ada3f2ce1c152da24e](https://user-images.githubusercontent.com/20343506/39100437-8220b8ce-4682-11e8-992f-c6ccc263130c.png)

**Comment by lucko** [comment] 2018-04-23 20:25
Okay, and 

> the groups the users inherit from 

??

You're leaving me to guess what the problem is at the moment. 

I need a description of your current setup, along with what you think the issue is, and what you expect to happen / be shown instead of what's happening at the moment.

Everything you've shown so far looks fine to me.

**Comment by ItzAntony** [comment] 2018-04-23 20:33
User inherits from the default, novice inherits from the user and so on. It just goes up the list. The thing is, I have 2 tracks. One donator and one for ranks. Now, the issue is, **two** ranks are being pulled from the **same** track. This should not be the case since I have it set to **highest_on_track_ranks**. It should only be grabbing the highest prefix. Eg. if someone was architect, titan and mod, they should only be given the rank Titan and Mod since titan is the highest one they have on the vanilla track and then mod since its the highest on the ranks track.

**Comment by lucko** [comment] 2018-04-23 20:35
Does the correct value show for these players when you run `/lp user <user> info`?

**Comment by ItzAntony** [comment] 2018-04-23 20:38
![e268ee26c9eca3da4427b70f20b4aadf](https://user-images.githubusercontent.com/20343506/39151918-8964f57a-473e-11e8-80cc-834ac3223b98.png)

This is an example of someone who is staff, donator and has a build rank. But, they should only have the donator prefix and staff prefix displayed due to it being set to highest on those tracks.

**Comment by lucko** [comment] 2018-04-23 20:40
Can you try running it when they're logged in

**Comment by ItzAntony** [comment] 2018-04-23 20:43
![96ab96641733c1249b8fff6da758680d](https://user-images.githubusercontent.com/20343506/39152158-4ba52236-473f-11e8-926c-d97a47c4bc7f.png)

**Comment by lucko** [comment] 2018-04-23 20:45
So, is that correct?

**Comment by ItzAntony** [comment] 2018-04-23 20:45
Well yes... They are in all the correct groups. But the way its being displayed in chat is not.

**Comment by ItzAntony** [comment] 2018-04-27 14:08
Yea, the prefix should be [MEGA] [Admin] or basically (Donator) (Staff)

This is the output given with the user online.
![620f21373385f44422d9dcb49888bbf5](https://user-images.githubusercontent.com/20343506/39366772-cf33f16e-4a2c-11e8-8683-68aa05b77884.png)

**Comment by lucko** [comment] 2018-05-03 16:26
You seem to be using an old(ish) version of LuckPerms, can you try updating?

The issue with the debug command has definitely been fixed already. You can grab the latest version here:
https://luckperms.github.io/


(sorry for not replying - it's hard to keep with with notifications. feel free to ping me in future if I miss things :p )

**Comment by ItzAntony** [comment] 2018-05-06 10:55
Hey, @lucko I tried updating and once I restarted my server luckperms decided to disable itself every time. I've tried a couple of the new versions and the same thing happened. I had to revert back to the version I had before and then it worked again. This is what came up in my console once I updated. https://pastebin.com/MJD9ACtg

**Comment by ItzAntony** [comment] 2018-05-06 11:27
It seems that all I had to do was break the plugin and then add an old one back.. lmao. This fixed my issue with staff prefixes displaying their builder rank haha

**Comment by lucko** [comment] 2018-05-06 14:58
Should be fixed by ^

**Comment by ItzAntony** [comment] 2018-05-06 16:31
https://hastebin.com/raw/xupujukece - /lp debug

**Comment by lucko** [comment] 2018-05-06 16:33
Can you give me the name of a player included in that output who doesn't have the correct prefix listed?

**Comment by ItzAntony** [comment] 2018-05-06 16:35
Crud haha, forgot about the player being online. Here is the debug with the user online. https://hastebin.com/raw/warovujimi The players username is Luci_MC

**Comment by lucko** [comment] 2018-05-06 17:07
It seems they aren't even inheriting the meta prefix, what's `server` set to here?

**Comment by ItzAntony** [comment] 2018-05-06 17:08
Creative, that is the server the chat is on.

**Comment by lucko** [comment] 2018-05-06 17:10
They only inherit from `mega` on `server=vanilla` - meaning that prefix won't be displayed on creative.

I don't see what the problem is?

**Comment by ItzAntony** [comment] 2018-05-06 17:10
Vanilla is our bungee for vanilla. Meaning both our skyblock and creative.

**Comment by lucko** [comment] 2018-05-06 17:11
Yes, but the bungee contexts won't apply to the backend server.

**Comment by lucko** [comment] 2018-05-06 17:11
see: https://github.com/lucko/LuckPerms/wiki/Context

**Comment by ItzAntony** [comment] 2018-05-06 17:12
![1a73a4ea997054da91c4c2bf7c19e8a7](https://user-images.githubusercontent.com/20343506/39675848-e3c7a1ba-5158-11e8-85e4-cd9e5fd94f16.png)
This is their current displayed chat. Everything works great besides that builder tag being displayed. So, just making it go to server=creative should fix it?

**Comment by lucko** [comment] 2018-05-06 17:26
Hard for me to comment on that without knowing how each of those groups are inherited and how your tracks are setup.

The debug log confirms that this isn't a bug, rather a configuration issue, so I'll close the "issue".

I'm happy to help you sort the configuration, but it's probably easier to do that in Discord or something like that. (also happy to help here if you post the necessary info)

**Closed by lucko** 2018-05-06 17:26 UTC
Labels: status: need more info, type: question
