### ISSUE TITLE
Sponge style wildcard option for other plugins

### ISSUE THREAD

**Issue by BrainStone** [lucko/LuckPerms#2237] opened 2020-04-27 21:52 UTC
It would be a nice addition if other server platforms could optionally turn on Sponge sytle wildcards. That is useful if you want the permissions to be consistent on networks that use Sponge with other server platforms (like BungeeCord).

**Comment by lucko** [comment] 2020-04-27 22:14
Ok ok, I get it.. :wink: (duplicate of #1625)

**Closed by lucko** 2020-04-27 22:14 UTC

**Comment by BrainStone** [comment] 2020-04-27 22:19
xD Totally forgot I had it open already.
