### ISSUE TITLE
LP 5.0.5.7  Issue related to the MongoDB implementation

### ISSUE THREAD

**Issue by TMCGH** [lucko/LuckPerms#2110] opened 2020-03-27 21:54 UTC
Originally had an entire bungee mock network running properly, LPB vzn 4.4.22 and LP 5.0.5.7 on the servers..

started randomly running into "Failed to connect to server" when attempting to connect to the network with no errors in my bungee,hub, or server console whenever LPB was enabled so I got temporarily disabled the bungee / hub system and turned my main server into a direct connection , online-mode:true and bungeecord:false and am now getting this error in console. (LP on the server itself was still enabled)

http://prntscr.com/ro2ikj

**Comment by TMCGH** [comment] 2020-03-27 21:54
Tried updating to latest LP spigot, but it did not help. Could there be some sort of confliction or something in the DB?

**Comment by BrainStone** [comment] 2020-03-27 22:26
No. It's an implementation issue related to the MongoDB implementation (which you should put in the title).

**Comment by TMCGH** [comment] 2020-03-28 03:34
UPDATE:
After disabling LPB 4.4.22 I no longer received the "Failed to connect to server" error that sent no error to any console. 

I now am seeing my player attempt to get connected to the default fallback server, but was then greeted by the same UUID error denying their join. http://prntscr.com/ro6je1

**Comment by Andre601** [comment] 2020-03-28 09:04
When LuckPermsBungee is the cause, then the errors should be in the bungee console.

**Comment by TMCGH** [comment] 2020-03-28 16:56
@Andre601 The reason I made the ticket was that I was receiving "Failed to connect to server" without any errors on the console while LuckpermsBungee was enabled. 

The actual UUID error in console (screenshot) only happened when Luckperms Spigot was enabled.

**Comment by BrainStone** [comment] 2020-03-29 22:39
I mean the error is a cleary bug in the MongoDB implementation. And that's what I asked them to create this issue for.  
Btw it's 5.0.57 ;)

**Comment by TMCGH** [comment] 2020-04-04 08:44
Is this problem I'm running into related to LuckPerms or is it being caused on our side? Our servers core depends on LP, once LP was removed players were able to connect (core was not loaded since LP was not active)

**Comment by BrainStone** [comment] 2020-04-04 08:46
I’m 95% sure this is a bug in LP.

**Comment by lucko** [comment] 2020-04-05 15:42
Thanks for reporting, this will hopefully be fixed by the above commit.

**Closed by lucko** 2020-04-05 15:42 UTC
Labels: type: issue
