### ISSUE TITLE
Problem with luckperms

### ISSUE THREAD

**Issue by Ghastty** [lucko/LuckPerms#2067] opened 2020-03-15 22:15 UTC
Hello,I have a problem with this plugin.
When I added this plugin to my server, this started to showing in my console 
 
[LuckPerms] Disabling LuckPerms v5.0.72
>[2K [20:21:12 INFO]: [LuckPerms] Starting shutdown process...
>[2K [20:21:12 INFO]: [LuckPerms] Closing storage...
>[2K [20:21:12 INFO]: [LuckPerms] Goodbye!

When I tried to join I have this message 

io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information:

Please help,I tried turning off my firewall, updating java, delete almost every plugin
I don't know what to do... :(

(Sorry for my english)

**Comment by lucko** [comment] 2020-03-19 11:32
Can you show your full server log?

Seems like something is shutting down your server as soon as it enables - but it's not LP doing it.

**Comment by Lukas1921** [comment] 2020-03-19 12:18
> Can you show your full server log?
> Seems like something is shutting down your server as soon as it enables - but it's not LP doing it.

Hello. 
I have the same problem when I installed this plugin.

My full server log.

[CSRV] Changing working dir...
[CSRV] Scanning for network conflicts... ['127.0.0.1:41807', '176.9.2.107:41807', '127.0.0.1:0']
[CSRV] Setting kernel resource limits
[CSRV] Switching to unprivileged server user
[CSRV] Executing Java...
Loading libraries, please wait...
[13:16:03 INFO]: Starting minecraft server version 1.8.8
[13:16:03 INFO]: Loading properties
[13:16:03 INFO]: Default game type: SURVIVAL
[13:16:03 INFO]: This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[13:16:03 INFO]: Debug logging is disabled
[13:16:03 INFO]: Server Ping Player Sample Count: 12
[13:16:03 INFO]: Using 4 threads for Netty based IO
[13:16:03 INFO]: Generating keypair
[13:16:03 INFO]: Starting Minecraft server on 127.0.0.1:41807
[13:16:03 INFO]: Using epoll channel type
[13:16:03 INFO]: Set PluginClassLoader as parallel capable
[13:16:04 ERROR]: Could not load 'plugins/CombatTag (1).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/World
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/World
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.World
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	... 6 more
[13:16:04 INFO]: [MotdManager] Loading MotdManager v1.41-b20
[13:16:04 INFO]: [LuckPerms] Loading LuckPerms v5.0.97
[13:16:04 INFO]: [WorldEdit] Loading WorldEdit v6.1;no_git_id
[13:16:04 INFO]: [HealthBar] Loading HealthBar v1.8.3
[13:16:04 INFO]: [CraftserveAgent] Loading CraftserveAgent v20200313-1954
[13:16:04 INFO]: [OpenInv] Loading OpenInv v4.0.8
[13:16:04 INFO]: [HeadSpawner] Loading HeadSpawner v1.5.0
[13:16:04 INFO]: [CombatLog] Loading CombatLog v2.3.0
[13:16:04 INFO]: [ClearLag] Loading ClearLag v3.1.6
[13:16:04 INFO]: [AutoMessage] Loading AutoMessage v2.5.5
[13:16:04 INFO]: [Reservations] Loading Reservations v2.5.1
[13:16:04 INFO]: [Multiverse-Core] Loading Multiverse-Core v2.5-b699
[13:16:04 INFO]: [NoCheatPlus] Loading NoCheatPlus v3.16.0-RC-sMD5NET-b1134
[13:16:04 INFO]: [NoCheatPlus] onLoad: Early set up of static API, configuration, logging.
[13:16:04 INFO]: [NoCheatPlus] Logging system initialized.
[13:16:04 INFO]: [NoCheatPlus] Detected Minecraft version: 1.8.8
[13:16:04 INFO]: [Vault] Loading Vault v1.5.6-b49
[13:16:04 INFO]: [CommandBook] Loading CommandBook v2.4:1692-75bb1c8,master
[13:16:04 INFO]: [Essentials] Loading Essentials v2.17.2.0
[13:16:04 INFO]: [Rankup] Loading Rankup v1.3
[13:16:04 INFO]: [AuthMe] Loading AuthMe v5.6.0-beta1-b2226
[13:16:04 INFO]: [WorldGuard] Loading WorldGuard v6.1
[13:16:04 INFO]: [TreasureChest] Loading TreasureChest v8.4.5
[13:16:04 INFO]: [SimpleClans] Loading SimpleClans v2.5.3
[13:16:04 INFO]: [BattleKits] Loading BattleKits v2.0.3
[13:16:04 INFO]: [RealisticBackpacks] Loading RealisticBackpacks v1.6.4
[13:16:04 INFO]: [KillMoney] Loading KillMoney v2.4
[13:16:04 INFO]: [EssentialsChat] Loading EssentialsChat vPre2.14.1.3
[13:16:04 INFO]: [DeathChest] Loading DeathChest v1.13.3
[13:16:04 INFO]: [PlayerVaults] Loading PlayerVaults v3.5.7-b${BUILD_NUMBER}
[13:16:04 INFO]: [CustomEnchantments] Loading CustomEnchantments v2.4c
[13:16:04 INFO]: [ChestShop] Loading ChestShop v3.9.0 (build #52)
[13:16:04 INFO]: [Smileychat] Loading Smileychat v3.1
[13:16:04 INFO]: [ScoreboardStats] Loading ScoreboardStats v0.10.5
[13:16:04 INFO]: [LuckPerms] Enabling LuckPerms v5.0.97
[13:16:04 INFO]: __ 
[13:16:04 INFO]: | |__) LuckPerms v5.0.97
[13:16:04 INFO]: |___ | Running on Bukkit - CraftBukkit
[13:16:04 INFO]: [LuckPerms] Loading configuration...
[13:16:04 INFO]: [LuckPerms] Loading storage provider... [H2]
[13:16:05 INFO]: [LuckPerms] Loading internal permission managers...
[13:16:05 INFO]: [LuckPerms] Performing initial data load...
[13:16:05 INFO]: [LuckPerms] Successfully enabled. (took 1023ms)
[13:16:05 INFO]: [CraftserveAgent] Enabling CraftserveAgent v20200313-1954
[13:16:05 WARN]: No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames
[13:16:05 WARN]: No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames
[13:16:05 INFO]: [Vault] Enabling Vault v1.5.6-b49
[13:16:05 INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[13:16:05 INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[13:16:05 INFO]: [Vault] Enabled Version 1.5.6-b49
[13:16:05 INFO]: [LuckPerms] Registered Vault permission & chat hook.
[13:16:05 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[13:16:05 WARN]: The server will make no attempt to authenticate usernames. Beware.
[13:16:05 WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[13:16:05 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[13:16:05 INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[13:16:05 INFO]: Preparing level "world"
[13:16:05 INFO]: -------- World Settings For [world] --------
[13:16:05 INFO]: Anti X-Ray: true
[13:16:05 INFO]: Engine Mode: 1
[13:16:05 INFO]: Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[13:16:05 INFO]: Replace Blocks: [1, 5]
[13:16:05 INFO]: Nerfing mobs spawned from spawners: false
[13:16:05 INFO]: Cactus Growth Modifier: 100%
[13:16:05 INFO]: Cane Growth Modifier: 100%
[13:16:05 INFO]: Melon Growth Modifier: 100%
[13:16:05 INFO]: Mushroom Growth Modifier: 100%
[13:16:05 INFO]: Pumpkin Growth Modifier: 100%
[13:16:05 INFO]: Sapling Growth Modifier: 100%
[13:16:05 INFO]: Wheat Growth Modifier: 100%
[13:16:05 INFO]: NetherWart Growth Modifier: 100%
[13:16:05 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[13:16:05 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[13:16:05 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[13:16:05 INFO]: Random Lighting Updates: false
[13:16:05 INFO]: Structure Info Saving: true
[13:16:05 INFO]: Sending up to 10 chunks per packet
[13:16:05 INFO]: Max Entity Collisions: 8
[13:16:05 INFO]: Custom Map Seeds: Village: 10387312 Feature: 14357617
[13:16:05 INFO]: Mob Spawn Range: 4
[13:16:05 INFO]: Max TNT Explosions: 100
[13:16:05 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[13:16:05 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[13:16:05 INFO]: Item Despawn Rate: 6000
[13:16:05 INFO]: Item Merge Radius: 2.5
[13:16:05 INFO]: Arrow Despawn Rate: 1200
[13:16:05 INFO]: View Distance: 10
[13:16:05 INFO]: Zombie Aggressive Towards Villager: true
[13:16:05 INFO]: Chunks to Grow per Tick: 650
[13:16:05 INFO]: Clear tick list: false
[13:16:05 INFO]: Experience Merge Radius: 3.0
[13:16:05 INFO]: -------- World Settings For [world_nether] --------
[13:16:05 INFO]: Anti X-Ray: true
[13:16:05 INFO]: Engine Mode: 1
[13:16:05 INFO]: Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[13:16:05 INFO]: Replace Blocks: [1, 5]
[13:16:05 INFO]: Nerfing mobs spawned from spawners: false
[13:16:05 INFO]: Cactus Growth Modifier: 100%
[13:16:05 INFO]: Cane Growth Modifier: 100%
[13:16:05 INFO]: Melon Growth Modifier: 100%
[13:16:05 INFO]: Mushroom Growth Modifier: 100%
[13:16:05 INFO]: Pumpkin Growth Modifier: 100%
[13:16:05 INFO]: Sapling Growth Modifier: 100%
[13:16:05 INFO]: Wheat Growth Modifier: 100%
[13:16:05 INFO]: NetherWart Growth Modifier: 100%
[13:16:05 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[13:16:05 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[13:16:05 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[13:16:05 INFO]: Random Lighting Updates: false
[13:16:05 INFO]: Structure Info Saving: true
[13:16:05 INFO]: Sending up to 10 chunks per packet
[13:16:05 INFO]: Max Entity Collisions: 8
[13:16:05 INFO]: Custom Map Seeds: Village: 10387312 Feature: 14357617
[13:16:05 INFO]: Mob Spawn Range: 4
[13:16:05 INFO]: Max TNT Explosions: 100
[13:16:05 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[13:16:05 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[13:16:05 INFO]: Item Despawn Rate: 6000
[13:16:05 INFO]: Item Merge Radius: 2.5
[13:16:05 INFO]: Arrow Despawn Rate: 1200
[13:16:05 INFO]: View Distance: 10
[13:16:05 INFO]: Zombie Aggressive Towards Villager: true
[13:16:05 INFO]: Chunks to Grow per Tick: 650
[13:16:05 INFO]: Clear tick list: false
[13:16:05 INFO]: Experience Merge Radius: 3.0
[13:16:05 INFO]: -------- World Settings For [world_the_end] --------
[13:16:05 INFO]: Anti X-Ray: true
[13:16:05 INFO]: Engine Mode: 1
[13:16:05 INFO]: Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[13:16:05 INFO]: Replace Blocks: [1, 5]
[13:16:05 INFO]: Nerfing mobs spawned from spawners: false
[13:16:05 INFO]: Cactus Growth Modifier: 100%
[13:16:05 INFO]: Cane Growth Modifier: 100%
[13:16:05 INFO]: Melon Growth Modifier: 100%
[13:16:05 INFO]: Mushroom Growth Modifier: 100%
[13:16:05 INFO]: Pumpkin Growth Modifier: 100%
[13:16:05 INFO]: Sapling Growth Modifier: 100%
[13:16:05 INFO]: Wheat Growth Modifier: 100%
[13:16:05 INFO]: NetherWart Growth Modifier: 100%
[13:16:05 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[13:16:05 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[13:16:05 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[13:16:05 INFO]: Random Lighting Updates: false
[13:16:05 INFO]: Structure Info Saving: true
[13:16:05 INFO]: Sending up to 10 chunks per packet
[13:16:05 INFO]: Max Entity Collisions: 8
[13:16:05 INFO]: Custom Map Seeds: Village: 10387312 Feature: 14357617
[13:16:05 INFO]: Mob Spawn Range: 4
[13:16:05 INFO]: Max TNT Explosions: 100
[13:16:05 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[13:16:05 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[13:16:05 INFO]: Item Despawn Rate: 6000
[13:16:05 INFO]: Item Merge Radius: 2.5
[13:16:05 INFO]: Arrow Despawn Rate: 1200
[13:16:05 INFO]: View Distance: 10
[13:16:05 INFO]: Zombie Aggressive Towards Villager: true
[13:16:05 INFO]: Chunks to Grow per Tick: 650
[13:16:05 INFO]: Clear tick list: false
[13:16:05 INFO]: Experience Merge Radius: 3.0
[13:16:05 INFO]: Preparing start region for level 0 (Seed: -4335714292168043376)
[13:16:06 INFO]: Preparing start region for level 1 (Seed: 3230009527372871039)
[13:16:06 INFO]: Preparing start region for level 2 (Seed: 3230009527372871039)
[13:16:06 INFO]: [MotdManager] Enabling MotdManager v1.41-b20
[13:16:06 INFO]: [MotdManager] version 1.41-b20 is enabled!
[13:16:06 INFO]: [WorldEdit] Enabling WorldEdit v6.1;no_git_id
[13:16:07 INFO]: WEPIF: Using the Bukkit Permissions API.
[13:16:07 INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_8_R3 as the Bukkit adapter
[13:16:07 INFO]: [HealthBar] Enabling HealthBar v1.8.3
[13:16:07 INFO]: [OpenInv] Enabling OpenInv v4.0.8
[13:16:07 INFO]: [HeadSpawner] Enabling HeadSpawner v1.5.0
[13:16:07 INFO]: [CombatLog] Enabling CombatLog v2.3.0
[13:16:07 INFO]: [CombatLog] WorldGuard plugin found! PvP regions are now detected.
[13:16:07 INFO]: [CombatLog] Loading config.yml
[13:16:07 INFO]: [CombatLog] v2.3.0 has been enabled.
[13:16:07 INFO]: [ClearLag] Enabling ClearLag v3.1.6
[13:16:08 INFO]: [ClearLag] Loading modules...
[13:16:08 INFO]: [ClearLag] Modules enabed, loading config values
[13:16:08 INFO]: [ClearLag] Modules have been loaded!
[13:16:08 INFO]: [ClearLag] Clearlag is now enabled!
[13:16:08 INFO]: [AutoMessage] Enabling AutoMessage v2.5.5
[13:16:08 INFO]: [ClearLag] Checking for updates compatible with your bukkit version [1.8]...
[13:16:08 INFO]: [Reservations] Enabling Reservations v2.5.1
[13:16:08 INFO]: [Reservations] is enabled!
[13:16:08 INFO]: [Multiverse-Core] Enabling Multiverse-Core v2.5-b699
[13:16:08 WARN]: [Multiverse-Core] WorldManager: Can't load this world because the folder was deleted/moved: Utopia_nether
[13:16:08 WARN]: [Multiverse-Core] Use '/mv remove' to remove it from the config!
[13:16:08 WARN]: [Multiverse-Core] WorldManager: Can't load this world because the folder was deleted/moved: Utopia
[13:16:08 WARN]: [Multiverse-Core] Use '/mv remove' to remove it from the config!
[13:16:08 WARN]: [Multiverse-Core] WorldManager: Can't load this world because the folder was deleted/moved: Utopia_the_end
[13:16:08 WARN]: [Multiverse-Core] Use '/mv remove' to remove it from the config!
[13:16:08 INFO]: [Multiverse-Core] 3 - World(s) loaded.
[13:16:08 INFO]: [Multiverse-Core] Version 2.5-b699 (API v19) Enabled - By Rigby, fernferret, lithium3141 and main--
[13:16:08 INFO]: [NoCheatPlus] Enabling NoCheatPlus v3.16.0-RC-sMD5NET-b1134
[13:16:08 INFO]: [ClearLag] No updates found!
[13:16:08 INFO]: [NoCheatPlus] McAccess set to: 1.8.4-1.8.8 / Spigot-CB-1.8_R3
[13:16:08 INFO]: [NoCheatPlus] Added block-info for Minecraft 1.5 blocks.
[13:16:08 INFO]: [NoCheatPlus] Added block-info for Minecraft 1.6.1 blocks.
[13:16:08 INFO]: [NoCheatPlus] Added block-info for Minecraft 1.7.2 blocks.
[13:16:08 INFO]: [NoCheatPlus] Added block-info for Minecraft 1.8 blocks.
[13:16:08 INFO]: [NoCheatPlus] Inventory checks: FastConsume is available, disabled InstantEat.
[13:16:08 INFO]: [NoCheatPlus] Packet level access: ProtocolLib is not available.
[13:16:08 INFO]: [NoCheatPlus] Version 3.16.0-RC-sMD5NET-b1134 is enabled.
[13:16:08 INFO]: [CommandBook] Enabling CommandBook v2.4:1692-75bb1c8,master
[13:16:08 INFO]: [CommandBook] Maximum wrapper compatibility is enabled. Some features have been disabled to be compatible with poorly written server wrappers.
[13:16:08 INFO]: [CommandBook] 0 Homes(s) loaded
[13:16:08 INFO]: [CommandBook] 0 Warps(s) loaded
[13:16:08 INFO]: [CommandBook] 1 kit(s) loaded.
[13:16:08 INFO]: [Essentials] Enabling Essentials v2.17.2.0
[13:16:08 WARN]: [Essentials] ?4Version mismatch! Please update EssentialsChat to the same version.
[13:16:08 INFO]: Attempting to convert old kits in config.yml to new kits.yml
[13:16:08 INFO]: No kits found to migrate.
[13:16:08 INFO]: [Essentials] Using legacy item data provider as mob spawner provider.
[13:16:08 INFO]: [Essentials] Using legacy item data provider as spawn egg provider.
[13:16:08 INFO]: [Essentials] Using legacy potion meta provider as potion meta provider.
[13:16:09 INFO]: Loaded 852 items from items.csv.
[13:16:09 INFO]: Using locale en_US
[13:16:09 INFO]: [Essentials] ServerListPingEvent: Spigot iterator API
[13:16:09 INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.
[13:16:09 INFO]: [Vault][Economy] Essentials Economy hooked.
[13:16:09 INFO]: [Essentials] Using Vault based permissions (LuckPerms)
[13:16:09 INFO]: [Rankup] Enabling Rankup v1.3
[13:16:09 INFO]: [Rankup] Rankup 1.3 is now enabled.
[13:16:09 INFO]: [AuthMe] Enabling AuthMe v5.6.0-beta1-b2226
[13:16:09 INFO]: [AuthMe] SQLite Setup finished
[13:16:09 WARN]: [AuthMe] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke method 'setup' for fr.xephi.authme.permission.PermissionsManager@56c1a336
[13:16:09 WARN]: [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
[13:16:09 INFO]: [AuthMe] Waiting for 0 tasks to finish
[13:16:09 INFO]: [AuthMe] AuthMe 5.6.0-beta1-b2226 disabled!
[13:16:09 INFO]: [WorldGuard] Enabling WorldGuard v6.1
[13:16:09 INFO]: [WorldGuard] (world) TNT ignition is PERMITTED.
[13:16:09 INFO]: [WorldGuard] (world) Lighters are PERMITTED.
[13:16:09 INFO]: [WorldGuard] (world) Lava fire is blocked.
[13:16:09 INFO]: [WorldGuard] (world) Fire spread is UNRESTRICTED.
[13:16:09 INFO]: [WorldGuard] Loaded configuration for world 'world'
[13:16:09 INFO]: [WorldGuard] (world_nether) TNT ignition is PERMITTED.
[13:16:09 INFO]: [WorldGuard] (world_nether) Lighters are PERMITTED.
[13:16:09 INFO]: [WorldGuard] (world_nether) Lava fire is blocked.
[13:16:09 INFO]: [WorldGuard] (world_nether) Fire spread is UNRESTRICTED.
[13:16:09 INFO]: [WorldGuard] Loaded configuration for world 'world_nether'
[13:16:09 INFO]: [WorldGuard] (world_the_end) TNT ignition is PERMITTED.
[13:16:09 INFO]: [WorldGuard] (world_the_end) Lighters are PERMITTED.
[13:16:09 INFO]: [WorldGuard] (world_the_end) Lava fire is blocked.
[13:16:09 INFO]: [WorldGuard] (world_the_end) Fire spread is UNRESTRICTED.
[13:16:09 INFO]: [WorldGuard] Loaded configuration for world 'world_the_end'
[13:16:09 INFO]: [WorldGuard] Loading region data...
[13:16:09 INFO]: [TreasureChest] Enabling TreasureChest v8.4.5
[13:16:09 INFO]: [SimpleClans] Enabling SimpleClans v2.5.3
[13:16:09 INFO]: [SimpleClans] Version 2.5.3 loaded
[13:16:09 INFO]: [SimpleClans] SQLite Connection successful
[13:16:10 INFO]: [SimpleClans] Clan players: 2
[13:16:10 INFO]: [SimpleClans] Modo Multithreading: false
[13:16:10 INFO]: [SimpleClans] Modo BungeeCord: false
[13:16:10 INFO]: [BattleKits] Enabling BattleKits v2.0.3
[13:16:10 INFO]: [BattleKits] Initializing configs...
[13:16:10 INFO]: [BattleKits] length is 2716
[13:16:10 INFO]: [BattleKits] length is 963
[13:16:10 INFO]: [BattleKits] length is 266
[13:16:10 INFO]: [BattleKits] Not enabling restrictions due to config setting
[13:16:10 INFO]: [BattleKits] Vault found.
[13:16:10 INFO]: [BattleKits] Disabling tag functionality as TagAPI is not installed.
[13:16:10 INFO]: [BattleKits] BattleKits (2.0.3) has been enabled!
[13:16:10 INFO]: [RealisticBackpacks] Enabling RealisticBackpacks v1.6.4
[13:16:10 INFO]: [RealisticBackpacks] Glow effect will not work with this version of craftbukkit!
[13:16:10 INFO]: [RealisticBackpacks] Vault found, economy features enabled.
[13:16:10 INFO]: [RealisticBackpacks] Realistic Backpacks has been enabled.
[13:16:10 INFO]: [KillMoney] Enabling KillMoney v2.4
[13:16:10 INFO]: [EssentialsChat] Enabling EssentialsChat vPre2.14.1.3
[13:16:10 WARN]: ?4Version mismatch! Please update all Essentials jars to the same version.
[13:16:10 INFO]: [DeathChest] Enabling DeathChest v1.13.3
[13:16:10 INFO]: [DeathChest] Could not recognize Bukkit Build-version. Version might be outdated.
[13:16:10 INFO]: [DeathChest] DeathChest v1.13.3 fully loaded with Vault hooked.
[13:16:10 INFO]: [PlayerVaults] Enabling PlayerVaults v3.5.7-b${BUILD_NUMBER}
[13:16:10 INFO]: [CustomEnchantments] Enabling CustomEnchantments v2.4c
[13:16:10 INFO]: [CE] Vault has been detected!
[13:16:10 INFO]: [CE] WorldGuard has been detected!
[13:16:10 INFO]: [CE] All Enchantments have been loaded.
[13:16:10 INFO]: [CE] All Items have been loaded.
[13:16:11 INFO]: [ChestShop] Enabling ChestShop v3.9.0 (build #52)
[13:16:11 INFO]: [ChestShop] Vault loaded! Found an economy plugin!
[13:16:11 INFO]: [Smileychat] Enabling Smileychat v3.1
[13:16:11 INFO]: [SmileyChat] version 3.1 Has been Enabled!
[13:16:11 INFO]: [SmileyChat] Using: Normal Minecraft Chat.
[13:16:11 INFO]: [ScoreboardStats] Enabling ScoreboardStats v0.10.5
[13:16:11 INFO]: [ScoreboardStats] Found plugin: HealthBar
[13:16:11 INFO]: [ScoreboardStats] You are using plugins that requires to activate compatibilityMode
[13:16:11 INFO]: [ScoreboardStats] Otherwise the plugins won't work
[13:16:11 INFO]: [ScoreboardStats] Enable it in the config of this plugin: compatibilityMode
[13:16:11 INFO]: [ScoreboardStats] Registered replacers: [SimpleClansVariables, BukkitGlobalVariables, PlayerPingVariable, BungeeCordVariables, GeneralVariables, BukkitVariables, VaultVariables]
[13:16:11 INFO]: HikariPool-1 - Starting...
[13:16:11 INFO]: HikariPool-1 - Driver does not support get/set network timeout for connections. (org.sqlite.Conn.getNetworkTimeout()I)
[13:16:11 INFO]: HikariPool-1 - Start completed.
[13:16:11 INFO]: Done (6.527s)! For help, type "help" or "?"
[13:16:11 INFO]: Starting GS4 status listener
[13:16:11 INFO]: Query running on 127.0.0.1:41807
[13:16:12 INFO]: Stopping server
[13:16:12 INFO]: [ScoreboardStats] Disabling ScoreboardStats v0.10.5
[13:16:12 INFO]: [ScoreboardStats] Now saving the stats to the database. This could take a while.
[13:16:12 INFO]: HikariPool-1 - Shutdown initiated...
[13:16:12 INFO]: HikariPool-1 - Shutdown completed.
[13:16:12 INFO]: [Smileychat] Disabling Smileychat v3.1
[13:16:12 INFO]: Smileychat Has been Disabled!
[13:16:12 INFO]: [ChestShop] Disabling ChestShop v3.9.0 (build #52)
[13:16:12 INFO]: [CustomEnchantments] Disabling CustomEnchantments v2.4c
[13:16:12 INFO]: [PlayerVaults] Disabling PlayerVaults v3.5.7-b${BUILD_NUMBER}
[13:16:12 INFO]: [DeathChest] Disabling DeathChest v1.13.3
[13:16:12 INFO]: [DeathChest] disabled DeathChest v1.13.3
[13:16:12 INFO]: [EssentialsChat] Disabling EssentialsChat vPre2.14.1.3
[13:16:12 INFO]: [KillMoney] Disabling KillMoney v2.4
[13:16:12 INFO]: [RealisticBackpacks] Disabling RealisticBackpacks v1.6.4
[13:16:12 INFO]: [RealisticBackpacks] Realistic Backpacks has been disabled.
[13:16:12 INFO]: [BattleKits] Disabling BattleKits v2.0.3
[13:16:12 INFO]: [BattleKits] BattleKits has been disabled.
[13:16:12 INFO]: [SimpleClans] Disabling SimpleClans v2.5.3
[13:16:12 INFO]: [TreasureChest] Disabling TreasureChest v8.4.5
[13:16:12 INFO]: [WorldGuard] Disabling WorldGuard v6.1
[13:16:12 INFO]: [WorldGuard] Shutting down executor and waiting for any pending tasks...
[13:16:12 INFO]: [Rankup] Disabling Rankup v1.3
[13:16:12 INFO]: [Rankup] Rankup 1.3 is now disabled.
[13:16:12 INFO]: [Essentials] Disabling Essentials v2.17.2.0
[13:16:12 INFO]: [Vault][Economy] Essentials Economy unhooked.
[13:16:12 INFO]: [CommandBook] Disabling CommandBook v2.4:1692-75bb1c8,master
[13:16:12 INFO]: [Vault] Disabling Vault v1.5.6-b49
[13:16:12 INFO]: [NoCheatPlus] Disabling NoCheatPlus v3.16.0-RC-sMD5NET-b1134
[13:16:12 INFO]: [NoCheatPlus] Added hook: AllViolations(NCP) [1.0].
[13:16:12 INFO]: [NoCheatPlus] Removed hook: AllViolations(NCP) [1.0].
[13:16:12 INFO]: [NoCheatPlus] Version 3.16.0-RC-sMD5NET-b1134 is disabled.
[13:16:12 INFO]: [Multiverse-Core] Disabling Multiverse-Core v2.5-b699
[13:16:12 INFO]: [Reservations] Disabling Reservations v2.5.1
[13:16:12 INFO]: [Reservations] is disabled!
[13:16:12 INFO]: [AutoMessage] Disabling AutoMessage v2.5.5
[13:16:12 INFO]: [ClearLag] Disabling ClearLag v3.1.6
[13:16:12 INFO]: [ClearLag] Clearlag is now disabled!
[13:16:12 INFO]: [CombatLog] Disabling CombatLog v2.3.0
[13:16:12 INFO]: [CombatLog] Disabled.
[13:16:12 INFO]: [HeadSpawner] Disabling HeadSpawner v1.5.0
[13:16:12 INFO]: [OpenInv] Disabling OpenInv v4.0.8
[13:16:12 INFO]: [CraftserveAgent] Disabling CraftserveAgent v20200313-1954
[13:16:12 INFO]: [HealthBar] Disabling HealthBar v1.8.3
[13:16:12 INFO]: HealthBar disabled, all the health bars have been removed.
[13:16:12 INFO]: [WorldEdit] Disabling WorldEdit v6.1;no_git_id
[13:16:12 INFO]: [LuckPerms] Disabling LuckPerms v5.0.97
[13:16:12 INFO]: [LuckPerms] Starting shutdown process...
[13:16:12 INFO]: [LuckPerms] Closing storage...
[13:16:12 INFO]: [LuckPerms] Goodbye!
[13:16:12 INFO]: [MotdManager] Disabling MotdManager v1.41-b20
[13:16:12 INFO]: [MotdManager] version 1.41-b20 is disabled!
[13:16:12 INFO]: Saving players
[13:16:12 INFO]: Saving worlds
[13:16:12 INFO]: Saving chunks for level 'world'/Overworld
[13:16:12 INFO]: Saving chunks for level 'world_nether'/Nether
[13:16:12 INFO]: Saving chunks for level 'world_the_end'/The End

**Comment by lucko** [comment] 2020-03-19 12:30
Something is shutting your server down shortly after it starts.

```
[13:16:11 INFO]: Done (6.527s)! For help, type "help" or "?"
[13:16:11 INFO]: Starting GS4 status listener
[13:16:11 INFO]: Query running on 127.0.0.1:41807
[13:16:12 INFO]: Stopping server
```

This isn't a LuckPerms issue.

**Comment by MWFIAE** [comment] 2020-03-19 12:33
try adding your plugins one by one until this behaviour starts occuring, then you will most likely find the faulty plugin

**Closed** 2020-03-19 12:38 UTC
Labels: type: question

**Comment by Lukas1921** [comment] 2020-03-19 13:04
LP works fine! The problem was authme. Thanks for the help.
Ps. great plugin 'LuckPerms'.
