### ISSUE TITLE
Support for selectors in Sponge

### ISSUE THREAD

**Issue by BrainStone** [lucko/LuckPerms#278] opened 2017-05-08 07:56 UTC
Currently the Minecraft selectors `@a`, `@p`, `@r` *(maybe even `@e`?)* (and upcomming `@s`) are not supported (at least) in Sponge!

Also all vanilla filters like `@a[m=2]` should be supported.

**Comment by lucko** [comment] 2017-05-08 08:08
Duplicate of #275

**Closed by lucko** 2017-05-08 08:08 UTC
