### ISSUE TITLE
LPB reading contexts same as LP

### ISSUE THREAD

**Issue by Ahmadh26** [lucko/LuckPerms#2417] opened 2020-06-27 19:34 UTC
Hey, is it possible to make Luckperms bungee read contexts same as Luckperms bukkit?
i have all of the perms running based on discord contexts of which DiscordSRV give

This is a picture of `Lp user <user> info`
![javaw_sn6YQ8tWR6](https://user-images.githubusercontent.com/57562297/85930572-493d2200-b8c6-11ea-8a3a-72928ce385cf.png)

And this is one where i did `lpb user <user> info`
![javaw_NXal1U1H0y](https://user-images.githubusercontent.com/57562297/85930579-53f7b700-b8c6-11ea-8ab0-d29e731412b2.png)

It doesn't read the same contexts as LP which means my mods don't read the needed perms to run some bungee commands.

**Comment by BrainStone** [comment] 2020-06-28 21:11
Essentially a duplicate of #1668. Throw in your two cents there ;)

**Comment by lucko** [comment] 2020-06-29 14:41
No it's not...


@Ahmadh26 Unfortunately, this is not possible as contexts are calculated very frequently, and are based on the state of the player at that exact given time. It would not be practical to sync them over the network.

**Closed by lucko** 2020-06-29 14:41 UTC

**Comment by MadLad989** [comment] 2024-09-07 16:21
Is there a workaround for this? I'm applying groups via discordsrv contexts but the primary group with /lpb still shows as default. This stops users from having access to permissions from bungee plugins unless I add the group as their parent manually.
