### ISSUE TITLE
[Spigot] Permissions data for your user was not loaded during the pre-login stage

### ISSUE THREAD

**Issue by LowTix** [lucko/LuckPerms#1531] opened 2019-05-15 13:23 UTC
Hello,
I have this error on my BungeeCord server:
https://pastebin.com/YBc8A0fp

I use WaterFall for my proxy, and spigot 1.8.8 for my servers.
I've tried with a normal BungeeCord and it's the same.
(online-mode: false)

Thanks :)

**Comment by lucko** [comment] 2019-05-16 10:59
I suspect this is a duplicate of #1462.

Can you set this option to true

https://github.com/lucko/LuckPerms/blob/d1511e43f2e1d4e900e119756cc87ba76ded9a17/bungee/src/main/resources/config.yml#L458-L461

And then try reproducing the issue again.

If you're able to, then please send over the log file from that period.

**Comment by LowTix** [comment] 2019-05-18 13:44
Hello,
I found the problem. I am currently using the JPremium plugin which allows to authenticate the premium players automatically. This plugin forces the server to set the premium UUID to the player. So I think LuckPerms did not have the same UUID.

**Comment by LowTix** [comment] 2019-05-18 13:44
You want me to send you logs with debug-logins: false?

**Comment by lucko** [comment] 2019-05-27 09:23
Set to `true` - but yes, sounds like it's an issue with JPremium.

You need to report the issue to the author of that plugin. :)

**Closed by lucko** 2019-05-27 09:23 UTC
Labels: status: need more info, type: issue
