### ISSUE TITLE
I cant give per server * permissions to owner/admin ranks

### ISSUE THREAD

**Issue by Dblxy** [lucko/LuckPerms#2043] opened 2020-03-04 01:33 UTC
Im trying to give these permissions only to owners and admins. But its not working and I have no clue why. I have already checked the permissions many times and I'm out of ideas at this point!

**Comment by Jaimss** [comment] 2020-03-04 02:45
I'm not really sure what you are saying the issue is, but check for inheritance issues maybe? I have run into issues with my owner/admin classes inheriting things from each other.

This might not be the issue though. Explain what is actually happening, please.

**Comment by Andre601** [comment] 2020-03-04 08:09
Please answer to your already existing issue (#2042) instead of opening a new one.
Just because an issue is closed doesn't mean you can't answer there.

**Comment by Dblxy** [comment] 2020-03-04 13:21
Ok, I figured it out! I had renamed the lobby server to hub and never changed the server name in the config file for the lobby. So I gave it to the hub server but since that was still called lobby it didn't apply them obviously. Thank you!

**Comment by Andre601** [comment] 2020-03-04 13:26
Glad the issue got resolved.
Please remember to close the issue, if you have no more questions or issues.

**Closed** 2020-03-04 19:56 UTC
