### ISSUE TITLE
LuckPerms not starting after migration to MySQL

### ISSUE THREAD

**Issue by Bloodrayne1995** [lucko/LuckPerms#681] opened 2018-01-13 13:34 UTC
Hi,

after the migration to MySQL LuckPerms don`t start.
Log: [https://pastebin.com/2Lc2P5dL](https://pastebin.com/2Lc2P5dL)

I tried to remove the hikari library and updating it. Even tried 3 builds of LuckPerms (First: 4.0.87, Second: 4.0.88 and last: 4.0.80).

Can you please help me?

Greetings
EONABloodrayne

**Comment by lucko** [comment] 2018-01-13 13:37
Do you have any other plugins on your server which package a version of the Hikari library?

**Comment by Bloodrayne1995** [comment] 2018-01-13 14:27
In the console log I saw that LogBlock tries to connect to database and use hikari too. But I dont know which version of hikari.

**Comment by Bloodrayne1995** [comment] 2018-01-13 14:32
I use the latest build of LogBlock and according to github it uses hakari 2.7.4. The same version as LuckPerms use.

**Comment by lucko** [comment] 2018-01-13 23:33
Will hopefully be fixed by: 19e6d4e4c8d3105d7ee325612ddc46dc55d31f91

It's an experimental change, but in my testing it seems to work as intended. 

You can download the latest builds from:
https://ci.lucko.me/job/LuckPerms/

___

@Phoenix616 Forgive me if I'm wrong, but I recall you saying you were also having issues with this system - hopefully the above change will resolve that too.

Closing for now - @Bloodrayne1995 Let me know if you experience any further issues :)

**Closed by lucko** 2018-01-13 23:33 UTC

**Comment by Bloodrayne1995** [comment] 2018-01-15 18:36
Hey,

I tested the latest build and it works.
Thank you for your help.
