### ISSUE TITLE
Target selectors not working

### ISSUE THREAD

**Issue by Katrix-** [lucko/LuckPerms#275] opened 2017-05-07 21:18 UTC
I have a command block that when executed, sets the group of the player who clicked the button that triggered using target selectors (`@p`). LuckPerms don't let me do that.

**Comment by lucko** [comment] 2017-05-07 21:19
It's down to your server implementation to do this. I won't be adding support in LP.

**Comment by Katrix-** [comment] 2017-05-07 21:20
I'm using Sponge. Is there any other way that I can add a group to a player when they do something if not with LuckPerms?

**Comment by lucko** [comment] 2017-05-07 21:26
Perhaps you can find a plugin which supports adding replacements, or ask the people behind Sponge if they can add support for it.

**Comment by Katrix-** [comment] 2017-05-07 21:29
That's why I'm confused why it's not working. Sponge already supports this through `SelectorCommandElement`. The default player argument should handle that just fine. https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/command/args/GenericArguments.java#L1136

**Comment by lucko** [comment] 2017-05-07 21:32
I don't use Sponge's argument parsing. The selectors would need to be replaced in the raw command string.

**Comment by Katrix-** [comment] 2017-05-07 21:36
Sponge supports parsing target selectors through the `Selector` class. The reason it's not replaced automatically is that Selectors can select multiple players. Would it be possible to run the target selector through the `Selector` class if it is a selector, and then see if it's size is 1? If it's not one, throw an error?

**Closed** 2017-05-07 21:52 UTC

**Comment by lucko** [comment] 2017-05-07 21:56
Should work fine. Behaviour should be the same as with Sponge parsed command arguments.

**Comment by Katrix-** [comment] 2017-05-07 22:06
Thanks

**Comment by BrainStone** [comment] 2017-05-08 08:19
This code should be in 3.1.35, right? Because it's not working.

LP: 3.1.35-sponge
Minecraft: 1.11.2
Sponge: SpongeForge-1.11.2-2282-7.0.0-BETA-2301

**Comment by lucko** [comment] 2017-05-08 09:20
If it's not replaced, it means there were no results for the selector.

**Comment by BrainStone** [comment] 2017-05-08 10:00
I ran it from an commandblock (while standing next to it) and I ran the command myself (I have full permissions). And I literally used that command. `@p` nothing more, nothing less.

**Comment by BrainStone** [comment] 2017-05-08 10:42
Yep it's Sponge. For some reason they renamed the selectors.
Here's a list:

`@a` -> `@minecraft:all_players`
`@p` -> `@minecraft:nearest_player`
`@r` -> `@minecraft:random`
`@e` -> `@minecraft:all_entities`

**Comment by Katrix-** [comment] 2017-05-08 13:20
Working wonderful for me with `@p[r=10]`. Whatever problems you're having, it's most likely a Sponge problem at this point. spongeforge-1.10.2-2281-5.2.0-BETA-2308.

**Comment by BrainStone** [comment] 2017-05-08 14:30
Yeah. Probably it's API version 7.0.0

**Comment by mGodinho87** [comment] 2024-01-27 23:12
Hi, i'm using spigot and I have this error here, the same error apper when i use @p instead of @minecraft:nearest_player or @p[r=10]. Can someone help me to solve it please?

[LuckPerms]: Error parsing selector '@minecraft:nearest_player' for CraftPlayer{name=Goodinhoo} executing [user, @minecraft:nearest_player, meta, removesuffix, 7, &f𓆐&f]
java.lang.IllegalArgumentException: Could not parse selector: @minecraft:nearest_player
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.selectEntities(CraftServerMixin.java:2378) ~[arclight-1.20.1-1.0.2-730181a4.jar%23332!/:arclight-1.20.1-1.0.2-730181a4]
        at me.lucko.luckperms.bukkit.BukkitCommandExecutor.resolveSelectors(BukkitCommandExecutor.java:140) ~[?:?]
        at me.lucko.luckperms.bukkit.BukkitCommandExecutor.onCommand(BukkitCommandExecutor.java:81) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[arclight-1.20.1-1.0.2-730181a4.jar%23332!/:arclight-1.20.1-1.0.2-730181a4]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[arclight-1.20.1-1.0.2-730181a4.jar%23332!/:arclight-1.20.1-1.0.2-730181a4]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServerMixin.java:877) ~[arclight-1.20.1-1.0.2-730181a4.jar%23332!/:arclight-1.20.1-1.0.2-730181a4]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[arclight-1.20.1-1.0.2-730181a4.jar%23332!/:arclight-1.20.1-1.0.2-730181a4]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[brigadier-1.1.8.jar%23110!/:?]
        at net.minecraft.commands.Commands.m_242674_(CommandsMixin.java:257) ~[server-1.20.1-20230612.114412-srg.jar%23503!/:?]
        at net.minecraft.commands.Commands.m_230957_(CommandsMixin.java:237) ~[server-1.20.1-20230612.114412-srg.jar%23503!/:?]
        at dev.ftb.mods.ftbquests.quest.reward.CommandReward.claim(CommandReward.java:104) ~[ftb-quests-forge-2001.3.2.jar%23407!/:2001.3.2]
        at dev.ftb.mods.ftbquests.quest.TeamData.claimReward(TeamData.java:539) ~[ftb-quests-forge-2001.3.2.jar%23407!/:2001.3.2]
        at dev.ftb.mods.ftbquests.quest.TeamData.checkAutoCompletion(TeamData.java:569) ~[ftb-quests-forge-2001.3.2.jar%23407!/:2001.3.2]
        at dev.ftb.mods.ftbquests.quest.Quest.onCompleted(Quest.java:526) ~[ftb-quests-forge-2001.3.2.jar%23407!/:2001.3.2]
        at dev.ftb.mods.ftbquests.quest.task.Task.onCompleted(Task.java:115) ~[ftb-quests-forge-2001.3.2.jar%23407!/:2001.3.2]
        at dev.ftb.mods.ftbquests.quest.TeamData.markTaskCompleted(TeamData.java:643) ~[ftb-quests-forge-2001.3.2.jar%23407!/:2001.3.2]
        at dev.ftb.mods.ftbquests.quest.TeamData.setProgress(TeamData.java:625) ~[ftb-quests-forge-2001.3.2.jar%23407!/:2001.3.2]
        at dev.ftb.mods.ftbquests.quest.task.AbstractBooleanTask.submitTask(AbstractBooleanTask.java:28) ~[ftb-quests-forge-2001.3.2.jar%23407!/:2001.3.2]
        at dev.ftb.mods.ftbquests.quest.task.Task.submitTask(Task.java:289) ~[ftb-quests-forge-2001.3.2.jar%23407!/:2001.3.2]
        at dev.ftb.mods.ftbquests.net.SubmitTaskMessage.lambda$handle$0(SubmitTaskMessage.java:44) ~[ftb-quests-forge-2001.3.2.jar%23407!/:2001.3.2]
        at dev.ftb.mods.ftbquests.quest.ServerQuestFile.withPlayerContext(ServerQuestFile.java:159) ~[ftb-quests-forge-2001.3.2.jar%23407!/:2001.3.2]
        at dev.ftb.mods.ftbquests.net.SubmitTaskMessage.handle(SubmitTaskMessage.java:44) ~[ftb-quests-forge-2001.3.2.jar%23407!/:2001.3.2]
        at dev.architectury.networking.simple.MessageDecoder.lambda$createReceiver$0(MessageDecoder.java:52) ~[architectury-9.1.12-forge.jar%23345!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:67) ~[server-1.20.1-20230612.114412-srg.jar%23503!/:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23503!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23503!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23503!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23503!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23503!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23503!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23503!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23503!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[server-1.20.1-20230612.114412-srg.jar%23503!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:732) ~[server-1.20.1-20230612.114412-srg.jar%23503!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2074) ~[server-1.20.1-20230612.114412-srg.jar%23503!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23503!/:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown selector type '@m' at position 1: @<--[HERE]
