### ISSUE TITLE
Cant fix luckperm

### ISSUE THREAD

**Issue by BrownciosB** [lucko/LuckPerms#2115] opened 2020-03-28 14:52 UTC
I work with luck perms.
If i set a prefix /lp group owner meta addprefix 100 &4[&c&lOwner&4]
I get this if i chat [Owner] [Owner] BrownciosB
i get 2 prefixes. but i want onliy one time like this [Owner] BrownciosB
How do i fix that pleas help me as soon you guys can !!

![image](https://user-images.githubusercontent.com/62801384/77825814-0c695f80-710c-11ea-9c61-e115f099464a.png)

**Comment by Tobi406** [comment] 2020-03-28 14:55
Duplicate of #2114

**Closed** 2020-04-05 15:55 UTC
Labels: type: question
