### ISSUE TITLE
Set player position on Track

### ISSUE THREAD

**Issue by Seeroh** [lucko/LuckPerms#133] opened 2017-01-16 12:19 UTC
I do not see an easy way to cleanly modify a player's group when doing donation ranks. If a player donates to get the first donation rank, it's as easy as doing a track promotion, but if the player donates to 3 ranks in immediately, or donates again, and skips multiple ranks, doing a promotion would not handle the multiple group progression well. I'd have to account for removing donation ranks, and any way I look at it, it begins to become messy, or completely ruins the track system by having multiple groups.

So maybe there could be a way to set a player's placement on a track?
`/lp user luck place {track} {position}`

There is probably a better way to word that command, but it shows what I mean.

**Comment by lucko** [comment] 2017-01-16 16:41
"but if the player donates to 3 ranks in immediately, or donates again, and skips multiple ranks, doing a promotion would not handle the multiple group progression well. I'd have to account for removing donation ranks, and any way I look at it, it begins to become messy, or completely ruins the track system by having multiple groups."

Using the `parent set` command avoids this problem. If you want people to remain in different track groups as well, perhaps #112 would fix this?

**Comment by Seeroh** [comment] 2017-01-17 00:51
How would I go about doing that? Easily keeping a player on the track for ingame ranks, as well as dealing with jumping multiple ranks in donations?

**Comment by lucko** [comment] 2017-01-17 21:38
Ok, duplicate of #112 in that case.

**Closed by lucko** 2017-01-17 21:38 UTC
